### ISSUE TITLE
Update the Acknowledgements text 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#101]
Using the Word doc from @rosibaj update:
- [ ] the [acknowledgements page](https://virusseq-dataportal.ca/acknowledgements) text to: 

- [ ] the acknowledgements popup on download 

Additionally, on the [acknowledgements page](https://virusseq-dataportal.ca/acknowledgements) we need to provide the policy as a PDF that can be downloaded. 
- [ ] Add a pdf copy of the policy to the bucket to be used by the UI 
- [ ] Add a button on the acknowledgements page at the top right of the header that downloads the pdf from the bucket url:
![image](https://user-images.githubusercontent.com/15824252/133673584-8185896c-3093-4376-8889-d405150a263f.png)

**Comment by b-f-chan** [comment]
@sifavahora - To follow-up with @caravinci if this is testable in a dev/QA environment and the status of it

**Comment by sifavahora** [comment]
@caravinci advised that we have made the changes to the acknowledgement text recently - this is an older ticket. need to confirm with @scottcain if we still need this.

**Comment by sifavahora** [comment]
Doesn't look like its required at the moment. Closing for now. Can reopen if requested.
