### ISSUE TITLE
Suppress duplicated analysis for study `ABPL-AB`

### ISSUE THREAD

**Issue by lindaxiang** [cancogen-virus-seq/portal#106]
107 duplicated analysis are to be suppressed in SONG. 

[ABPL-AB.107.duplicates.txt](https://github.com/cancogen-virus-seq/portal/files/7225862/ABPL-AB.107.duplicates.txt)

**Comment by lindaxiang** [comment]
The above 107 analysis have been suppressed from the portal.

**Comment by rosibaj** [comment]
thank you very much @lindaxiang !
