### ISSUE TITLE
Null submitted crashing on host_age_bin

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#107]
![image](https://user-images.githubusercontent.com/15824252/134790823-ec1e601c-3ef5-4ac1-97fd-063474365fa7.png)

**Comment by rosibaj** [comment]
- max_buckets temporarily upped to 10,000
- @caravinci investigating updating the query to a more scalble version for `sample_id`

**Comment by caravinci** [comment]
currently, arranger uses the following code to provide `bucket_count` (which is how we're getting the total for this field)
<img width="744" alt="image" src="https://user-images.githubusercontent.com/2107110/134959038-b60ffc3d-74e3-4545-abde-d82ebb62afa0.png">
https://github.com/overture-stack/arranger/blob/master/modules/middleware/src/flattenAggregations.js#L28

Will work on a different implementation to get the `value_count` instead

**Comment by caravinci** [comment]
Added a code fix in the portal to prevent the error message coming up, should we exceed the bucket limit again. Won't solve the issue, but at least will remove red herring messages.
