### ISSUE TITLE
Suppress samples with age > 90

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#108]
![image](https://user-images.githubusercontent.com/15824252/134960723-885731b7-3de2-40d1-a0b8-0707e7c31e15.png)

FILE OF SAMPLES TO SUPPRESS: 

[38-sampels-to-remove-bc-age-over-90.txt](https://github.com/cancogen-virus-seq/portal/files/7238336/38-sampels-to-remove-bc-age-over-90.txt)

**Comment by lindaxiang** [comment]
The following analysis belonged to the above samples have been suppressed from the portal.
[MCPL-MB.22.age_over_90.analysisId.txt](https://github.com/cancogen-virus-seq/portal/files/7239263/MCPL-MB.22.age_over_90.analysisId.txt)
 
[RRPL-SK.16.age_over_90.analysisId.txt](https://github.com/cancogen-virus-seq/portal/files/7239264/RRPL-SK.16.age_over_90.analysisId.txt)

**Comment by nithujohn** [comment]
Can I re- upload the 38 samples?

**Comment by rosibaj** [comment]
@nithujohn yes ma'am we are ready!  please go ahead and do so!
