### ISSUE TITLE
Update `host_age_bin` from `90 - 99` to `90+`

### ISSUE THREAD

**Issue by lindaxiang** [cancogen-virus-seq/portal#110]
Here is the sample list on the portal which have `host_age_bin`=`90 - 99`
[22_samples.age_bin_to_update.txt](https://github.com/cancogen-virus-seq/portal/files/7239286/22_samples.age_bin_to_update.txt)

- 90-99 --> 90+
- For three samples with wrong age bin, update to correct age bin: 
![image](https://user-images.githubusercontent.com/15824252/135093378-68e118da-07b0-474b-ae57-b2c467514583.png)

-

**Comment by nknox** [comment]
Age bin should be adjusted to match host age (correct value).

Thanks!
Natalie

**Comment by nithujohn** [comment]
Hi Linda and Rosita, Please change the age bins according to the age. Thanks, Nithu

**Comment by lindaxiang** [comment]
@nithujohn @rosibaj 
All the `age_bin` with value `90 - 99` have been updated to new CV term `90+` on the portal. Please give a check. Thanks.

**Comment by nithujohn** [comment]
@lindaxiang I have checked the age bin section and yea they have changed to 90+ age bin (57 samples). Thanks!
