### ISSUE TITLE
Add schema validations between `host_age` and `host_age_bin`

### ISSUE THREAD

**Issue by lindaxiang** [cancogen-virus-seq/portal#111]
**host\_age**|**host\_age\_bin**
:-----:|:-----:
age>=0 and age<=9 or age=null|0 - 9
age>=10 and age<=19 or age=null|10 - 19
age>=20 and age<=29 or age=null|20 - 29
age>=30 and age<=39 or age=null|30 - 39
age>=40 and age<=49 or age=null|40 - 49
age>=50 and age<=59 or age=null|50 - 59
age>=60 and age<=69 or age=null|60 - 69
age>=70 and age<=79 or age=null|70 - 79
age>=80 and age<=89 or age=null|80 - 89
age=null|90+

**Comment by rosibaj** [comment]
@lindaxiang this is in prod now i believe, but just want to confirm with you as well :)
