### ISSUE TITLE
CoViZu FE Server Integration

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#114]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=OV&title=Integration%3A+CoViZu#Integration:CoViZu-HostingCoViZufront-end

- [ ] Host vanilla CoviZu
- [ ] Adjust headers with NEW tag 
- [ ] If time, brand the CoViZu hosted page with header

**Comment by samrichca** [comment]
scope update
- feature flag (localStorage.COVIZU=true)
- add "Visualize Data NEW" to navigation
-

**Comment by b-f-chan** [comment]
Thanks @samrichca great work integrating this!  Some testing feedback:

For the header verbiage, I don’t think the link changes we discussed with @kcullion  are added yet, but just to re-summarize:

- `Covizu` should go to Art’s github page/repo: https://github.com/PoonLab/CoVizu
- `Canadian VirusSeq data` should return to the exploration page: https://virusseq-dataportal.ca/explorer

Also looks like switching to French works.  But a couple small changes/requests:

- Can we remove in both English and French, the estimated time in the loading/spinner modal (`~10 sec`)?  I don’t want to set any expectation for the user, if the data grows this could take longer, or could be dependent on their connection speed and client setup.
- If you are on English or French, and click the same language again, it goes to a 404 page.  Can we either disable the currently selected option, OR if not, when they click, just reload the current language page?

Thanks!
