### ISSUE TITLE
Contaminated AB samples 

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#119]
Another set of AB contamination.

hCoV-19/CANADA/ABPHL-14778/2021
hCoV-19/CANADA/ABPHL-14779/2021
hCoV-19/CANADA/ABPHL-14780/2021
hCoV-19/CANADA/ABPHL-14781/2021
hCoV-19/CANADA/ABPHL-14783/2021
hCoV-19/CANADA/ABPHL-14784/2021
hCoV-19/CANADA/ABPHL-14785/2021
hCoV-19/CANADA/ABPHL-14786/2021
hCoV-19/CANADA/ABPHL-14787/2021
hCoV-19/CANADA/ABPHL-14788/2021
hCoV-19/CANADA/ABPHL-14789/2021
hCoV-19/CANADA/ABPHL-14790/2021
hCoV-19/CANADA/ABPHL-14791/2021
hCoV-19/CANADA/ABPHL-14792/2021
hCoV-19/CANADA/ABPHL-14795/2021

@b-f-chan Can you please suppress the above IDs? Thanks!

**Comment by b-f-chan** [comment]
@nithujohn we have suppressed these, but are waiting to re-index the data so the changes reflect in the portal.  We hope to have this done in the next couple days, will update again shortly.

**Comment by b-f-chan** [comment]
Hi @nithujohn, these have been suppressed in the portal.  Seems you have already done the verification as well.  If you are satisfied, please close the ticket, thanks!
