### ISSUE TITLE
UI Feedback round 2

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#12]
## Search page
- [x] Scroll bar on dropdown needs to be removed (windows/Google Chrome)
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/d53f103b-d86c-431b-bbb4-ddd7c29e97ba)
- [x]  make the numbers font size 12
![image](https://user-images.githubusercontent.com/15824252/114571135-6a4be500-9c44-11eb-8265-500592ea73e8.png)
- [x] remove # files in facet
- [x] Footer link order. Please use the following order: "About CanCOGeN  •  Policies  •  Contact Us  •  Submitter Login" 
![image](https://user-images.githubusercontent.com/18424138/115053215-e183b200-9eac-11eb-87a2-e368ac7986de.png)

**Comment by caravinci** [comment]
Along with this ticket, will remove the "showing x-y of z files".
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/35740594-2754-4641-9012-251a4922c8bd)

**Comment by rosibaj** [comment]
@caravinci that was a misunderstanding. This comes of unnecessarily moving too fast. If I had had time to offer the feedback correctly in a ticket we wouldn't be having this issue now.

![image](https://user-images.githubusercontent.com/15824252/115899028-4189d380-a42c-11eb-9a3d-280b37dacf75.png)

**Comment by caravinci** [comment]
Apologies. I misunderstood what Christina said.

**Comment by rosibaj** [comment]
@caravinci looks great thanks for updates!
