### ISSUE TITLE
CoViZu prototype

### ISSUE THREAD

**Issue by samrichca** [cancogen-virus-seq/portal#120]
- Make a prototype of CoViZu embedded into a page in the React application.
- Need to make sure data fetching, events, and dependencies work properly.
- Timebox to Thursday for the prototype & part of Friday for planning further work.

**Comment by b-f-chan** [comment]
Prototype successfully completed --> Final decision with @samrichca @joneubank after deliberating is to embed the viz within the React site/app itself.
