### ISSUE TITLE
Updation of BC metadata 

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#121]
BC has gotten permission to share additional metadata (age bin, gender and purpose of sequencing to limited resolution). Is it possible to update these in the portal?

**Comment by scottcain** [comment]
@nithujohn About the metadata, where can we get it? You can email it to me if that's easy. I think we might get this addressed next week.

**Comment by nithujohn** [comment]
@scottcain The metadata is shared with me via NextCloud through National Microbiology Laboratory which is not shared with me yet as I have not confirmed the updation process. If you want I can mail them and they will share the updations with me and cc you as well with mail.

**Comment by scottcain** [comment]
That would be great; we'll start working on a plan next week and having access to the required updates will make that planning easier.

**Comment by scottcain** [comment]
@lindaxiang is this issue resolved?

**Comment by nithujohn** [comment]
@scottcain I have attached the file for the updation. Thanks!
[BC metadata update.txt](https://github.com/cancogen-virus-seq/portal/files/7571707/BC.metadata.update.txt)

**Comment by lindaxiang** [comment]
@nithujohn @scottcain  I am working on updating of the BC metadata. However just found that for `purpose of sequencing`, the provided the updating term: `Targeted sequencing` is not in the allowed list. 
Can you tell me which term is good to go?

FYI, here is the list of CV terms for `purpose of sequencing`:
```
              "Baseline surveillance (random sampling)",
              "Targeted surveillance (non-random sampling)",
              "Priority surveillance project",
              "Screening for Variants of Concern (VoC)",
              "Longitudinal surveillance (repeat sampling of individuals)",
              "Re-infection surveillance",
              "Vaccine escape surveillance",
              "Travel-associated surveillance",
              "Domestic travel surveillance",
              "Interstate/ interprovincial travel surveillance",
              "Intra-state/ intra-provincial travel surveillance",
              "International travel surveillance",
              "Surveillance of international border crossing by air travel or ground transport",
              "Surveillance of international border crossing by air travel",
              "Surveillance of international border crossing by ground transport",
              "Surveillance from international worker testing",
              "Cluster/Outbreak investigation",
              "Multi-jurisdictional outbreak investigation",
              "Intra-jurisdictional outbreak investigation",
              "Research",
              "Viral passage experiment",
              "Protocol testing experiment",
              "Not Applicable",
              "Missing",
              "Not Collected",
              "Not Provided",
              "Restricted Access"
```

**Comment by lindaxiang** [comment]
@nithujohn @scottcain 
Also for sample
```
2021-09-02      BC_54832        Unknown Not Provided    Not Provided    Baseline surveillance (random sampling)
```
`host age bin` is `Unknown`, which is also NOT in the allowed list of `host age bin`:
```
              "0 - 9",
              "10 - 19",
              "20 - 29",
              "30 - 39",
              "40 - 49",
              "50 - 59",
              "60 - 69",
              "70 - 79",
              "80 - 89",
              "90+",
              "Not Applicable",
              "Missing",
              "Not Collected",
              "Not Provided",
              "Restricted Access"
```
 Can you let me know which NA value you want to put there? Thanks.

**Comment by nithujohn** [comment]
> @nithujohn @scottcain Also for sample
> 
> ```
> 2021-09-02      BC_54832        Unknown Not Provided    Not Provided    Baseline surveillance (random sampling)
> ```
> 
> `host age bin` is `Unknown`, which is also NOT in the allowed list of `host age bin`:
> 
> ```
>               "0 - 9",
>               "10 - 19",
>               "20 - 29",
>               "30 - 39",
>               "40 - 49",
>               "50 - 59",
>               "60 - 69",
>               "70 - 79",
>               "80 - 89",
>               "90+",
>               "Not Applicable",
>               "Missing",
>               "Not Collected",
>               "Not Provided",
>               "Restricted Access"
> ```
> 
> Can you let me know which NA value you want to put there? Thanks.

@lindaxiang Not Provided can be used instead of Unknown

**Comment by lindaxiang** [comment]
Thanks @nithujohn . What about the values for `purpose of sequencing`?

**Comment by nithujohn** [comment]
@lindaxiang  I am confirming the tag with NML most probably it will be "Targeted surveillance (non-random sampling)"

**Comment by nithujohn** [comment]
@lindaxiang it's "Targeted surveillance (non-random sampling)" confirmed by NML

**Comment by lindaxiang** [comment]
@scottcain @nithujohn all the metadata in above file(`BC metadata update.txt`) have been updated on Prod. Please give a check. Thanks.

**Comment by nithujohn** [comment]
@scottcain @lindaxiang Thank you so much and they are updated!
