### ISSUE TITLE
AB Duplicate IDs in the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#122]
@scottcain Please suppress the duplicate AB IDs in the portal. Thanks !
[Duplicate IDs AB.txt](https://github.com/cancogen-virus-seq/portal/files/7437085/Duplicate.IDs.AB.txt)

**Comment by lindaxiang** [comment]
@nithujohn @scottcain 
The duplicated analysis belong to the above samples have been suppressed from the portal. Please check!

**Comment by nithujohn** [comment]
Thank you! @lindaxiang @scottcain
