### ISSUE TITLE
French name converting to symbols 

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#123]
@scottcain Hi Scott, New Brunswick - Vitalité Health Network is converting to New Brunswick - Vitalit� Health Network while uploading to the portal which causes error while uploads. Please have a look at your end. Thanks!

**Comment by scottcain** [comment]
@nithujohn I'm trying to get a grip on a reasonably easy way to work around this, which basically involves forcing something to convert "special" characters (ie, the ones not used in English) to the ASCII character set, which should allow you to upload the data. A longer term fix should come along eventually, but my understanding is that it's tricky.

So, my question to you is this: if you were to hand edit the file that has the accented e in it, what would you use, and on what operating system? I'm trying to see if there is a way we could open the file and "save as" or copy and paste the contents to somewhere and save in such a way that this character change would be done automatically, because I don't expect you to manually look for every character that might be a problem and change it yourself.

**Comment by nithujohn** [comment]
@scottcain I am using Windows operating system (64-bit operating system). I have also attached one sample metadata file from NB for you to test. Hope this will help! Thanks
[NBsample.txt](https://github.com/cancogen-virus-seq/portal/files/7500485/NBsample.txt)

**Comment by scottcain** [comment]
OK, this is going to sound a little crazy, but here goes: do you use Excel if you want to edit these files? I googled for methods of removing diacritical marks and found several pages that basically list the same solution: write a simple VBA function that will remove them. Is that something you'd be interested in trying? Below I'll paste a link to a short video where it's explained, plus a page where you could copy and paste the function from.  Basically, the way I would see it working is that you'd open the metadata file, and then a new sheet where you'd have Excel run the function to remove the diacriticals and then you could save that as the new upload. It's ugly for sure, and I'd rather see a cleaner solution, but this at least shouldn't take too long to implement. If I had a Windows machine, I'd do it for you and send you a template, alas.

Short video:
https://www.youtube.com/watch?v=PQDEtFmpkFg

Page where it's described and can be copy and pasted from:
https://www.extendoffice.com/documents/excel/707-excel-replace-accented-characters.html

**Comment by nithujohn** [comment]
Ok, but does it affect the metadata schema (https://github.com/cancogen-virus-seq/metadata-schemas/blob/main/schemas/consensus_sequence.json) ? I mean if I remove those will it cause another error. Well, let me try with one sample. If it works I will let you know :)

**Comment by nithujohn** [comment]
@scottcain I tried by removing the accents and it didn't work but I re- tried with the accent and it worked. Let me se if the whole lot goes in

**Comment by nithujohn** [comment]
![image](https://user-images.githubusercontent.com/85367999/140844341-952d39a9-ae3c-449b-bea9-79ea81f15e04.png)
When I uploaded one sample, it was accepted but multiple samples the same error.

**Comment by nithujohn** [comment]
So when I submitted one sample each for NB there is no error for French names but when I submitted for instance I received 507 samples in one file it causes error. Using fasta uploader I submitted all the NB files to the portal.

**Comment by scottcain** [comment]
@nithujohn, during the call yesterday, I think I heard you say you had uploaded all these sequences. Is that correct? Did you do them one at a time?!?

Also, would it be possible to get the file with 507 samples in it. We are trying to reproduce this problem in our dev environment. Thanks!

**Comment by nithujohn** [comment]
@scottcain Yes, I have uploaded all the sequences but didn't do it one time. I used [fasta-uploader](https://github.com/cidgoh/FastaUploader#fasta-uploader) which broke the sets in to batch of 5 and uploaded it.
[NB505.txt](https://github.com/cancogen-virus-seq/portal/files/7514681/NB505.txt)

**Comment by scottcain** [comment]
@nithujohn is this the one that you asked us to suppress in #151 ?

Also, before you indicated that uploading one (or a few) at a time works, is that not the case with the omicron sample, or is it just that you have to wait for us to suppress it, and then you'll try again with this sample?

**Comment by nithujohn** [comment]
@scottcain This is a different sample, the one I have asked to suppress in #151 is PHO sample. I have got another omicron as well detected in Quebec

**Comment by nithujohn** [comment]
it worked for the samples from New Brunswick but not for Quebec.

**Comment by scottcain** [comment]
Shoot. So much for having a work around. @jaserud do you have any thoughts on this new development?

**Comment by nithujohn** [comment]
@scottcain I think there was an encoding issue with the files I received and I have changed it to UTF-8 and it worked!

**Comment by scottcain** [comment]
thank you so much for figuring this out. I had a feeling it had something to do with encoding but it was so hard to debug remotely.
