### ISSUE TITLE
Files and Viral Genomes have different size

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#124]
@scottcain Hi Scott, I just noticed the file numbers and viral genomes have different numbers. Can you please  have a look. Thanks!
![image](https://user-images.githubusercontent.com/85367999/140184134-474c1e4b-95fa-4fae-aee1-fafeb1a2ddf5.png)
![image](https://user-images.githubusercontent.com/85367999/140184175-999ad224-75b8-49c1-b5fe-fdd56bd45974.png)

**Comment by nithujohn** [comment]
I have included two pics first one with the discrepancy and the second is today's upload as I noticed this after the uploads!

**Comment by scottcain** [comment]
@lindaxiang can you take a look at this? I'm guessing this is an indexing related issue.

**Comment by lindaxiang** [comment]
@nithujohn @scottcain  I will take a look. 
The different number of files and genomes means there are some duplicated samples being submitted. 

For each batch of submission, I would suggest to do some pre-check of the samples upon the latest portal samples before you initiate the submission:
- retrieve all samples in the new batch of submission
- retrieve all samples from the latest data release on the portal: https://virusseq-dataportal.ca/releases
- compare to check if there are any portal existing samples which duplicate with the samples in the new submission

**Comment by lindaxiang** [comment]
@nithujohn @scottcain 
FYI, the 328 duplicated samples in PHO-ON have been suppressed from the portal.
[PHO-ON.328.duplicated.submitterSampleId.txt](https://github.com/cancogen-virus-seq/portal/files/7478112/PHO-ON.328.duplicated.submitterSampleId.txt)

**Comment by nithujohn** [comment]
@lindaxiang Thanks Linda! but would like to know is it from the recent upload as I went through my submission dashboard as well and was not able to find any duplicates.

**Comment by nithujohn** [comment]
@lindaxiang Hi Linda, can you send me the supressed metadata file. Thanks!

**Comment by lindaxiang** [comment]
@nithujohn do you still need the suppressed metadata for verification? Attached please find it. 
[PHO-ON.328.suppressed.metadata.txt](https://github.com/cancogen-virus-seq/portal/files/7500419/PHO-ON.328.suppressed.metadata.txt)

**Comment by nithujohn** [comment]
@lindaxiang thanks for the file, we cross checked the files with the portal ID. But this will help to confirm the IDs deleted. Thanks again!

**Comment by scottcain** [comment]
Double checking--I think this issue can be closed, right @nithujohn ?
