### ISSUE TITLE
Sample not indexed on the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#125]
@scottcain Hi Scott, I have uploaded AB 5240 and one sample was not indexed on the portal. 
Sample ID: AB_201011
Analysis ID: 32a2bc37-b985-4fb3-a2bc-37b9859fb33d 
![image](https://user-images.githubusercontent.com/85367999/140440560-a405e459-0ded-45af-936e-fad3e1591a9b.png)

**Comment by scottcain** [comment]
@nithujohn has this been addressed?

**Comment by nithujohn** [comment]
Yea, last virusseq meeting!
