### ISSUE TITLE
separate metadata from fasta in downloads

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#126]
Natalie Fox at NML has asked if it would be possible to modify the downloads page to make the fasta and metadata available as separate downloads. Apparently it is fairly common to want to download just the metadata, and being forced to download the gigantic fasta file just to get a pretty small metadata file is a drag. How hard would this be to implement?

**Comment by nithujohn** [comment]
@scottcain Hi Scott, I am receiving lot of requests for this issue. Most of the researchers would like to download only metadata sets rather than the whole set.

**Comment by joneubank** [comment]
Arranger has OOTB methods available for downloading data as a tsv. If all the meta data that is needed is in our search index (and I believe that to be the case) than this is strictly a UI change.

**Comment by caravinci** [comment]
Indeed. This change happens on the DMS-UI side, and we'd need to add a new (custom) exporter in the "downloads" menu, with the appropriate parameters to call the downloads endpoint. not sure how tricky that'd be, but @joneubank is right: we can already do this.

**Comment by caravinci** [comment]
As requested, I'm adding a dropdown functionality to the `Download Dataset` button, in which you can now download the metadata for all files (or any individual rows selected in the table), aside from the existing metadata + fasta downloads.

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/f95bfd38-5a00-4cb3-974c-6b87507d1bc3)

Bonus: to improve usability, I've fixed the hover highlighting within the dropdowns.
