### ISSUE TITLE
Update sample collection dates for exsisting samples in the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#127]
@scottcain Is that possible to update sample collection dates for exsisting samples in the portal. I have attached a file with 5 samples from BC with updated sample collection dates
[fixed_dates_2021_11_08 - dp.txt](https://github.com/cancogen-virus-seq/portal/files/7506978/fixed_dates_2021_11_08.-.dp.txt)

**Comment by lindaxiang** [comment]
@nithujohn @scottcain `sample collection dates` have been updated at the backend for the above 5 samples. 
Please give the portal a bit of time for catching up and then check whether the portal has been updated. Thanks.

**Comment by nithujohn** [comment]
@lindaxiang @scottcain Thank you so much! I checked the IDs and the dates have been updated.

**Comment by scottcain** [comment]
Closing, thanks @lindaxiang
