### ISSUE TITLE
Date submitted not in metadata file?

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#128]
I haven't confirmed this yet but Natalie Fox reports that the date submitted is not in the metadata in the download, which seems fairly important.

**Comment by nithujohn** [comment]
@scottcain Is there any update on this issue? Thanks!

**Comment by b-f-chan** [comment]
@scottcain - Can you confirm if this can be closed?  The related closed ticket that you mentioned (#179), seems to actually fix this issue, we also just re-tested this in prod today.  Specifically, the Submitted Data is now clearly in the downloaded TSV of the metadata.  Can you please close if applicable?
