### ISSUE TITLE
Modify Download button

### ISSUE THREAD

**Issue by christinayung** [cancogen-virus-seq/portal#13]
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/56479112-c05b-4b36-95f5-92ea1cd98f18)

- [ ] Change "File Table" to "Metadata Table" - downloads the metadata tsv
- [ ] Change "File Manifest" to "Consensus Seq" - downloads the fasta file (GZip/XZ)

**Comment by rosibaj** [comment]
@jaserud looks good, but can you `remove` the file manifest option? Moving back to in progress until this feedback is ready for review.

**Comment by rosibaj** [comment]
@jaserud this looks good for the front-end so i will be closing this ticket.  Future feedback will be made as part of the API ticket or a new ticket. 

lgtm thank you!
