### ISSUE TITLE
add genome canada to acknowledgments

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#132]
This is very high priority and should be done this week (ie, before we work out how to add the dynamic content from github)

**Comment by b-f-chan** [comment]
Hi @scottcain do you have the static text for this?  Need some more detail for this

**Comment by scottcain** [comment]
I don't, which makes getting this done difficult. I'll poke some people to see if I can get something.

**Comment by scottcain** [comment]
In production now.
