### ISSUE TITLE
Update metadata schema (Purpose of sequencing)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#133]
@scottcain New tags added to "Purpose of sequencing in the Data harmonizer. Please update the field with the new tags. 
[Purpose of sequencing tags.txt](https://github.com/cancogen-virus-seq/portal/files/7564838/Purpose.of.sequencing.tags.txt)

**Comment by scottcain** [comment]
@nithujohn, @lindaxiang will take look at this next week.

**Comment by scottcain** [comment]
@nithujohn , can you test that this has be updated? If it looks good to you, please feel free to close this issue.

**Comment by nithujohn** [comment]
@scottcain @lindaxiang thank you !
