### ISSUE TITLE
Schema and field updates

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#14]
We have a new Song Schema: https://github.com/cancogen-virus-seq/metadata-schemas/blob/main/schemas/consensus_sequence.json
- [x] Make sure its updated in prod cancogen song: 
- [ ] Update the Maestro mapping to reflect new fields 
- [ ] Update the Arranger project to read the new indexed fields, and arranger configs. 
- - Default table columns to show are marked with "Y" in column C in this doc: https://docs.google.com/spreadsheets/d/1MKOEO1Wi66eXbwEQo_OKpUJ0X0mUIQ7NU7bI86gGrjA/edit 
- - Every field should show as a facet 
- - age/integer slider facet gets correctly initialized to work with the component

**Comment by christinayung** [comment]
The Arranger config JSONs are here: https://github.com/cancogen-virus-seq/metadata-schemas/tree/main/arranger_config.  Currently, project ID and index name are both "file9", and will need to be renamed when applying to VirusSeq Portal.  Issues I couldn't work out:
* Could not make `donors.specimens.submitter_specimen_id` a searchable ID field even after enabling quick search.
* Could not make `host_age` an integer. Facet wouldn't load when doing so.

**Comment by lindaxiang** [comment]
Maestro ES-mapping is here: https://github.com/cancogen-virus-seq/infra/tree/main/helm/maestro/prod

**Comment by christinayung** [comment]
Completed the Arranger configuration
