### ISSUE TITLE
PHO data fix (host age bin)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#140]
@scottcain I have attached the list of samples from PHO that needs to be fixed for host age bin.  
[PHO_age_group_update_20211120.csv](https://github.com/cancogen-virus-seq/portal/files/7583250/PHO_age_group_update_20211120.csv)

**Comment by scottcain** [comment]
@lindaxiang About this issue and the other metadata update issues: is it possible to create a file during the updating process that keeps track of what the old value was and what it was updated to? I'm thinking having at least some sort of rudimentary change log would be nice.

**Comment by scottcain** [comment]
@lindaxiang I'm being told updating this data is very important (the data provider may asked to have the data removed if we don't fix this). So, with or without a change log, please update this as soon as possible.

**Comment by lindaxiang** [comment]
@scottcain yes. I have log file generated to record the changes we made.

**Comment by lindaxiang** [comment]
@scottcain @nithujohn 
PHO host_age_bin data has been updated in the portal. Please have a check. Thanks. 
Here is the update log.

[PHO-data-fix-2022-01-13.txt](https://github.com/cancogen-virus-seq/portal/files/7866324/PHO-data-fix-2022-01-13.txt)

**Comment by nithujohn** [comment]
@lindaxiang thank you so much!
