### ISSUE TITLE
Error while uploading the samples

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#142]
Schema violation error while uploading samples to portal: Restricted Access is a valid ennum for the metadata schema but still shows error
![image](https://user-images.githubusercontent.com/85367999/143487666-07fed6ef-611c-4c6f-8679-676c008d6037.png)
[test.txt](https://github.com/cancogen-virus-seq/portal/files/7604823/test.txt)

**Comment by lindaxiang** [comment]
@nithujohn There is a typo in the metadata as `Restriced Access`. That's why it complains.

**Comment by nithujohn** [comment]
@lindaxiang thanks Linda! I didn't notice that looks like need extra glasses
