### ISSUE TITLE
Upload status of the samples

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#146]
@scottcain Hi Scott, I have attached 3 batches of samples, of them couple of the samples are fully processed, partially processed and queued ones. Can you let me know the status of these samples as which of them needs to be re- uploaded. Thanks!
[BC failed batches dp.xlsx](https://github.com/cancogen-virus-seq/portal/files/7614889/BC.failed.batches.dp.xlsx)

**Comment by scottcain** [comment]
Hi @nithujohn , @jaserud spent a lot of time with this one tracking down a bug, and gave me a list of ids that should NOT be resubmitted ( ie, the rest should):

"BC_143988",
"BC_144830",
"BC_143989",
"BC_143979",
"BC_143982",
"BC_144821",
"BC_143974",
"BC_143971"

**Comment by nithujohn** [comment]
Thank you! @scottcain @jaserud
