### ISSUE TITLE
Overloaded SONG causes 500 errors when Maestro tries to reindex because DB connections can't be established

### ISSUE THREAD

**Issue by jaserud** [cancogen-virus-seq/portal#147]
Issue discovered from original issue: https://github.com/cancogen-virus-seq/portal/issues/95

### Investigation findings:
![Screenshot from 2021-09-16 15-44-43](https://user-images.githubusercontent.com/3143103/133677645-098d2d60-89a5-487f-90d1-7c4e6c8ca8ba.png)

Ok so this was a Song error, as you can see from the screenshot:

* the first two logs entries show that the analysis was published, event emitted by kafka, received by maestro
* the rest of entries show that Maestro was attempting to get this analysis from Song in order to publish it to ES and that request to SONG resulted in a 500 (internal server error), it retried a couple times and then eventually gave up
* Song logs show the request coming in 3 times (initial plus retries) 
* Once maestro exhausted it's retries it gave up and moved on

That analysis is there now as you can see by going [here](https://song.virusseq-dataportal.ca/studies/BCCDC-BC/analysis/ae228aa2-f2ca-4333-a28a-a2f2ca13333a)

Looking at Song logs for the same time as these 500 errors ...

![Screenshot from 2021-09-16 16-00-18](https://user-images.githubusercontent.com/3143103/133678018-e63a2278-3f45-44d3-9d74-a11a6f9453c1.png)

We can see that this instance of Song was unable to get a connection to the database. It is strange that only this one GET request failed while the rest of the submission was fine.

#### TLDR Conclusion

Song database connections got overloaded and resulted in a 500 error from an instance of song as it attempted to fetch the analysis for maestro to index.

#### Recommendations

We can look at potentially tweaking some of the configs to allow for more connections and/or a beefier postgres but we may also want to observer if this happens again what the size of the submission is to understand if this is something that scales with submission size.

**Comment by b-f-chan** [comment]
Could be something @UmmulkiramR can check out and re-confirm this issue still occurs, and find a fix from there

**Comment by caravinci** [comment]
Closing as "done".
This issue seems to have been solved now, after a combination of:
- service upgrades (both song and maestro, adding request pagination)
- several rounds of fine-tuning ingress probes. 

For additional detail about the probes (and documentation), we now ensure K8s doesn't kill the apps if they take long to respond while heavy processing is happening; and also are paying attention to long boot times, should a pod wake up slowly, which used to send the pods into cascading reboot loops.
