### ISSUE TITLE
SONG Update in Prod can NOT populate the correct values in fields `firstPublishedAt`, `publishedAt` , `analysisStateHistory`

### ISSUE THREAD

**Issue by lindaxiang** [cancogen-virus-seq/portal#148]
When update the SONG metadata, the current SONG in Cancogen has a bug to populate the correct values in the fields:
`firstPublishedAt`, `publishedAt `, `analysisStateHistory`

Example:
https://song.dev.cancogen.cancercollaboratory.org/studies/PHO-ON/analysis/087ecad7-6401-40f0-beca-d7640160f07d

- Before Update
![Screen Shot 2021-11-30 at 10 19 27 AM](https://user-images.githubusercontent.com/7522294/144077052-7aeefe89-4ec4-4f40-a6a0-1e148045dc0b.png)

- After Unpublish
![Screen Shot 2021-11-30 at 10 19 52 AM](https://user-images.githubusercontent.com/7522294/144077150-4a1a31a1-8b62-4a3a-908b-bae36d6bdcb9.png)

-After Update
![Screen Shot 2021-11-30 at 10 24 08 AM](https://user-images.githubusercontent.com/7522294/144077191-b49c86ca-30a6-4696-8558-434e4a54ffb1.png)

-After Publish
![Screen Shot 2021-11-30 at 10 33 01 AM](https://user-images.githubusercontent.com/7522294/144077462-c6daef9f-cab0-448a-a34e-34baf5aa9150.png)

Did similar tests in RDPC-QA, there is no such issue. So the simple solution is to bump the SONG version for Cancogen.

**Comment by lindaxiang** [comment]
This bug likely has been fixed in Dev. 
You can use the following content for updating step:
```
{
  "analysisType":{
    "name":"consensus_sequence"
  },
  "database_identifiers":{
    "gisaid_accession":"EPI_ISL_2822913"
  },
  "experiment":{
    "purpose_of_sequencing":"Missing",
    "purpose_of_sequencing_details":"TEST-Missing",
    "sequencing_instrument":"Illumina MiSeq",
    "sequencing_protocol":"Viral sequencing was performed following a tiling amplicon strategy using the 400 bp ARTIC v3 primer scheme. Sequencing was performed using an Illumina MiSeq sequencing instrument."
  },
  "host":{
    "host_age":null,
    "host_age_bin":"20 - 29",
    "host_age_null_reason":"Not Provided",
    "host_age_unit":"year",
    "host_disease":"COVID-19",
    "host_gender":"Female",
    "host_scientific_name":"Homo sapiens"
  },
  "pathogen_diagnostic_testing":{
    "diagnostic_pcr_ct_value":18.6,
    "diagnostic_pcr_ct_value_null_reason":null,
    "gene_name":"E gene (orf4)"
  },
  "sample_collection":{
    "anatomical_material":"Fluid",
    "anatomical_part":"Nasopharynx (NP)",
    "body_product":"Not Provided",
    "collection_device":"Swab",
    "collection_method":"Swabbing",
    "environmental_material":"Not Provided",
    "environmental_site":"Not Provided",
    "fasta_header_name":"hCoV-19/Canada/ON-PHL-21-22007/2021",
    "geo_loc_country":"Canada",
    "geo_loc_province":"Ontario",
    "isolate":"hCoV-19/Canada/ON-PHL-21-22007/2021",
    "organism":"Severe acute respiratory syndrome coronavirus 2",
    "purpose_of_sampling":"Diagnostic testing",
    "purpose_of_sampling_details":"Not Provided",
    "sample_collected_by":"Public Health Ontario (PHO)",
    "sample_collection_date":"2021-05-25",
    "sample_collection_date_null_reason":null,
    "sequence_submitted_by":"Public Health Ontario (PHO)"
  },
  "sequence_analysis":{
    "bioinformatics_protocol":"https://github.com/jts/ncov2019-artic-nf",
    "consensus_sequence_software_name":"Freebayes",
    "consensus_sequence_software_version":"1.3.2",
    "dehosting_method":"BWA v0.7.17",
    "metrics":{
      "breadth_of_coverage":"99.40%",
      "depth_of_coverage":"1820x"
    },
    "raw_sequence_data_processing_method":"https://github.com/jts/ncov2019-artic-nf",
    "reference_genome_accession":"MN908947.3"
  }
}
```

**Comment by lindaxiang** [comment]
Just did a bunch of tests in both Dev and Prod. Here are some new observations:
- The Dev actually still have the issue
- The issue ONLY happens to the first time the analysis got updated
- After update the analysis once, the updates happened later will work as normal

For first time update of the analysis in Dev and Prod:
SONG update operation will turn the above fields (firstPublishedAt, publishedAt , analysisStateHistory) into the `null` as the following example:
![Screen Shot 2021-12-17 at 1 15 36 PM](https://user-images.githubusercontent.com/7522294/148118949-2d48801a-157c-4d5a-974f-fc1af9b1346d.png)

**Comment by lindaxiang** [comment]
@joneubank  Here is an example in Dev you can use to check the above behaviours, but you can only see the bug when you update the analysis for the first time:
Example:
`song API`: https://song.dev.cancogen.cancercollaboratory.org/swagger-ui.html 
`analysisId`: f5f5c60d-c440-4392-b5c6-0dc44093925c
`studyId`: UHTC-ON
`analysis_url`: https://song.dev.cancogen.cancercollaboratory.org/studies/UHTC-ON/analysis/f5f5c60d-c440-4392-b5c6-0dc44093925c

1. Unpublish it in Dev
2. Update. (Please check the content of the above analysis for fields: `firstPublishedAt`, `publishedAt` , `analysisStateHistory`)
You can use the following content for updating step:
```
{
  "analysisType":{
    "name":"consensus_sequence"
  },
  "host":{
    "host_age":null,
    "host_gender":"Not Provided",
    "host_age_bin":"Not Applicable",
    "host_disease":"Not Provided",
    "host_age_unit":"Not Provided",
    "host_age_null_reason":"Not Provided",
    "host_scientific_name":"Homo sapiens"
  },
  "experiment":{
    "sequencing_protocol":null,
    "purpose_of_sequencing":"Not Provided",
    "sequencing_instrument":"Oxford Nanopore",
    "purpose_of_sequencing_details":"Not Provided"
  },
  "sample_collection":{
    "isolate":"hCoV-19/Canada/ON-UHTC_0472/2021",
    "organism":"Not Provided",
    "body_product":"Not Provided",
    "anatomical_part":"Not Provided",
    "geo_loc_country":"Canada",
    "geo_loc_province":"Ontario",
    "collection_device":"Not Provided",
    "collection_method":"Not Provided",
    "fasta_header_name":"hCoV-19/Canada/ON-UHTC_0472/2021",
    "environmental_site":"Not Provided",
    "anatomical_material":"Not Provided",
    "purpose_of_sampling":"Not Provided",
    "sample_collected_by":"Unity Health Toronto",
    "sequence_submitted_by":"Ontario Institute for Cancer Research (OICR)",
    "environmental_material":"Not Provided",
    "sample_collection_date":"2020-12-04",
    "purpose_of_sampling_details":"Not Provided",
    "sample_collection_date_null_reason":null
  },
  "sequence_analysis":{
    "metrics":{
      "depth_of_coverage":"2466.0x",
      "breadth_of_coverage":"Not Provided"
    },
    "dehosting_method":null,
    "bioinformatics_protocol":null,
    "reference_genome_accession":null,
    "consensus_sequence_software_name":"Not Provided",
    "consensus_sequence_software_version":null,
    "raw_sequence_data_processing_method":null
  },
  "database_identifiers":{
    "gisaid_accession":null
  },
  "pathogen_diagnostic_testing":{
    "gene_name":"Not Provided",
    "diagnostic_pcr_ct_value":null,
    "diagnostic_pcr_ct_value_null_reason":"Not Provided"
  }
}
```
3. Publish

Once you finish the first update for the analysis, you can try to update it again, but this time everything will work as normal.

**Comment by joneubank** [comment]
Loss of state history does occur as described by @lindaxiang above. This only happens on "the first update" because the underlying cause is that this happens when the analysisType changes, which in our case is happening because the analysis type is going from:
```
"analysisType": {
    "name": "consensus_sequence",
    "version": 7
  },
```
to
```
"analysisType": {
    "name": "consensus_sequence",
    "version": 12
  },
```
This happens on the first update triggered, and then it is at the latest version so it doesn't happen again afterwards.

The analysis' state change history was not being read during this step, so when the analysisType changed and the document was re-created the state history was not copied to the new entry. This is easy to fix here:

https://github.com/overture-stack/SONG/blob/develop/song-server/src/main/java/bio/overture/song/server/service/analysis/AnalysisServiceImpl.java#L173

need to change:
```
val oldAnalysis = get(analysisId, true, true, false);
```
to
```
val oldAnalysis = get(analysisId, true, true, true);
```


For the analyses in prod that have already been affected, I believe it is possible to find the original entries in the DB and associate that with the updated analysis again, if keeping that history is desired. There is no automated way to do this atm but we could do it manually.

**Comment by b-f-chan** [comment]
@sifavahora - As discussed, let's follow-up with @lindaxiang as to the nature of this issue and if it's still valid, I don't have the context/history for this one
