### ISSUE TITLE
Update metadata schema (sample collected by)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#152]
@scottcain New tags for "Sample collected by". Please update the field with the new tag **"Dynacare"** to the metadata schema. Thanks!

**Comment by scottcain** [comment]
@lindaxiang can you take a look at this one please?

**Comment by lindaxiang** [comment]
@nithujohn I wan to double check with you. Are you referring to `Dynacare` or `Dynacare (Brampton)`.
FYI, `Dynacare (Brampton)` is the one current schema is missing compared with DataHarmonizer CV.

**Comment by nithujohn** [comment]
@lindaxiang Can you please add both as the border testing is done by Dynacare in some provinces. Thanks!

**Comment by lindaxiang** [comment]
sure thing @nithujohn . thank you for confirming.

**Comment by lindaxiang** [comment]
@nithujohn @scottcain The schema has been updated. Please give a check. Thanks.

**Comment by nithujohn** [comment]
I have checked it and it has been updated! thank you so much @lindaxiang @scottcain
