### ISSUE TITLE
Allow sorting by lineage in explorer (FR)

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#154]
^^^ can it be done?

**Comment by scottcain** [comment]
To allowing sorting/searching by lineage, we have to get that data into the data store. Natalie Knox provided us with the attached csv file with IDs and lineage assignments, though it was pointed out that we may be able to get this info directly from viral.ai via API call
[dp_lineage_join.csv.gz](https://github.com/cancogen-virus-seq/portal/files/8165857/dp_lineage_join.csv.gz)
.

**Comment by b-f-chan** [comment]
@scottcain do you mean filtering by lineage in the Exploration Page?  I assume this is what you mean by `sorting/searching`?

**Comment by scottcain** [comment]
This also (I feel like obviously, but perhaps not) includes importing lineage data.

**Comment by b-f-chan** [comment]
This is part of the new work packages, we will need to analyze the new data and how it impacts our data model & mappings.  Assigning to @sifavahora for analysis and specs as required.

**Comment by joneubank** [comment]
This may repeat a bit of what was said above, but to summarize what this requires:

1. This data needs to be added to the ES index which means:
    1. Need to make sure we have this data for each sample already in our system and run a script to update the index with this data added
    2. Need to update our indexing to include this value with all future added samples, so we need to know where in the uploaded meta data this value is included

Assuming we have the required value for existing data and know where in the uploaded data this field is, then its a matter of updating our analysis schema for song and in maestro to get this data indexed. We would add this value to every analysis in song and then get maestro to re-index everything from source (song).

Before we commit to this work I would like to confirm that we have this value available for all samples today, and that we know where this value is coming from for future samples.

**Comment by lindaxiang** [comment]
> To allowing sorting/searching by lineage, we have to get that data into the data store. Natalie Knox provided us with the attached csv file with IDs and lineage assignments, though it was pointed out that we may be able to get this info directly from viral.ai via API call [dp_lineage_join.csv.gz](https://github.com/cancogen-virus-seq/portal/files/8165857/dp_lineage_join.csv.gz) .

@scottcain took a look at the above example CSV file with lineage data. Do you have an idea 
1. what is the difference between `lineage` and `lineage_current`?
2. it seems that `pangoLEARN_ver` is not usual version numbers
3. the data format(field names) are not the same fields which are defined in DataHarmonizer:
    "lineage_name",
    "lineage_analysis_software_name",
    "lineage_analysis_software_version",
    "variant_designation",
    "variant_evidence",
    "variant_evidence_details" 
Do you know whether data submitters will make adjustments? Or DataHarmonizer will make schema changes?

**Comment by joneubank** [comment]
The virus seq analysis schema configured in SONG includes all these fields listed in the DataHarmonizer. This is under a property called `lineage_analysis` which is not required for an analysis.

So far, none of the uploaded analyses include data for lineage_analysis. This means that a one time process is needed to find the lineage data for each sample and to update the analyses in SONG.

Going forward, it would be good to make this field required in the analysis_schema if they intend to include this data. We don't want to be constantly running a script to add in this data for the submitters.

**Comment by sifavahora** [comment]
The field cannot be required because it is computed at a later stage.

We need to pull the data from the Viral AI system for Lineage analysis.  The flow of data is as follows: 
Current Flow:
1. Ext - Receive Sample dat 
2. VirusSeq - Upload data on the portal (sample data without lineage information)
3. Ext (ViralAI) - Scrape the Data Release Page and ingest the latest release in their system.
4. Ext (ViralAI) - The system is automated to calculate lineage data - it takes about 48 hours(from ingestion) for the lineage data  to be available on the Viral AI System. 
Expected Addition at the end of the current flow: 
1. VirusSeq pull/fetch the lineage data from ViralAI system and update on the portal.

**Comment by leoraba** [comment]
This is now completed. Closing this issue.
