### ISSUE TITLE
Update metadata schema (purpose of sequencing)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#156]
@scottcain Hi Scott, there are new tags for "purpose of sequencing" which I have listed below for metadata schema updation. Thanks!

"Sample has epidemiological link to Variant of Concern (VoC)"
"Sample has epidemiological link to Omicron Variant"

**Comment by lindaxiang** [comment]
@nithujohn @scottcain the schema has been updated. Please give a check. Thanks.

**Comment by nithujohn** [comment]
Thank you!! @lindaxiang @scottcain
