### ISSUE TITLE
No active datasets for download in Data release page

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#157]
@scottcain Hi Scott, there is no active dataset in the data release page of the portal. Can you please have a look, might be an error? Thanks!

**Comment by nithujohn** [comment]
![image](https://user-images.githubusercontent.com/85367999/146065564-0e9f7eb8-1b97-4dd7-82a7-837728ff72f4.png)

**Comment by scottcain** [comment]
Looks fixed (thanks @henro001 ) @nithujohn please confirm and close if you agree.
