### ISSUE TITLE
Add COVID-MVP to portal (FR)

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#159]
This could be added in multiple steps:

1. adding a link to the page that is running on William's server.
2. Integrating it like CoViZu.

Site: https://covidmvp.cidgoh.ca/

What I think would be really good would be to convert the "visualize" banner option to a dropdown that has links to CoViZu and COVID-MVP

**Comment by scottcain** [comment]
This is basically the same as https://github.com/cancogen-virus-seq/portal/issues/141 but with one more sentence :-)

**Comment by anwarMZ** [comment]
@scottcain any update on this ? We have added Surveillance report feature too see [an example file for Omicron](https://github.com/cidgoh/nf-ncov-voc/blob/master/docs/Omicron_surveillance_report.pdf)
