### ISSUE TITLE
Suppress duplicate AB samples

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#161]
@scottcain Hi Scott, there are duplicate samples for AB in the portal. I have listed the IDs below. Can you please suppress the samples. Thanks!

AB_261448
AB_261449
AB_261342

**Comment by scottcain** [comment]
Hi @lindaxiang when you get back please take care of this.

**Comment by lindaxiang** [comment]
@nithujohn 
Hi Nithu, all these 3 samples have two copies in the portal
- one copy was submitted on `2021-12-08`, with `purpose_of_sequencing_details`=`Surveillance testing`
- the other copy was submitted on `2021-12-22`, with `purpose_of_sequencing_details`=`Not Provided`
which copy do you want to suppress?

**Comment by nithujohn** [comment]
@lindaxiang Hi Linda, can you please suppress the enteries submitted on 2021-12-22 for all three samples, thanks!

**Comment by lindaxiang** [comment]
@nithujohn Done!
