### ISSUE TITLE
Updation for AB data (GISAID IDs)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#163]
@scottcain Hi Scott, there are changes for GISAID accession IDs for AB data in the portal. I have attached the list, can you please make the changes in the portal. Thanks!

[dp_corrections-gisaid-ids-20220104.csv](https://github.com/cancogen-virus-seq/portal/files/7810541/dp_corrections-gisaid-ids-20220104.csv)

**Comment by scottcain** [comment]
Unfortunately, this fix is blocked by the same issue that we worked on just before the break: https://github.com/cancogen-virus-seq/portal/issues/148 so updating this will have to wait a little while.

**Comment by lindaxiang** [comment]
@nithujohn 
Here are some details I want to confirm with you before I update the data in portal. 
I did some cross check of the data you provide. 
- the first column `study_id` is actually `sample ID`?
- values of `isolate` in the table do NOT match with what currently recorded in the portal for each sample. 
- values of `OLD GISAID accession` match with the value `GISAID Accession`  currently in the portal for each sample

For example, sample `AB_82266`,  
`isolate` in the table: `hCoV-19/Canada/AB-ABPHL-16785/2020`
`isolate` in the portal: `hCoV-19/CANADA/ABPHL-16785/2020` 
`OLD GISAID accession`: `EPI_ISL_2479478`
`Gisaid Accession` in the portal: `EPI_ISL_2479478`

Can you confirm you ONLY want to update the values of `Gisaid Accession` from `OLD` to `CORRECT`? 
If that is the case, I will leave current `isolate` untouched. 

cc: @scottcain

**Comment by nithujohn** [comment]
@lindaxiang yep, I just want to update the values of **GISAID Accession** from Old to Correct. 
the first column is specimen collector ID soor for the error

**Comment by lindaxiang** [comment]
@nithujohn 
This issue has been addressed. Please have a check. Thanks. 
cc: @scottcain

**Comment by lindaxiang** [comment]
Here is the log file for updating contents. 
[AB-gisaid_accession.2022-01-13.txt](https://github.com/cancogen-virus-seq/portal/files/7871646/AB-gisaid_accession.2022-01-13.txt)

**Comment by nithujohn** [comment]
Thank you so much Linda! @lindaxiang
