### ISSUE TITLE
Retrieve a list of all analysisId whose analysis were updated but `firstPublishedAt` and `analysisStateHistory ` were not correctly populated

### ISSUE THREAD

**Issue by lindaxiang** [cancogen-virus-seq/portal#165]
There are some analysis which have been updated, but their state history may not be correctly kept due to SONG issue: https://github.com/cancogen-virus-seq/portal/issues/148

**Comment by lindaxiang** [comment]
Here are the analysisId whose analysis were updated but `firstPublishedAt` and `analysisStateHistory` were not correctly populated 
All the files have 3 columns:
- analysisId
- studyId
- submitterSampleId

[BCCDC-BC.incorrect_firstPublishedAt.log](https://github.com/cancogen-virus-seq/portal/files/7830769/BCCDC-BC.incorrect_firstPublishedAt.log)
[UHTC-ON.incorrect_firstPublishedAt.log](https://github.com/cancogen-virus-seq/portal/files/7830770/UHTC-ON.incorrect_firstPublishedAt.log)
[KHSC-ON.incorrect_firstPublishedAt.log](https://github.com/cancogen-virus-seq/portal/files/7830771/KHSC-ON.incorrect_firstPublishedAt.log)
[PHO-ON.incorrect_firstPublishedAt.log](https://github.com/cancogen-virus-seq/portal/files/7830772/PHO-ON.incorrect_firstPublishedAt.log)
[MCPL-MB.incorrect_firstPublishedAt.log](https://github.com/cancogen-virus-seq/portal/files/7830773/MCPL-MB.incorrect_firstPublishedAt.log)

**Comment by sifavahora** [comment]
@lindaxiang can this be closed?

**Comment by lindaxiang** [comment]
@sifavahora The list of all analysisId which were affected are attached here in the ticket. The ticket itself can be regarded as complete, so it can be closed. 
It's up to your and stakeholders' decision whether we need to create follow up ticket to systematically correct them.
