### ISSUE TITLE
BUG - Sample exists in SONG but do not show up in the Portal

### ISSUE THREAD

**Issue by lindaxiang** [cancogen-virus-seq/portal#172]
There are 2 samples  which have records in SONG, however they are not showing up in the portal

**study\_id**|**specimen collector sample ID**|**submission date**|**song URL**
:-----:|:-----:|:-----:|:-----:
ABPL-AB|AB\_201011|2021-11-04|https://song.virusseq-dataportal.ca/studies/ABPL-AB/analysis/32a2bc37-b985-4fb3-a2bc-37b9859fb33d
BCCDC-BC|BC\_212959|2021-11-28|https://song.virusseq-dataportal.ca/studies/BCCDC-BC/analysis/0480b364-b311-476e-80b3-64b311076ef1

This could have some relation with issue: https://github.com/cancogen-virus-seq/portal/issues/95

**Comment by akachru-github** [comment]
@jaserud , do you mind taking a quick look at this?

**Comment by jaserud** [comment]
Sure thing.

**Comment by jaserud** [comment]
I think Linda is right. Most likely they got missed during the topic outage which we fixed November 29 in https://github.com/cancogen-virus-seq/roadmap/issues/32. I've reindexed both via maestro so they should appear in protal. Also a new data-release bundles has been created with these two samples added.

**Comment by lindaxiang** [comment]
thanks @jaserud . Just checked and this has been fixed. amazing Jaser!
