### ISSUE TITLE
PHO age bin fix

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#173]
Hi @scottcain, PHO has another set of updates and corrections for age bin. Can you please do the update on the portal. Thanks! 
[PHO_VirusSeq_age_bins_to_correct_2022-01-15.xlsx](https://github.com/cancogen-virus-seq/portal/files/7877615/PHO_VirusSeq_age_bins_to_correct_2022-01-15.xlsx)

**Comment by lindaxiang** [comment]
@nithujohn @scottcain 
The `host_age_bin` has been updated on the portal for the above dataset. 
FYI:
- 20 samples with host_age_bin of `90 - 99` are changes to `90+` to conform to enum in the schema
- `host_age_null_reason` of samples with host_age_bin of `90+`  are updated to `Restricted Access` to conform to the requirement of the schema

Here is the log file:
[PHO_VirusSeq_age_bins_to_correct_2022-01-15.log](https://github.com/cancogen-virus-seq/portal/files/7892131/PHO_VirusSeq_age_bins_to_correct_2022-01-15.log)

**Comment by nithujohn** [comment]
@lindaxiang Hi Linda, thank you so much!
