### ISSUE TITLE
Suppress AB samples

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#174]
Hi @scottcain, I have listed AB samples below to be suppressed from the portal. Thanks!

AB_82269
AB_82313
AB_82358
AB_82361
AB_82385
AB_82395
AB_82401
AB_82404
AB_82467
AB_82489
AB_82494
AB_82510
AB_82519
AB_82584
AB_82610
AB_82655
AB_82685
AB_82717
AB_82748

**Comment by lindaxiang** [comment]
@nithujohn @scottcain 
The above samples have been suppressed from the portal. Please have a check. thanks.
Here is the log:
[ABPL-AB.analysisId_sampleId.txt](https://github.com/cancogen-virus-seq/portal/files/7891397/ABPL-AB.analysisId_sampleId.txt)

**Comment by nithujohn** [comment]
@lindaxiang Thanks Linda!
