### ISSUE TITLE
AB remove records

### ISSUE THREAD

**Issue by nknox** [cancogen-virus-seq/portal#178]
Hi Scott,
Our AB partners have requested the removal of the following records.

Thanks,
Natalie

[data.to.remove-20220125.txt](https://github.com/cancogen-virus-seq/portal/files/7934926/data.to.remove-20220125.txt)

**Comment by lindaxiang** [comment]
@nknox @scottcain 
The samples in the above list have been suppressed from the portal. 
Here is the log:
[ABPL-AB.suppression.log](https://github.com/cancogen-virus-seq/portal/files/7937438/ABPL-AB.suppression.log)
