### ISSUE TITLE
metadata selection dropdown ignored for downloads

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#179]
When downloading data from the explorer, even though "Submission Date" is selected in the "Columns" drop down (and is, I believe, selected by default), that column is not included in the generated metadata.  This appears to be the case whether the whole data set or a slice of the data is downloaded.  Here are the column headers for the metadata file when I haven't changed the defaults:
```
study_id       
specimen collector sample ID    
sample collected by     
sequence submitted by   
sample collection date  
sample collection date null reason      
geo_loc_name (country)  
geo_loc_name (state/province/territory) 
organism        
isolate fasta header name       
purpose of sampling     
purpose of sampling details     
anatomical material     
anatomical part body product   
 environmental material  
environmental site     
collection device       
collection method       
host (scientific name)  
host disease    
host age        
host age null reason    
host age unit   
host age bin    
host gender     
purpose of sequencing   
purpose of sequencing details   
sequencing instrument   
sequencing protocol     
raw sequence data processing method     
dehosting method        
consensus sequence software name       
consensus sequence software version     
breadth of coverage value       
depth of coverage value 
reference genome accession      
bioinformatics protocol gene name       
diagnostic pcr Ct value 
diagnostic pcr Ct value null reason     
GISAID accession
```
Note that in addition to submission date not being present, several things are present despite not being selected in the columns drop down, like organism, dehosting method, and depth and breadth of coverage. It seems like the UI widget is being completely ignored and some other default is being used.

Also note that the table being displayed in the page does respect the column drop down, as the submission date is displayed by default, and toggling the checkbox in the column drop down causes it to go and appear as expected.

**Comment by scottcain** [comment]
Guessing this is an Arranger issue, and so am initially assigning to @joneubank

**Comment by scottcain** [comment]
Summarizing the conversation with @jaserud : 

Plan is to modify the download template to include submission date and otherwise mirror the submission upload (which is what it does now). This will have a knock-on effect of including submission date in the "Downloads" page, since they use the same template, and this was already requested in https://github.com/cancogen-virus-seq/portal/issues/128.

Additionally, we will add a tool tip to the "columns" button that indicates that modifying the columns affects ONLY the display with the download being unaffected. The text of the tool tip would be something like "NOTE: changes for display only; no effect on downloads"

These changes should satisfy the user requirements.

**Comment by b-f-chan** [comment]
Changes implemented, deployed & tested successfully in production.  @scottcain please close ticket if satisfactory, thanks!
