### ISSUE TITLE
Policy Addition

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#18]
- [x] Policy design uses consistent styles with the login intermediate page.

- [x] Add link to this page from the footer

Zeplin: https://zpl.io/ad39WnL

**Comment by caravinci** [comment]
@rosibaj Can I bug you for the urls for the links?

**Comment by rosibaj** [comment]
`https://www.go-fair.org/fair-principles` is correct; linkout to `info@virusseq-dataportal.ca` for the contact email.

**Comment by caravinci** [comment]
Design implemented, and pushed for dev for visual feedback.
Awaiting final content changes, if any.

**Comment by rosibaj** [comment]
- [ ] Space here
![image](https://user-images.githubusercontent.com/15824252/116090202-9e2a0000-a671-11eb-9f5b-d277f703810c.png)
- [ ] Some small text updates: 
First paragraph: 
```
The goal of the CanCOGeN VirusSeq project is to sequence up to 150,000 viral samples from Canadians testing positive for COVID-19. The VirusSeq Data Portal is an open-source and open-access data portal for all Canadian SARS-CoV-2 sequences and associated non-personal contextual data. It harmonizes, validates and automates submission to international databases.
```

later fix lab --> laboratories 
```
among Canadian public health laboratories, researchers and other groups interested in accessing the data for research and innovation purposes.
``

```
Microbiology Laboratory and provincial public health laboratories across the country.
```

**Comment by rosibaj** [comment]
- [ ] Space here
![image](https://user-images.githubusercontent.com/15824252/116090202-9e2a0000-a671-11eb-9f5b-d277f703810c.png)

**Comment by rosibaj** [comment]
this looks good closing as future text update is in another ticket.
