### ISSUE TITLE
API connectivity issue

### ISSUE THREAD

**Issue by nknox** [cancogen-virus-seq/portal#180]
Hi there,
I'm no longer able to submit sequences through the API since the downtime. Here's the message I receive:

`API Server problem (check API URL?): ConnectionError(MaxRetryError("HTTPSConnectionPool(host='muse.dev.cancogen.cancercollaboratory.org', port=443): Max retries exceeded with url: /submissions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efc6092b220>: Failed to establish a new connection: [Errno 110] Connection timed out'))"))`

**Comment by nknox** [comment]
Issue seems to be resolved now.

**Comment by scottcain** [comment]
Glad to hear it; I’m going to keep this open and “ask around” to see if it’s anything that should be addressed. I’ll start with @jaserud

**Comment by jaserud** [comment]
I noticed the URL is to our dev cluster "muse.**dev**.cancogen.cancercollaboratory.org". I'm not sure if you have access to that URL as it is not publicly available, but we were having some intermittent DEV cluster issues yesterday. Some services were in and out through out the day on our dev cluster.

**Comment by scottcain** [comment]
Makes sense, closing.
