### ISSUE TITLE
PHO duplicates in the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#181]
@scottcain Hi Scott, there are duplicates in the portal. Can you please have a look and also let me know whether they are same samples or different samples. Thanks!

**Comment by nithujohn** [comment]
![image](https://user-images.githubusercontent.com/85367999/152360141-d76990af-2a6d-44f6-8790-320d7626b160.png)

**Comment by scottcain** [comment]
@lindaxiang can you take a look at this please?

**Comment by lindaxiang** [comment]
@scottcain @nithujohn The duplicated submitted samples have been suppressed from the portal. Please have a check. 
Attached is the sample and analysis which have been suppressed.
[PHO-ON.duplicated-analysis.txt](https://github.com/cancogen-virus-seq/portal/files/7998646/PHO-ON.duplicated-analysis.txt)

**Comment by scottcain** [comment]
@nithujohn please close this issue after you confirm! Thanks

**Comment by nithujohn** [comment]
Hi @lindaxiang were they different sample with same IDs?
