### ISSUE TITLE
Elastic search and the exact counts on the main page

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#182]
Hi @joneubank (guessing you're a good person to start with on this), during a cancogen call last week, we discussed the coming 200,000 sequence limit for ES buckets to give live updates on the main page for files and genomes. Lincoln's suggestion was that we replace the "live calculated" number on the main page with a cached value so that there isn't a delay in the display. Since the values are updated fairly infrequently (at most a few times a day), and since the curator doing the load would be the person who triggers the update in the cache by reloading the main page, the pain of recalculating the  cache would be only felt by that user.

We also discussed the same delay in the count calculation on the explore page; the overwhelming consensus of the people on the call was to keep the exact count even as the delay gets bigger (those scientists and their exact numbers). They indicated they'd be willing to revisit this decision should the delay get significantly longer, but for now they want it as is.

So my suggested plan for the site is this:
1. ~~Increase the number of sequences from 200,000 to something like 300,000 so that we don't hit the limit (we are close to 180,000 now)~~ Done!
2. With the breathing room given us by 1, implement a simple cache for the main page.
3. Do nothing with the explore page until somebody complains, at which point we can switch over to "About x sequences"

**Comment by scottcain** [comment]
Marked as critical since the 200,000 limit is approaching quickly.

**Comment by joneubank** [comment]
Caching on the home page is a good idea, we wouldn't want a delay on that.

For the count displayed in the explore... increasing the limit entails risk of both longer loads and eventually errors on requests from running out of memory on ES, but when that happens I can't predict. If everyone is comfortable with this then we can increase it again until we see performance issues. Adding caching to these queries would also be good, as the most common one (no filters) would be the largest result set. With this caching, we would need to have a system for busting this cache as new sequences are added to the site.

**Comment by scottcain** [comment]
Right--when a curator adds more sequence, there will need to be a way to mark the cache as stale so that the next load of the main page would trigger recalculating it, and it is reasonable to have the curators do that as part of their load process (either by convention or by having the load page redirect to the main page?)

**Comment by joneubank** [comment]
Another point to mention, is we can use a different approach called Composite Aggregations to calculate the total count... it might be a bit slower but is meant to be more memory efficient for ES. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html

A Composite Aggregation query will provide a paginated response that lets us page through all the unique IDs and count them, then return that number. Unfortunately the query doesn't know the total number of values, so we'll need to go through every page and count them. If we start having memory issues with the current approach, this is an alternative.

**Comment by scottcain** [comment]
Lincoln indicated last week that this issue is critical; while the first step was completed last week (thanks @jaserud ) and the bucket limit was increased, we need to implement a "simple" cache for the numbers on the main page (which can be reused for the initial page load of the explore page too, right?). Who can be tasked with this change?

**Comment by scottcain** [comment]
#209 and #210 have been implemented and are in production, closing
