### ISSUE TITLE
Allow multiple tags for purpose of sequencing

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#188]
@scottcain As we discuss in the meeting for change of metadata schema to allow multiple tags in the Purpose of Sequencing column. Thanks!

**Comment by scottcain** [comment]
This is a specific example of a broader question: in the Purpose of Sequencing field, some orgs have started putting more than one value here. We need to explore how to represent that in the data store and identify what other fields may require this (a member of the steering committee also mentioned that there are fields that they feel may need to allow multiple values).

**Comment by scottcain** [comment]
Hi @nithujohn can you post an example input that has multiple values for Purpose of Sequencing, so we can figure out how to deal with it?  Thanks!

**Comment by nithujohn** [comment]
Hi @scottcain one instance is Targeted surveillance (non-random sampling);Travel-associated surveillance, another example I have seen is Screening for Variants of Concern (VoC);Travel-associated surveillance and sometimes instead of Travel-associated surveillance it would be Cluster/Outbreak investigation.

**Comment by scottcain** [comment]
Do you have an input file you could add to the issue so we can see how it's being represented?

**Comment by nithujohn** [comment]
Hi @scottcain Please refer data harmonizer schema which already allows multiple tags https://github.com/cidgoh/DataHarmonizer/blob/master/template/canada_covid19/data.js

**Comment by lindaxiang** [comment]
@scottcain If it requests to convert `Purpose of sequencing` from `string` type to `array of strings`,  I can make changes to the schema. 
We will also need changes to ES mapping, Maestro and UI? @joneubank should have better idea.

**Comment by nithujohn** [comment]
Hi @scottcain has this been addressed as I will be getting samples with multiple tags for dp uploads. Thanks!

**Comment by b-f-chan** [comment]
@nithujohn - This has not been addressed yet, we will schedule it into an upcoming sprint.  Just to confirm, the JSON you sent us is the latest and most up-to-date with the controlled values for `purpose of sequencing`, correct?  Thanks!

**Comment by b-f-chan** [comment]
@nithujohn @scottcain - Does this change need to be applied only moving forward / prospectively for new samples?  Or do we need to retrospectively go back in time and correct all existing samples to have array values?  If the latter, then a migration is required and this becomes more effort/complex.

**Comment by b-f-chan** [comment]
Sorry I spoke too soon @nithujohn @scottcain - This may not be as simple as first thought.  Especially if we need to show multiple values in a row cell in the UI.  This requires a change to our Arranger component which has impacts to the way we design and style our UI.  I would want more time to investigate this, especially because we are in the middle of a re-write of our Arranger component.  I need to understand the criticality of this, as you may not get this fix in just a few days or even few weeks time.  Can we include this as part of the new work packages being ironed out now?

**Comment by nithujohn** [comment]
@b-f-chan This change needsa to be applied only for new samples as this was a recent change the data providers has request.

**Comment by nithujohn** [comment]
[test.txt](https://github.com/cancogen-virus-seq/portal/files/8375000/test.txt)
Example for multiple tag for purpose of sequencing

**Comment by nithujohn** [comment]
@scottcain Got a new request to allow multiple tag for the column "anatomical part" to include multiple samples collected at the sites. Thanks!

**Comment by b-f-chan** [comment]
@sifavahora - We will need to find out the priority of this from @scottcain first and also whether we want to change Arranger at this point for it, so will need input from @caravinci and @joneubank

**Comment by sifavahora** [comment]
Had a quick discussion with @caravinci. It is medium effort and doable. We can discuss in detail once we have the priority determined.

**Comment by sifavahora** [comment]
@joneubank advised the following steps: 

1. Muse Processing - to accept and parse multiple values (in the sample file sent by Nithu, the delimiter is a semicolon)
2.Updating Schema in Song - Identify the syntax for changing value type to array of enum from enum 
3.Updating Muse Configs (update the new song analysis value to Muse Configs)
4.Update Arranger Configs 
5.Implement custom cell in Arranger.

**Comment by nithujohn** [comment]
Hi @sifavahora I can confirm this and ; will be used as separator for multi tags.
