### ISSUE TITLE
Profile Page Updates

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#19]
- copy JWT not API Key
- when you copy, refresh he JWT 

**See Zeplin for changes**: https://zpl.io/addyQoR
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/a370b049-6724-4e7c-b998-93bb753d0595)

- [x] UI bug - the user dropdown is outside of the browser width, causing a horizontal scrollbar to appear on the page.
![image](https://user-images.githubusercontent.com/18424138/115595547-0d37db00-a2a5-11eb-906a-4eee4f3b546c.png)

**Comment by caravinci** [comment]
As most of these changes are being effected in #25, I think all that remains from this ticket is showing the studies a user has access to.

**Comment by rosibaj** [comment]
@caravinci is there some blocker to showing the scopes the user has acces to?

**Comment by caravinci** [comment]
None whatsoever, just showing some progress so you could give feedback in a piecemeal basis.
The scopes are list now as per specification, and visible in Dev.

**Comment by rosibaj** [comment]
looks good @caravinci !
