### ISSUE TITLE
AB sample to be removed

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#191]
Hi @scottcain,

Could you please remove this AB sample- AB_296473 from the portal? This sample is a potential mixed infection sample.

Thanks,
Chanchal

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain This has been addressed and following is the log:
```
4aa9ece5-6e4c-4ffc-a9ec-e56e4ccffc15	AB_296473	hCoV-19/Canada/AB-ABPHL-48285/2021
```
