### ISSUE TITLE
PHO remove sample

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#192]
Hi there,
Our PHO partners have requested the removal of this sample- ON_337655 from the portal.

Thanks,
Chanchal

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain The above sample has been removed from the portal.
```
9c0b1348-047c-4e4c-8b13-48047cce4ccf	ON_337655	hCoV-19/Canada/ON-PHL-22-04025/2021
```
