### ISSUE TITLE
Ability to search in explorer for a specific sequence id went away

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#196]
will add more info soon

**Comment by b-f-chan** [comment]
@scottcain - Do you mean that there used to be a Sequence ID search box in the Filters on the Explore page?  I personally have never seen that, but that can be implemented if required.  Again, need to know the priority.

**Comment by caravinci** [comment]
TBH, I don't recall that specific facet filter being available, but I'm confident we're able to add it if needed.

**Comment by scottcain** [comment]
Yeah, it was somewhat vague when it was discussed during the call (as you can tell from my oh-so-helpful initial message), but perhaps @nithujohn could add some more details.

**Comment by nithujohn** [comment]
The filter was available initially but I don't remember when it actually disappeared. I have attached screen shot please have a look
![pic1](https://user-images.githubusercontent.com/85367999/172195467-6c4ae83b-3aad-4a7d-94f8-6ed60293f7d1.png)

**Comment by sifavahora** [comment]
thanks @nithujohn for confirming! @caravinci can you please take a look.

**Comment by sifavahora** [comment]
@scottcain The team investigated and determined that the reason to remove this was for performance issues as it shows  ~50327 entries and bad ux, we can replace the field as an autocomplete search field, not a checkbox list as a later enhancement.  We need to determine the priority for this.

**Comment by justincorrigible** [comment]
A new component has been added along with Arranger3. This ticket can be closed upon validation now, @scottcain

**Comment by leoraba** [comment]
Quicksearch component has been enabled in Portal to find analysis by **Specimen Collector Sample ID.**

![image](https://github.com/cancogen-virus-seq/portal/assets/9260184/d69a7864-59ba-4cfb-bc1c-8f7ee28a06fd)
