### ISSUE TITLE
Upload status of the samples

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#198]
Hi @scottcain, I have attached few samples which got stuck during the upload. I would like to know the status of these samples, are they uploaded in the portal or needs to re- upload. Thanks!
[Errors.xlsx](https://github.com/cancogen-virus-seq/portal/files/8137182/Errors.xlsx)

**Comment by scottcain** [comment]
@jaserud Can you please take a look at this list of samples? I suspect the answer is to just upload them again, but I'd like to have your confirmation on that.

**Comment by jaserud** [comment]
These upload rows exists in the portal:
```
BCCDC-BC	BC_307019	ac6f0b01-2a3c-4f01-af0b-012a3ccf0159	PROCESSING
BCCDC-BC	BC_307015	c57c214a-ec9c-4271-bc21-4aec9ca27144	PROCESSING
BCCDC-BC	BC_307016	a0c591ff-f93b-4f3a-8591-fff93bbf3a20	PROCESSING
BCCDC-BC	BC_307017	c9760f74-71f7-4afc-b60f-7471f7aafcac	PROCESSING
```
The rest need to be resubmitted.

**Comment by nithujohn** [comment]
Thanks! @jaserud @scottcain
