### ISSUE TITLE
Submission Details Page

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#20]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/a9e3514f-2122-4250-ab92-02c2f308fd4c)

**Comment by caravinci** [comment]
Deployed new version. Still pending: sorting and pagination. Ignored "retry" functionalities as instructed.
Not a 100% sure I've handled the error messaging according to spec... please let me know if I should change it.

**Comment by rosibaj** [comment]
A couple styling notes:

- [ ] 
![image](https://user-images.githubusercontent.com/15824252/115414950-80b5eb80-a1c4-11eb-91db-42dda1a89135.png)

**Comment by rosibaj** [comment]
Tested April 20, 2021 afternoon
- table appears as expected, with the expected daa
- status update in the table
- spacing has been fixed. 
lgtm thank you @caravinci
