### ISSUE TITLE
Sample collection dates to be updated-BC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#200]
Hi there,

Could you please update the sample collection dates for the list of BC samples attached?

Thanks,
Chanchal
[BC_sample_Collection_Dates_to_be_Updated_DP.csv](https://github.com/cancogen-virus-seq/portal/files/8143130/BC_sample_Collection_Dates_to_be_Updated_DP.csv)

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain This has been addressed. Please have a check. 
Attached please find the log file. 
[BC_sample_Collection_Dates_to_be_Updated_DP.log](https://github.com/cancogen-virus-seq/portal/files/8165787/BC_sample_Collection_Dates_to_be_Updated_DP.log)
