### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#202]
Hi @scottcain, After resuming the uploads I started getting internal server error. Also have a quick question is there a number limit for per province as I don't see the limit increasing for BC (100K) on the portal ?

BC_9672 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
 BC_9670 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9671 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9667 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9665 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9664 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9662 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9661 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9673 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_36858 | 0f218af1-6892-4ed2-a18a-f16892aed291 | ERROR:Internal server error!
BC_37709 | 55476bf0-590f-4f3e-876b-f0590f2f3ea8 | ERROR:Internal server error!
BC_37709 | 55476bf0-590f-4f3e-876b-f0590f2f3ea8 | ERROR:Internal server error!
BC_37703 | f2650d5a-a932-42bd-a50d-5aa93272bdfd | ERROR:Internal server error!
BC_37948 | 44ca870f-8259-40f5-8a87-0f825900f5ae | ERROR:Internal server error!
BC_9711 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9710 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9707 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9708 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
 BC_9704 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error
BC_9705 |   | ERROR:500 INTERNAL_SERVER_ERROR - SongScore - Internal Server Error

**Comment by scottcain** [comment]
@nithujohn There are no messages in our server logs, so it could be just that SONG was overloaded at the time and throwing these errors. Can you try again with those sequences?

**Comment by nithujohn** [comment]
@scottcain yea it worked this time. Thanks!
