### ISSUE TITLE
Update metadata schema (Purpose of sequencing)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#205]
Hi @scottcain there is a new tag for the field "Purpose of sequencing" I have included below. Can you please update the schema? Thanks!

"Retrospective sequencing"

**Comment by scottcain** [comment]
Hi @lindaxiang Can you please add this to your list?

**Comment by lindaxiang** [comment]
@nithujohn @scottcain  this has been updated. Please give a try. Thanks.

**Comment by nithujohn** [comment]
@lindaxiang @scottcain Thank you so much!
