### ISSUE TITLE
Improve download dialog boxes

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#208]
Currently, the explorer download dialog box says "Download complete" when the creation of the download tarball is complete (but before the actual download to the users computer is necessarily complete):

<img width="1198" alt="Screen Shot 2022-03-02 at 9 25 32 AM" src="https://user-images.githubusercontent.com/274751/156433621-63875dd8-5f00-4e8b-a3cf-71aa4e6f7f1f.png">

@b-f-chan suggested that the dialog title text be changed like this:

`Preparing download…`
(portal prepping the tar)

`Download initiated`
(tar is ready and download via browser kicked off)

which would be less confusing to users.

**Comment by b-f-chan** [comment]
Tested successfully on DEV:

- Correct message displays when prepping tar
- Correct message displays once tar ready and download triggered via browser

Ready for deploy to prod

**Comment by scottcain** [comment]
This was deployed some time ago; closing ...
