### ISSUE TITLE
Cache Summary Counts on Homepage

### ISSUE THREAD

**Issue by b-f-chan** [cancogen-virus-seq/portal#209]
Splitting this out as sub-task of #182 

To improve loading time and responsiveness to the user when displaying the summary counts (# Files, # Viral Genomes, #S tudies, # GB) on the homepage (https://virusseq-dataportal.ca/), we will implement server-side caching of the counts.  The portal will retrieve & display values served up from the cache.

The cache should have invalidation logic to update it with the latest values as necessary.  Each time a new release is published (i.e. new count values are published), the cache should be invalidated.

This is done outside of Arranger, so should be fairly straightforward (i.e. no modifications of or investigation into Arranger behaviour itself).

**Comment by b-f-chan** [comment]
Tested on Dev - Solution implemented, but difficult to perceive speed increase/benefits due to small amount of data on Dev.  However, it will be difficult for us to load the same amount of data as prod into Dev and may not be worth the time.  We can test this more thoroughly in Prod and do a quick rollback in case of any major issues.

**Comment by scottcain** [comment]
Works in production; closing
