### ISSUE TITLE
Implement Cardinality Aggregation on Exploration Page

### ISSUE THREAD

**Issue by b-f-chan** [cancogen-virus-seq/portal#210]
Splitting this out as sub-task of #182, to distinguish work required on the Homepage vs the Exploration page.

Calculating the summary counts on the Exploration page using the current logic will eventually hit a resource (memory) in Elasticsearch and cause an error on the page, as the # of files and viral genomes increases.  We cannot continuously increase the ES search.max_buckets limit, as it is unclear when the ceiling will be hit.

We will implement an alternative, more resource-efficient method, as agreed with the Cancogen Steerco.  That is, we will use ES Cardinality Aggregation (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html), which calculates an approximate count of distinct values.  This aggregation type is only precise up to a configurable threshold (max 40,000 in ES).

Hence, the summary counts will only be accurate up to a max of 40,000.  We should set the ES precision threshold to the max (40,000), but we are clearly beyond that number.  Anything beyond 40,000 the counts will be fuzzy.  ES has a graph depicting their studies on the error variation beyond the threshold: https://www.elastic.co/guide/en/elasticsearch/reference/current/images/cardinality_error.png

**Summary of Work:**

- **NOTE:** As suggested by @joneubank, first investigate Arranger functionality, as this may or may not already be supported there (unclear, need to investigate)
- Replace current summary count calculation with ES cardinality aggregation
- Set precision threshold to max value (40,000)
- UI logic for display/labeling will change slightly:
    - If count <= precision threshold, display number as is, for example, `39456`
    - Else if count > precision threshold, display number with approximation, for example `~246269` (like we do in ARGO clinical timeline), or `Approx. 246269`(@kcullion what is our preference?  I assume `~` because it's shorter!)

**Comment by kcullion** [comment]
@b-f-chan I prefer `~246,269` (if you can put the commas in there, great)...but yeah, I think ~ does the trick

**Comment by b-f-chan** [comment]
Thanks @kcullion - Hehe I think the commas are definitely doable :) - And we should!  I'll ask @jaserud to do this on the homepage as well

**Comment by jaserud** [comment]
Slight hickup, Cardinality Aggregations are actually never guaranteed to be exact. 
From es docs: "counts are expected to be close to accurate".

The new flow is:
- config in portal for QUERY_MAX_BUCKET_COUNTS, which will be a integer less than the ES_CLUSTER_MAX_BUCKETS (e.g. ES_CLUSTER_MAX_BUCKETS=65,000 : MAX_BUCKET_COUNTS=50,000).
- the default query will be for cardinality and logic will be
   if CARDINALITY < QUERY_MAX_BUCKET_COUNTS -> query again but for bucket_count
   else -> show CARDINALITY as approximation

**Comment by b-f-chan** [comment]
Tested new flow as described by @jaserud above successfully on Dev:

- When CARDINALITY < QUERY_MAX_BUCKET_COUNTS, exact count shown and number displayed without `~`
- When CARDINALITY >= QUERY_MAX_BUCKET_COUNTS, approximation shown and number displayed with `~`

However, difficult to test/assess speed increase/benefits since there is a much smaller amount of data in Dev vs Prod.  It will be difficult for us to get such a large amount of data into Dev and may not be worth the investment.  We can test the speed in Prod and do a quick rollback in case of any major issues.

**Comment by scottcain** [comment]
Works in production, closing
