### ISSUE TITLE
PHO duplicate IDs

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#211]
Hi @scottcain There are duplicates in the recent upload of PHO datasets. Please have a look and suppress the duplicates. Thanks!

**Comment by nithujohn** [comment]
@scottcain I downloaded the datasets and found that it's the same specimen collector ID but different sample. When you suppress the duplicate IDs please do let me know so I can ask NML to re-assign new IDs for those samples

**Comment by lindaxiang** [comment]
@nithujohn there are 2090 duplicates which have been removed from the portal. 

Here is the metadata for suppressed samples which were all submitted on Mar.07
[PHO-ON.remove-2090.2022-03-09.metadata.txt](https://github.com/cancogen-virus-seq/portal/files/8219025/PHO-ON.remove-2090.2022-03-09.metadata.txt)

**Comment by nithujohn** [comment]
Thanks Linda! @lindaxiang
