### ISSUE TITLE
Metadata updates- NS

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#212]
Hi there,

Could you please update the Purpose of sequencing, gene name and diagnostic pcr ctv values for the list of NS samples attached? We received these updates from the partners.
[NS_DP_Updates_20220308.csv](https://github.com/cancogen-virus-seq/portal/files/8208208/NS_DP_Updates_20220308.csv)

Thanks,
Chanchal

**Comment by lindaxiang** [comment]
The samples have been updated on the portal. Here attached the log file.
[NSHA-NS.DP_update.log](https://github.com/cancogen-virus-seq/portal/files/8255544/NSHA-NS.DP_update.log)
