### ISSUE TITLE
Samples to remove- PHO

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#216]
Hi there,

Could you please remove these 2 PHO samples from the portal--> ON_335318, ON_337891.

Thanks,
Chanchal
@scottcain

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain The samples have been removed.
[PHO-ON.remove.2_samples.txt](https://github.com/cancogen-virus-seq/portal/files/8255578/PHO-ON.remove.2_samples.txt)
