### ISSUE TITLE
Metadata updates for PHO samples

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#217]
Hi there @scottcain ,

Could you please make the metadata updates highlighted in the xlsx files for some PHO samples in VirusSeq? Our partners have provided these updates and would like them to be updated in VirusSeq.

Thanks,
Chanchal
[DP_updates_PHO_20220311.xlsx](https://github.com/cancogen-virus-seq/portal/files/8235641/DP_updates_PHO_20220311.xlsx)

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain The samples have been update on the portal.
[PHO-ON.DP_update.log](https://github.com/cancogen-virus-seq/portal/files/8255586/PHO-ON.DP_update.log)

**Comment by ChanchalYa** [comment]
Thanks so much @lindaxiang.
