### ISSUE TITLE
Metadata updates- NB

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#218]
Hi there @scottcain ,

Could you please apply the highlighted metadata updates in the attached excel sheets (NB_01,NB_02,NB_03) to the NB data in the portal?

Thank you,
Chanchal
[Updates_for_DataPortal_20220315.xlsx](https://github.com/cancogen-virus-seq/portal/files/8256402/Updates_for_DataPortal_20220315.xlsx)

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain The NB metadata have been updated on the portal. Here is the log file:
[VHN-NB.update.log](https://github.com/cancogen-virus-seq/portal/files/8325405/VHN-NB.update.log)

**Comment by ChanchalYa** [comment]
Thanks very much @lindaxiang @scottcain !
