### ISSUE TITLE
Data standard blurb

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#221]
@scottcain Please find the data standard blurb to be included under Policies section

"As data needs change over time, the data standard implemented by the Data Portal evolves (additional fields and terms may be added, requirements may be updated, etc). This may alter the database schema as well as the types of information provided by data stewards. For more information, please contact Dr. Emma Griffiths at ega12@sfu.ca "

**Comment by nithujohn** [comment]
@b-f-chan Hi Brandon,  yep I mean somewhere at this link but I would like to suggest to put the section after Data users guidelines. Thanks!

**Comment by b-f-chan** [comment]
Thanks @nithujohn, will add as new sub-section

**Comment by b-f-chan** [comment]
I've made the update @nithujohn, once I incorporate other verbiage changes from other stakeholders, we'll send you a screenshot from a test environment to confirm before we deploy to prod

**Comment by scottcain** [comment]
Implemented in production: https://virusseq-dataportal.ca/policies
