### ISSUE TITLE
Make Verbiage Edits to Portal

### ISSUE THREAD

**Issue by b-f-chan** [cancogen-virus-seq/portal#223]
Several verbiage edits need to be made to the Portal

(1) At bottom of homepage (https://virusseq-dataportal.ca/), box about COVID Cloud should be updated to:

"Genome Canada has partnered with DNAstack to share [VirusSeq data on Viral AI](https://viral.ai/collections/virusseq/overview), a federated network for genomic variant surveillance and infectious disease research. Viral AI was designed to deliver equitable access to software infrastructure, accelerate international data sharing, and empower scientists and public health officials with globally representative datasets they need to mitigate current and future infectious disease outbreaks."

![image](https://user-images.githubusercontent.com/40768946/160622267-8b0da350-d78e-4fc9-8e43-7c53985ebed9.png)

(2) On the About the Team page (https://virusseq-dataportal.ca/team), in the `Cloud-Based Platform` section, update text to:

"Cloud Based Platform: 
Genome Canada has partnered with DNAstack to share [VirusSeq data on Viral AI](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fviral.ai%2Fcollections%2Fvirusseq%2Foverview&data=04%7C01%7CBrandon.Chan%40oicr.on.ca%7Cd510406d67e5493566e708da10c3b6c5%7C9df949f8a6eb419d9caa1f8c83db674f%7C0%7C0%7C637840730062897000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FUNSWTbUFBHFLq6v5LxkM84v%2Ff2vEy8ndeg2tsxPR6U%3D&reserved=0), a federated network for genomic variant surveillance and infectious disease research. Viral AI helps researchers find, visualize, and analyze genomics, epidemiological and other datasets related to COVID-19.  Viral AI was designed to deliver equitable access to software infrastructure, accelerate international data sharing, and empower scientists and public health officials with globally representative datasets they need to mitigate current and future infectious disease outbreaks. The Viral AI network shares Canadian and international data over APIs developed by the [Global Alliance for Genomics & Health](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ga4gh.org%2F&data=04%7C01%7CBrandon.Chan%40oicr.on.ca%7Cd510406d67e5493566e708da10c3b6c5%7C9df949f8a6eb419d9caa1f8c83db674f%7C0%7C0%7C637840730062897000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R43DY55EctWIbeK%2FBwQUGK9bSbgNj%2FN24WLks%2FlJu4o%3D&reserved=0). Viral AI was developed in partnership with a [consortium of Canadian experts](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.digitalsupercluster.ca%2Fcovid-19-program-page%2Fbeacon-realtime-global-data-sharing-network%2F&data=04%7C01%7CBrandon.Chan%40oicr.on.ca%7Cd510406d67e5493566e708da10c3b6c5%7C9df949f8a6eb419d9caa1f8c83db674f%7C0%7C0%7C637840730062897000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vzca4sYgSYD7IqBNbL0tXqqyHy%2Fb%2F00pvGLNPbX1dwU%3D&reserved=0) in infectious disease, ethics, policy, cloud computing, and artificial intelligence, and supported by Canada’s [Digital Technology Supercluster.](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.digitalsupercluster.ca%2F&data=04%7C01%7CBrandon.Chan%40oicr.on.ca%7Cd510406d67e5493566e708da10c3b6c5%7C9df949f8a6eb419d9caa1f8c83db674f%7C0%7C0%7C637840730062897000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QUyI1%2FSyH5VjUnvDQCU4QFuMus79bPYZmzjhwnNUXXc%3D&reserved=0)"

![image](https://user-images.githubusercontent.com/40768946/160623044-9d5a8c8c-191b-4593-b69c-e923879ee064.png)

(3) **To confirm**: On the About the Team page (https://virusseq-dataportal.ca/team), in the `Technology Partners` and `VirusSeq Data Portal` sections, Christina Yung is still mentioned although she is no longer at OICR.  Confirm if this needs to be changed/removed, and if so, make the edits.

![image](https://user-images.githubusercontent.com/40768946/160623145-45e53178-d23b-4c3a-8649-63427b933262.png)

**Comment by b-f-chan** [comment]
COVID Cloud logo also needs replacing, see attached:

![viral ai](https://user-images.githubusercontent.com/40768946/160841163-6f8535aa-6347-49ab-9300-9dae65b17290.png)

**Comment by scottcain** [comment]
Got a thumbs up from Christine, so closing this
