### ISSUE TITLE
Improve visualisation of totals

### ISSUE THREAD

**Issue by caravinci** [cancogen-virus-seq/portal#225]
The way we display numbers in the "totals" panel requires avoidable cognitive effort to assert their order of magnitude.
In Arranger, the counts are displayed with the appropriate punctuation. This ticket is to replicate that functionality here.

![image](https://user-images.githubusercontent.com/2107110/160680517-a286a5c7-c0e4-4466-ba43-b0d8b80a113c.png)

**Comment by caravinci** [comment]
Tagging @b-f-chan for visibility.

**Comment by b-f-chan** [comment]
This appears in two specific places that need changing:

- Stats bar on homepage
- Stats bar on exploration page

Make consistent with aggregations in facet panel by adding comma when magnitude enters each additional power of 10^3
