### ISSUE TITLE
Incorrect Gender

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#237]
@scottcain Hi Scott, I have included a sample which has gender error in the portal and included the correct gender. Thanks!

Lab Name  GISAID ID  Current gender in portal Correct gender

Manitoba_Cadham_Provincial_Laboratory  EPI_ISL_2495421 Male  Female

**Comment by lindaxiang** [comment]
@scottcain @nithujohn this has been addressed. Thanks.

**Comment by nithujohn** [comment]
@lindaxiang Thank you!!
