### ISSUE TITLE
Sample to be removed-PHO

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#239]
Hi there @scottcain ,

Could you please remove this PHO sample- ON_2960 from the portal? This is a duplicate of another PHO sample (ON_367213).

Thanks,
Chanchal

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain this sample (analysisId: 48b25207-4018-4470-b252-074018f47006) has been removed from the portal.

**Comment by ChanchalYa** [comment]
Thanks very much, @lindaxiang
