### ISSUE TITLE
Samples to be removed- QC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#241]
Hi @scottcain ,

Could you please remove the QC samples- QC_70619, QC_287867,QC_287865 from the portal? There are some duplicate virus name issues related to these samples.

Thanks,
Chanchal

**Comment by ArtPoon** [comment]
We just detected a duplicate entry as well: `QC-1nDJXQ-2036201174A`
Documented at https://github.com/CoVaRR-NET/duotang/issues/45

**Comment by lindaxiang** [comment]
@scottcain @ChanchalYa @ArtPoon the above samples have been removed from portal. 
Here is the log file:
[QC_remove.samples.log](https://github.com/cancogen-virus-seq/portal/files/8627044/QC_remove.samples.log)

**Comment by ChanchalYa** [comment]
Thanks @lindaxiang !
