### ISSUE TITLE
Metadata updates- PHO

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#242]
Hi @scottcain ,

Could you please update the host age bin in the portal for these PHO samples? Our partners have provided these updates.

Thanks,
Chanchal
[PHO_HostAgeBin_updates_20220503.csv](https://github.com/cancogen-virus-seq/portal/files/8611848/PHO_HostAgeBin_updates_20220503.csv)

**Comment by lindaxiang** [comment]
@scottcain @ChanchalYa The above samples have been updated. 
Here is the log:
[PHO-ON.migrate_consensus_sequence.log](https://github.com/cancogen-virus-seq/portal/files/8627105/PHO-ON.migrate_consensus_sequence.log)

**Comment by ChanchalYa** [comment]
Thanks @lindaxiang !
