### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#243]
Hi @scottcain, while uploading the samples in to the portal one of the sample resulted in internal server error. Can you please have a look and let me know that I have to re-upload the sample? Thanks!

![image](https://user-images.githubusercontent.com/85367999/166496032-69ea5e4e-b740-4a1c-ba93-d11a58de3a1a.png)

PHO-ON | ON_401255 | e90cc52a-83e2-426f-8cc5-2a83e2526f69 | ERROR:Internal server error!

**Comment by scottcain** [comment]
That looks not great; @jaserud can you take a look?

**Comment by scottcain** [comment]
@nithujohn we checked the server and there was no error message in the log, but that sequence didn't make it into the data store, so it needs to be re-uploaded.

**Comment by nithujohn** [comment]
Hi @scottcain I re- uploaded the sample. Thanks!
![image](https://user-images.githubusercontent.com/85367999/167165032-3e86bc0f-4057-492b-ab5d-bfcb549732b8.png)
