### ISSUE TITLE
Metadata updates- QC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#244]
Hi @scottcain ,

Could you please update the sample collection date for these QC samples? Our partners have provided these updates.

Thanks,
Chanchal

[QC_SampleCollectionDateUpdates_20220503.csv](https://github.com/cancogen-virus-seq/portal/files/8612435/QC_SampleCollectionDateUpdates_20220503.csv)

**Comment by lindaxiang** [comment]
@scottcain @ChanchalYa The above samples have been updated. 
Here is the log:
[LSPQ-QC.update_sample_collection_date.log](https://github.com/cancogen-virus-seq/portal/files/8627104/LSPQ-QC.update_sample_collection_date.log)

**Comment by ChanchalYa** [comment]
Thanks @lindaxiang !
