### ISSUE TITLE
Metadata update (sample collected by)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#245]
Hi @scottcain there is a new tag for the field "sample collected by" I have included below. Can you please update the schema? Thanks!

"Shared Hospital Laboratory"

**Comment by scottcain** [comment]
This is something you can do, righ @lindaxiang ?  Thanks.

**Comment by lindaxiang** [comment]
The tag has been added. @scottcain @nithujohn

**Comment by nithujohn** [comment]
Thanks @lindaxiang
