### ISSUE TITLE
metadata updates- NML

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#247]
Hi @scottcain ,

Could you please update the list of samples attached here for "specimen collector sample ID", "geo_loc_name (country)", "geo_loc_name (state/province/territory)", "isolate" columns?

Thanks,
Chanchal

[samples_to_update_VirusSeq_20220510.xlsx](https://github.com/cancogen-virus-seq/portal/files/8665108/samples_to_update_VirusSeq_20220510.xlsx)
l

**Comment by ChanchalYa** [comment]
Hi again @scottcain @lindaxiang ,

Once you have applied the updates from samples_to_update_VirusSeq_20220520.xlsx in the comment above, could you please update the `isolate` and `fasta header name` using this attached file? I have sent the fasta sequences with updated headers to Nithu.

Thanks so much,
Chanchal
[virusseq_updates_20220525.csv](https://github.com/cancogen-virus-seq/portal/files/8773946/virusseq_updates_20220525.csv)

**Comment by lindaxiang** [comment]
@scottcain @ChanchalYa 
 These updates are to change the `submitter_sample_id` and `fasta_header_name` . For these cases, it’s not purely payloads updating tasks, and it will need fasta file re-uploading as well. So I would suggest:
- I can suppress all the requested samples from portal
- the user will need to re-submit the correct metadata and fasta files.

**Comment by ChanchalYa** [comment]
Hi @lindaxiang ,
Please go ahead and suppress all the samples with study id `COVID-CAN` and Submission date of `2022-05-06` , there is a total of 2325 samples. I will re-submit the metadata and fasta files to Nithu today.

Thank you very much,
Chanchal

**Comment by lindaxiang** [comment]
@ChanchalYa Can you confirm all the 2325 samples in the attached table are to be suppressed?
[COVID-CAN.to-remove.specimen_collector_sample_ID.txt](https://github.com/cancogen-virus-seq/portal/files/8799551/COVID-CAN.to-remove.specimen_collector_sample_ID.txt)

**Comment by ChanchalYa** [comment]
Hi @lindaxiang ,

Yes, please suppress these samples. I have sent the modified metadata and fasta seqs for these samples to Nithu already that she can submit once the current samples in VirusSEQ have been suppressed.

Thanks,
Chanchal

**Comment by lindaxiang** [comment]
@ChanchalYa the samples in the above list have been suppressed from the portal. Here is the log file.
[to_remove.sample_analysis.txt](https://github.com/cancogen-virus-seq/portal/files/8799850/to_remove.sample_analysis.txt)

**Comment by ChanchalYa** [comment]
Thanks very much @lindaxiang !
