### ISSUE TITLE
Sample Removal - QC 

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#248]
Hi @scottcain 

Could you please remove the QC sample: 

QC_287870

isolate: hCoV-19/Canada/QC-1nDJXQ-2036201249A/2020

We suspect the metadata does not belong with the sequence. 

Thank you!

**Comment by lindaxiang** [comment]
@scottcain @GH-Emily the above sample is removed. 
analysisId: a8feb55a-f9b9-40d6-beb5-5af9b9c0d6fe
