### ISSUE TITLE
Metadata Updates - NB

### ISSUE THREAD

**Issue by Mach-2** [cancogen-virus-seq/portal#251]
Hi @scottcain 

I have a few samples from NB that require an update for their collection dates. I'm attaching the file here. 

[NB-collection-date-update-request.csv](https://github.com/cancogen-virus-seq/portal/files/8709427/NB-collection-date-update-request.csv)

Thank you! 
Madison

**Comment by lindaxiang** [comment]
@scottcain @Mach-2 Just did a quick check, the samples' `sample collection date` currently on the portal are the same with what you want to update. Can you confirm that?

**Comment by Mach-2** [comment]
@lindaxiang Thanks for checking! Looks like no update is required, these are the correct values.

**Comment by scottcain** [comment]
@lindaxiang I think the collection dates in the csv file are one day off from what is currently in the data store. For example, NB_249265 in the data store has a collection date of 2021-11-04, but in @Mach-2 csv file, the same sample has a collection date of 2021-11-05. Checking a few more on the list show the same pattern.

**Comment by scottcain** [comment]
LOL. If @Mach-2 says it's good, it's good :-)

**Comment by Mach-2** [comment]
Sorry @scottcain, looks like I spoke too soon. I saw @lindaxiang's message that the dates were the same, but didn't check for myself. I just checked the data portal and it does look like there is a one day difference after all. Could these dates please be updated to what is in the attached file? 

Apologies for the confusion!

**Comment by b-f-chan** [comment]
Need to investigate first on our side, as we realized the sample collection date on VirusSeq platform has one day offset from the user-provided date.  Seems this has been true since Day 0 of the platform - But we need to investigate.  VirusSeq date is one day offset earlier/before the user-provided date.

**Comment by sifavahora** [comment]
@lindaxiang can these dates please be updated. thanks.

**Comment by sifavahora** [comment]
Not a data issue, Its the display issue while converting string to data format. Closing this issue as have created another ticket to address this https://github.com/cancogen-virus-seq/portal/issues/259
