### ISSUE TITLE
Metadata updates- PHO

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#252]
Hi there @scottcain,

Could you please update VirusSeq for the attached list of metadata updates for PHO? Our partners have provided these updates.

Thanks,
Chanchal
[PHO_metadata_updates_VirusSeq_20220517.csv](https://github.com/cancogen-virus-seq/portal/files/8709835/PHO_metadata_updates_VirusSeq_20220517.csv)

**Comment by lindaxiang** [comment]
@scottcain @ChanchalYa the above samples have been updated on the portal. 
[PHO_metadata_updates_VirusSeq_20220517.log](https://github.com/cancogen-virus-seq/portal/files/8734419/PHO_metadata_updates_VirusSeq_20220517.log)

**Comment by ChanchalYa** [comment]
Thanks @lindaxiang!
