### ISSUE TITLE
Metadata updates- border

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#256]
Hi @scottcain,

Could you please update these border samples for `Purpose of sampling` ? 

Thank you very much,
Chanchal
[VirusSeq_update_POS_20220526.xlsx](https://github.com/cancogen-virus-seq/portal/files/8780118/VirusSeq_update_POS_20220526.xlsx)

**Comment by b-f-chan** [comment]
@lindaxiang could you please take a first crack at this?

**Comment by lindaxiang** [comment]
@b-f-chan @sifavahora @ChanchalYa The samples have been updated as request. 
Here is the log: 
[VirusSeq_update_POS_20220526.log](https://github.com/cancogen-virus-seq/portal/files/8893077/VirusSeq_update_POS_20220526.log)

**Comment by sifavahora** [comment]
Thanks @lindaxiang :)  @ChanchalYa can you please confirm the issue can be closed?

**Comment by ChanchalYa** [comment]
Thank you very much @lindaxiang!
