### ISSUE TITLE
Check Pending upgrades for services throughout the components of the architecture

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#260]
As we resume work on this portal, it would be a good first step to identify and then update(after discussion with the team) any/all services/component for a smoother development and debugging experience.

**Comment by sifavahora** [comment]
@UmmulkiramR to list the pending upgrades

**Comment by sifavahora** [comment]
Song 
Maestro 
Singularity * - after multiple tags execution 
Muse * -  after multiple tags execution

**Comment by sifavahora** [comment]
@caravinci  We want to upgrade Song and Maestro for now.

**Comment by caravinci** [comment]
Sond and Maestro have been running in prod for a few days now.
The other services mentioned in this ticket will be updated on an individual, improvements-made basis.
