### ISSUE TITLE
Suppress duplicate IDs (BC uploads)

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#262]
Hi @scottcain, I have attached a file with duplicate IDs, please suppress the IDs from the portal. Thanks!
[Duplicate IDS BC.xlsx](https://github.com/cancogen-virus-seq/portal/files/8873529/Duplicate.IDS.BC.xlsx)

**Comment by lindaxiang** [comment]
@nithujohn @scottcain @sifavahora the above 1028 duplicated submissions(submitted on 2022-06-09) are suppressed from the portal. 
Here is the log: 
[Duplicated_analysis.BC.remove.txt](https://github.com/cancogen-virus-seq/portal/files/8920477/Duplicated_analysis.BC.remove.txt)

**Comment by nithujohn** [comment]
Thanks @lindaxiang
