### ISSUE TITLE
metadata update- BC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#266]
Hi there @scottcain ,

Could you please update the `purpose of sampling` to `Restricted Access` for the list of BC samples attached here?

Thank you,
Chanchal

[Metadata_update_BC_20220620.csv](https://github.com/cancogen-virus-seq/portal/files/8941921/Metadata_update_BC_20220620.csv)

**Comment by lindaxiang** [comment]
@sifavahora @ChanchalYa The field: `purpose of sampling` has been updated to `Restricted Access` for the list of above BC samples. Here is the log file:
[Metadata_update_BC_20220620.log](https://github.com/cancogen-virus-seq/portal/files/8993299/Metadata_update_BC_20220620.log)

**Comment by ChanchalYa** [comment]
Thanks so much @lindaxiang !
