### ISSUE TITLE
Metadata Update - SK

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#267]
Hi Scott, 

Looking to get the consensus sequence method version numbers updated after a click and drag error was identified. 
[2022-06-20_Issue228_VirusSeq.csv](https://github.com/cancogen-virus-seq/portal/files/8943554/2022-06-20_Issue228_VirusSeq.csv)

some of these may not be in data portal

Emily

**Comment by lindaxiang** [comment]
@GH-Emily , can you confirm that you only want to update the values in column `Consensus Sequence Method Version` for given `Virusseq ID`? What to do with the `Virus Name` column? Is it just for our information? Thanks

**Comment by GH-Emily** [comment]
@lindaxiang sorry for the confusion. The virus names were just unnecessary information. An updated copy of the file is attached! 

[2022-06-20_Issue228_VirusSeq.csv](https://github.com/cancogen-virus-seq/portal/files/8976814/2022-06-20_Issue228_VirusSeq.csv)

**Comment by edsu7** [comment]
`consensus_sequence_software_version` updated for `106/176` samples

As an example `088fcbc6-1e7b-4d89-8fcb-c61e7b9d8904`/`SK_282084` previously was :

`"consensus_sequence_software_version": "21.04.10"`
updated to 
`"consensus_sequence_software_version": "21.04.0"`

**Comment by sifavahora** [comment]
@GH-Emily can you please confirm and close the issue if applicable?

**Comment by GH-Emily** [comment]
thank you!
