### ISSUE TITLE
Samples not indexing on the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#269]
Hi @sifavahora, I did a small set of 236 samples in the morning and looks like none of them are indexed on the portal. I have attached an excel sheet with the submission ID and analysis ID. Thanks!

Data Submission: 6d48a639-a436-4816-810a-ee1c9162a9a4

[SK.xlsx](https://github.com/cancogen-virus-seq/portal/files/8977695/SK.xlsx)

![image](https://user-images.githubusercontent.com/85367999/175580437-90d158a3-29f1-46f7-9c2a-ae1dc0c8b8da.png)

**Comment by sifavahora** [comment]
Hi @nithujohn. I see the 236 samples on the portal. Can you please tell me if I am missing something here? 
![image](https://user-images.githubusercontent.com/30519419/175647107-838ca3ba-6ae2-43f2-b54f-2749f9c5cc86.png)

**Comment by nithujohn** [comment]
Hi @sifavahora I can see now the 236 samples before it was not showing. Thanks!
