### ISSUE TITLE
Add Appropriate error message for failed uploads for Submission Dashboard

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#270]
1. Display appropriate error message for failed upload. (On the specific submission Page, Screenshot added by Nithu) 
2.  Highlight the failed uploads so that the users can identify them. (on the Submission Dashboard)
 ![image.png](https://images.zenhubusercontent.com/62963afc91a20472a00e6690/aa9ba7f4-e58d-46f2-a875-89e82c96fced)

**Comment by sifavahora** [comment]
@nithujohn can you please upload a screenshot of the error message that you get currently? thanks

**Comment by nithujohn** [comment]
![image](https://user-images.githubusercontent.com/85367999/175977519-f38ae1cf-57e9-446f-b46b-077f75408100.png)

**Comment by sifavahora** [comment]
@nithujohn. We investigated on this on our end and we concluded that all the Data/format related errors display appropriate messages on the submission dashboard, only the server errors do not show detailed messages. Its a standard practice to not display server error details because the users cannot solve them on their end. To double check that we have covered all data/format related error can you please give us submission ID's for some of your latest attempts of sample upload where you saw errors with incomplete/no details?

**Comment by sifavahora** [comment]
Attaching a picture of submission portal where there is data/format error. The portal does display the error however it can be worded better for the users to understands. 
![image.png](https://images.zenhubusercontent.com/62963afc91a20472a00e6690/0c4d33ad-8620-4c28-a9d1-089a4295c902)

**Comment by nithujohn** [comment]
Hi @sifavahora Thank you so much for confirming. I have attached a list of latest IDs which showed internal server error at my end. 
[DP errors.txt](https://github.com/cancogen-virus-seq/portal/files/9066124/DP.errors.txt)

**Comment by sifavahora** [comment]
@UmmulkiramR can you please check the error logs and confirm they are system errors?

**Comment by UmmulkiramR** [comment]
@nithujohn Thank you for the list of IDs. I can see these are the analysis IDs for the submission 9a4c899d-924f-4176-b5b9-00868ab20aab made on 9th June. 
I checked but could not find any logs for them. Would it be possible for you to send across IDs for a more recent submission that gave you the same error, something that is less than a month old?

**Comment by nithujohn** [comment]
Hi @UmmulkiramR, all these internal errors popped up during the bulk upload of BC. But if I get these errors again I can let you know.  Thanks!

**Comment by sifavahora** [comment]
Closing now , updating Song and Maestro and Making some resource allocation changes on Muse Pod have solved the issues- so we are not facing any errors. As for the format errors they are well described.
