### ISSUE TITLE
Upload 40K Test Samples on Dev Portal

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#276]
We need massive data on the dev portal to test and troubleshoot production issues like bundles getting stuck in the building stage for huge dataset. We keep the target to upload 40 K samples as of now, we may need more later.

**Comment by b-f-chan** [comment]
@edsu7 tried manual upload, ran for a day still didn't complete

Handed off to @caravinci and DevOps to resolve via direct upload method (instead of through portal)

**Comment by caravinci** [comment]
Methinks it's fair to say this ticket is done?

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/c88527c1-dbad-410f-a2e4-1359fe608523
)

**Comment by sifavahora** [comment]
It is.
