### ISSUE TITLE
MB duplicates in the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#277]
Hi @sifavahora, I just uploaded an MB set which are duplicates in the portal. Can you please delete the duplicate IDs I have included below. Thanks!

[MB.xlsx](https://github.com/cancogen-virus-seq/portal/files/9041154/MB.xlsx)

**Comment by edsu7** [comment]
Done. 239 Analyses with the date `2022-07-04` have been suppressed.

Before (focusing only on MB_433327):
![before screenshot.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/b4edcad0-8466-4780-bd26-262152c28bc4)

After:
![after screenshot.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/b562f3e9-111f-420d-8c5e-42c0c56dfc68)

**Comment by nithujohn** [comment]
Hi @edsu7 Thank you so much! Is there any issue with MB_433327 or you just would like to demonstrate that today's submission was deleted

**Comment by edsu7** [comment]
Just a demonstration (and sanity check for my own sake)
