### ISSUE TITLE
ON - Give samples New Specimen collector sample ID

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#278]
Hi  @scottcain  

In order to solve an internal duplication issue, we need to assign the attached Ontario samples a new specimen collector sample ID. Our records indicate that samples: 

ON_350535
ON_350550
ON_350560
ON_350551
ON_350567
ON_350556
ON_350553
ON_350566
ON_350542
ON_350547

are not in VirusSeq, but I have included them in the attached update file just in case our records are not up to date. 

[2022-07-07_dataportalUpdate_issue247.csv](https://github.com/cancogen-virus-seq/portal/files/9066092/2022-07-07_dataportalUpdate_issue247.csv)

**Comment by scottcain** [comment]
Hi @GH-Emily I want to make sure I understand: you think we probably don't need to anything, but are giving us this list in case we do? Or, having now looked at the attached file, there are some samples that need a new specimen collector sample ID, but maybe not every sample in the file is in the VirusSeq data store, right?

**Comment by GH-Emily** [comment]
that list is correct, please suppress these samples.

**Comment by edsu7** [comment]
Done. The `65` analyses listed above have been suppressed.

**Comment by GH-Emily** [comment]
thank you! we will re-submit soon.
