### ISSUE TITLE
Homepage + Footer Updates

### ISSUE THREAD

**Issue by kcullion** [cancogen-virus-seq/portal#28]
Zeplin link: https://zpl.io/VYqrkrw

- [x] Since we don't have a chart, please revise the stats display. If we can make the banner a bit shorter, let's do so (as long as the researcher picture isn't cut off too much)
![image](https://user-images.githubusercontent.com/18424138/115896137-181b7880-a429-11eb-9ced-20ea5e6fedf3.png)

- [x] Add the COVID Cloud callout at the bottom.
External links open in a new window: 
DNAstack links to: www.dnastack.com
the `COVID Cloud logo` and `Explore VirusSeq Data on COVID Cloud` link to https://virusseq.covidcloud.ca/
![image](https://user-images.githubusercontent.com/18424138/115896472-78121f00-a429-11eb-9d52-d1507f3ff25f.png)

- [x] Add github link to the right of the overture logo, opens in new window and links to: https://github.com/cancogen-virus-seq
![image](https://user-images.githubusercontent.com/18424138/115897248-36ce3f00-a42a-11eb-8520-92847833242a.png)

- [x] Add "About the Team" button to the banner - links to new page from: https://github.com/cancogen-virus-seq/portal/issues/29

**Comment by rosibaj** [comment]
looks great thank you @caravinci !
