### ISSUE TITLE
MB duplicates in the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#280]
Hi @sifavahora, I have uploaded 321 samples from MB in the portal. But there was a glitch in the NML database which resulted in duplicates again. Apologies for the extra work!. I have attached the IDs to suppress from the portal. Thanks!
[MB.xlsx](https://github.com/cancogen-virus-seq/portal/files/9087409/MB.xlsx)

**Comment by sifavahora** [comment]
@edsu7 can you please take a look? Thanks.

**Comment by edsu7** [comment]
The latest analyses `(n=239)` of the above provided `submitterSpecimenIds` have been suppressed.

```
  "analysisId": "f0ee0c65-4cd2-40c8-ae0c-654cd240c882",
  "studyId": "MCPL-MB",
  "analysisState": "SUPPRESSED",
  "analysisStateHistory": [
    {
      "initialState": "UNPUBLISHED",
      "updatedState": "PUBLISHED",
      "updatedAt": "2022-07-11T19:39:48.848746"
    },
    {
      "initialState": "PUBLISHED",
      "updatedState": "SUPPRESSED",
      "updatedAt": "2022-07-12T17:34:11.062351"
    }
  ],
```

**Comment by nithujohn** [comment]
Thank you @edsu7 @sifavahora
