### ISSUE TITLE
File counts do not match on the home page and Explorer page

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#281]
![image (3)](https://user-images.githubusercontent.com/30519419/178549627-6fe45a8c-e824-410e-9905-b1beb8bbed0f.png)

It looks like the count on the homepage comes from a cached count on the server. Ideally the cache should refresh every time there is a new upload on the portal.

**Comment by sifavahora** [comment]
Because the count comes from singularity https://github.com/cancogen-virus-seq/singularity/issues/38

**Comment by caravinci** [comment]
This issue may be resolved with https://github.com/cancogen-virus-seq/singularity/issues/51
