### ISSUE TITLE
SK - Sample redaction 

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#283]
Hi @scottcain,

SK identified a mapping issue with the following samples. Could you please remove from VirusSeq?

SK_447565
SK_447568
SK_447569
SK_447571
SK_447558
SK_447545
SK_447549
SK_447546
SK_447547
SK_447576
SK_447556
SK_447574
SK_447575
SK_447557
SK_447561
SK_447578
SK_447580
SK_447548
SK_447597
SK_447550
SK_447586
SK_447577
SK_447600
SK_447553
SK_447608
SK_447583
SK_447579
SK_447610
SK_447591
SK_447589
SK_447594
SK_447596
SK_447619
SK_447620
SK_447601
SK_447624
SK_447627
SK_447622
SK_447616
SK_447618
SK_447604
SK_447605
SK_447633
SK_447625
SK_447609
SK_447611

**Comment by edsu7** [comment]
The above `46` analyses have been suppressed.
```
{
  "analysisId": "550e0887-eaf2-4b44-8e08-87eaf27b44aa",
  "studyId": "RRPL-SK",
  "analysisState": "SUPPRESSED",
  "createdAt": "2022-06-24T16:16:29.307933",
  "updatedAt": "2022-07-12T22:16:16.059938",
  "firstPublishedAt": "2022-06-24T16:16:39.429464",
  "publishedAt": "2022-06-24T16:16:39.429464",
  "samples": [
    {
      "submitterSampleId": "SK_447610",
```

**Comment by GH-Emily** [comment]
thank you!
