### ISSUE TITLE
QC sample update and supression

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#289]
Hi @sifavahora, 

Could you please remove:

QC_235020
QC_235155
QC_291764
QC_287168
QC_287169
QC_287170

And could you please update collection dates for: 

ID | New collection date
-- | --
QC_138109 | 2021-04-09
QC_155981 | 2021-05-11
QC_139914 | 2021-05-19
QC_139915 | 2021-05-19

Thanks!

**Comment by sifavahora** [comment]
Onhold, Until we get a confirmation from ViralAI to make changes to portal data. 
Currently holdong off anything that triggers a release. 

Also could be related to https://github.com/cancogen-virus-seq/portal/issues/259
please check with @caravinci

**Comment by GH-Emily** [comment]
hi @sifavahora I believe these collection dates were off by a year, so wouldn't be a part of #259

**Comment by sifavahora** [comment]
Thanks @GH-Emily for this information. We will check again and get back to you.

**Comment by sifavahora** [comment]
@GH-Emily you are right, sorry about missing that. We will do as requested.

**Comment by edsu7** [comment]
The following IDs have had their `sample_collection_date` changed:
```
QC_138109
QC_155981
QC_139914
QC_139915
```

As an example -
Previously:
```
"analysisId": "41f1bf56-4177-4676-b1bf-564177967612",...
"submitterSampleId": "QC_155981",...
"sample_collection_date": "2020-05-11",...
```

Now:
```
"analysisId": "41f1bf56-4177-4676-b1bf-564177967612",...
"submitterSampleId": "QC_155981",...
"sample_collection_date": "2021-05-11",...
```

**Comment by edsu7** [comment]
The following IDs have been suppressed:
```
QC_235155
QC_291764
QC_287168
QC_287169
QC_287170
```
As an example:
```
"analysisId": "6babf5d1-509e-4916-abf5-d1509e391683",...
"studyId": "LSPQ-QC",...
"analysisState": "SUPPRESSED",...
"submitterSampleId": "QC_287169",...
```

`QC_235020` was not associated with existing analyses

**Comment by GH-Emily** [comment]
thank you!
