### ISSUE TITLE
About the Team page

### ISSUE THREAD

**Issue by kcullion** [cancogen-virus-seq/portal#29]
Zeplin: https://zpl.io/Vq3vKYl

- [x] Add "About the Team" item in top navbar
- [x] Build the team page. Content may change
- [x] The links are all external - open in a new window and are as follows:
![image](https://user-images.githubusercontent.com/18424138/115901537-561b9b00-a42f-11eb-867f-851f4882e560.png)

1. www.genomecanada.ca
2. www.canada.ca
3. https://www.genomecanada.ca/en/cancogen
4. https://www.canada.ca/en/public-health/news/2021/02/government-of-canada-invests-53-million-to-address-covid-19-virus-variants-of-concern.html
5. https://www.genomecanada.ca/en/cancogen/cancogen-virusseq
6. www.genomecanada.ca
7. https://www.genomecanada.ca/en/cancogen

![image](https://user-images.githubusercontent.com/18424138/115906353-69ca0000-a435-11eb-910c-05933715c0f2.png)

1. https://www.computationalgenomics.ca/c3g-montreal-node/
2. https://softeng.oicr.on.ca/team/
3. www.oicr.on.ca
4. www.overture.bio. 
5. www.overture.bio
6. www.oicr.on.ca
7. www.dnastack.com
8. www.ga4gh.org
9. https://www.digitalsupercluster.ca/covid-19-program-page/beacon-realtime-global-data-sharing-network/
10. https://www.digitalsupercluster.ca/
11. https://virusseq.covidcloud.ca/
12. www.dnastack.com

**Comment by andricDu** [comment]
https://portal.dev.cancogen.cancercollaboratory.org/team

**Comment by kcullion** [comment]
@andricDu @caravinci  If there's time...some thing I noticed...

- [ ] Can you center the white container of content, it's not quite centered/

- [ ] can you style the links like the ones on homepage and portal...so same default and hover state? I'm seeing different colours 
![image](https://user-images.githubusercontent.com/18424138/115923868-ecaa8500-a44c-11eb-8201-373404f82057.png)

- [ ] some links take me to page not found. Sorry I should have added the `http://` in the above links
![image](https://user-images.githubusercontent.com/18424138/115924095-427f2d00-a44d-11eb-9b67-8f5a90937140.png)

- [ ] can you open all links in a new window

- [ ] 
![image](https://user-images.githubusercontent.com/18424138/115924936-6727d480-a44e-11eb-99c5-781ef1710a33.png)

**Comment by caravinci** [comment]
Made all these changes. Deploying to Dev right now

**Comment by rosibaj** [comment]
Tested Apr 26: 

-[ ]  links are still broken in last paragraph 

![image](https://user-images.githubusercontent.com/15824252/116095892-cec06880-a676-11eb-8e82-5050154b9c2c.png)

- DNASTACK leading to https://portal.dev.cancogen.cancercollaboratory.org/www.dnastack.com
- GA4GH link leading t0 https://portal.dev.cancogen.cancercollaboratory.org/www.ga4gh.org 

Moving back to in progress until this is addressesd.

**Comment by rosibaj** [comment]
April 26 10:50 retested 
- all links on the team page now navigate correctly. 

ty lgtm @caravinci !
