### ISSUE TITLE
sample to be removed- QC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#291]
Hi there @sifavahora ,

Could you please remove this sample - `L00414320` from the portal? There is a duplicate of another sample.

Thank you,
Chanchal

**Comment by GH-Emily** [comment]
@sifavahora as part of the same issue that @ChanchalYa has described above, could you please also remove: 

QC_287872
QC_287874

**Comment by sifavahora** [comment]
Sure @GH-Emily. @edsu7  please consider Emily's comment when you take up the ticket.

**Comment by edsu7** [comment]
The following IDs have been suppressed:
```
L00414320
QC_287872
QC_287874
```

As an example:
```
"analysisId": "5718d916-a160-4b0d-98d9-16a160eb0d21",...
"studyId": "LSPQ-QC",...
"analysisState": "SUPPRESSED",...
"submitterSampleId": "L00414320",...
```

**Comment by ChanchalYa** [comment]
Thanks very much @sifavahora @edsu7 !
