### ISSUE TITLE
Samples got stuck during upload

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#293]
Hi @sifavahora, I did an upload of 304 samples (Border sequences) and 126 samples completed but some of them got stuck during upload. I have attached an excel sheet and let me know the samples need to re- upload. 
#105 looks similar to this issue Thanks!

[BD.xlsx](https://github.com/cancogen-virus-seq/portal/files/9162624/BD.xlsx)
![image](https://user-images.githubusercontent.com/85367999/180848660-4fc2d60b-f71f-4c1e-bc3e-39f23b98cbc4.png)

**Comment by nithujohn** [comment]
Re- uploaded the samples today and it worked it!
![image](https://user-images.githubusercontent.com/85367999/180493800-9e34b251-1de7-4d03-85b0-0cc85de36b48.png)

**Comment by sifavahora** [comment]
Hi @nithujohn, We will check this. Thanks for reporting.

**Comment by sifavahora** [comment]
closing this for now.  We have upgrade Muse services for better upload experience.
