### ISSUE TITLE
metadata update- MB

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#299]
Hi there @sifavahora,

Could you please update the gender for these following MB samples in the portal?

`MB_95134 `   --> `Unknown`
`MB_94849` ---> `Female`

Thanks,
Chanchal

**Comment by edsu7** [comment]
Hi @ChanchalYa,
Could you specify if you wished to update `gender` or `host_gender`.

```
"studyId": "MCPL-MB", 
"gender": "Other", 
"submitterDonorId": "MB_95134",
"host_age": 59, 
"host_gender": "Male",
"host_age_bin": "50 - 59", 
"host_disease": "COVID-19", 
"host_age_unit": "year",
"host_age_null_reason": null, 
"host_scientific_name": "Homo sapiens"

**Comment by ChanchalYa** [comment]
Hi there,

Could you please update `host_gender` ?


Thanks.
Chanchal

**Comment by edsu7** [comment]
The following samples' `host_gender` have been updated:
```
MB_95134
MB_94849
```

Example:
```
"MB_94849",
"host_gender": "Male",
```
is now
```
"MB_94849",
"host_gender": "Female"
```

**Comment by ChanchalYa** [comment]
thank you very much @edsu7 !
