### ISSUE TITLE
UI Styling Feedback: Search Page

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#3]
# Header
- [x] Change “About VirusSeq Portal” to “About VirusSeq Data Portal”
- [x] Change “Explore COVID-19 Data” to “Explore VirusSeq Data”
- [x] Make the fonts for both bold

# Footer
- [x] Make the text not bold
- [x] Make the Genome Canada logo bigger. Note for @caravinci when you make this larger can you decrease the top and bottom padding just around this logo, so the footer doesn't get much bigger than it already is? if not, that's fine
- [x] Remove Genome Canada link (the logo already links)
- [x]  Change “2021 CanCOGeN VirusSeq Data Portal” to “2021 Canadian VirusSeq Data Portal

# Landing page
- [x] Replace `The goal of VirusSeq ...and ensuring data access to the research community.` with `The goal of the CanCOGeN VirusSeq project is to sequence up to 150,000 viral samples from Canadians testing positive for COVID-19. The VirusSeq Data Portal is an open-source and open-access data portal for all Canadian SARS-CoV-2 sequences and associated non-sensitive clinical/epidemiological data. It harmonizes, validates and automates submission to international databases.`
- [x] Make the above text not bold.
- [x] Under “Impact on Canadians”, change “Genomics-based” to “Genomic-based”; “COVID-19 virus” to “SARS-CoV-2 virus”

# Explorer
- [x]  Facet categories, eg. “Analysis Type”, “File Type”, make the fonts smaller, about the same size as “Filters” at the top.
- [x] Facet restyling.
![image](https://user-images.githubusercontent.com/15824252/114190734-a23beb00-9919-11eb-8a77-1152b35f9b70.png)

- [x] selected values: use the darker blue from this mockup (the lighter blue isn't accessible) https://zpl.io/awzeOmK
![image](https://user-images.githubusercontent.com/18424138/114192000-ff846c00-991a-11eb-8260-f2ebc98c7112.png)

- [ ] ~Download link to docs - @rosibaj is there a page explaining how to download data with a file manifest? I couldn't find this. Also add a period to this sentence.~
![image](https://user-images.githubusercontent.com/18424138/114194401-6f93f180-991d-11eb-8dd8-c6da4d2fb9bc.png)

- [x] I think this should say "Start by selecting filters." As we call them filters in the title, and technically you are selecting "values" not fields.
![image](https://user-images.githubusercontent.com/18424138/114194771-cef20180-991d-11eb-8aa8-d4bf4965bb55.png)

- [x] Make the text in the top right and y axis `# Viral Genomes` so # Viral Genomes by Province.  The tooltip should be fine; the label `Host Age` is clear. 
 ![image](https://user-images.githubusercontent.com/18424138/114195270-52abee00-991e-11eb-9e77-21f794498739.png)

- [x] I thought we were going to show age "bins"? otherwise will this chart be each individual age that's in the portal?
![image](https://user-images.githubusercontent.com/18424138/114199874-af110c80-9922-11eb-9924-e7fd38ef4936.png)

- [x] Should we specify what this number is counting for clarity. [not urgent will save for later if desired]
![image](https://user-images.githubusercontent.com/18424138/114196555-791e5900-991f-11eb-8f81-29b6dba2f74b.png)

# Brand
- [x] If there's time, use the font that CanCOGen uses: https://fonts.google.com/specimen/Source+Sans+Pro
(this font may make the regular weight not seem as bold?)

# Submitter Login page

- [x] you could use the same font style as the paragraphs on the homepage, this seems a bit small. 
- [x] Change "COVID-19 Data is submitted" to "Viral genomes are submitted"
- [x] the "request an account" link could link right to the CanCOGen contact form, as well as the footer "contact us" link: @rosibaj Thoughts?  https://www.genomecanada.ca/en/cancogen/contact-us

![image](https://user-images.githubusercontent.com/18424138/114198283-22198380-9921-11eb-912d-c4032a45a2cc.png)
![image](https://user-images.githubusercontent.com/18424138/114198860-cb607980-9921-11eb-9e07-17ab29a5a915.png)

**Comment by kcullion** [comment]
> For "Facet categories, eg. “Analysis Type”, “File Type”, make the fonts smaller, about the same size as “Filters” at the top.", Both "Filters" and the category titles, are all 16px. Making the later smaller than instead (14px).
> 
> ![image](https://user-images.githubusercontent.com/2107110/114194819-dd401d80-991d-11eb-99e3-d85618b8afe2.png)

If you switch the font to source-sans-pro - that may take care of some sizing and fonts looking too bold? If not, you can make the field labels 14px

**Comment by rosibaj** [comment]
@kcullion `Download link to docs - @rosibaj is there a page explaining how to download data with a file manifest? I couldn't find this. Also add a period to this sentence.`  No there is no page for this , and might not be how this particular download works.  need more info

**Comment by rosibaj** [comment]
Re: -the "request an account" link could link right to the CanCOGen contact form, as well as the footer "contact us" link: @rosibaj Thoughts? https://www.genomecanada.ca/en/cancogen/contact-us

This flow is not in scope of this ticket

**Comment by caravinci** [comment]
> @kcullion `Download link to docs - @rosibaj is there a page explaining how to download data with a file manifest? I couldn't find this. Also add a period to this sentence.` No there is no page for this , and might not be how this particular download works. need more info

This is carryover from the DMS-UI spec. The document it's meant to be pointed to hasn't been created yet, but I hear it'll be done next week. I can remove this bit meanwhile, if that makes things easier.

**Comment by rosibaj** [comment]
yes please @caravinci that will work best for now!

**Comment by caravinci** [comment]
Side question: Would it beneficial if I set a Netlify for this project, so we can do iteration more easily? (given the release/deployment hurdles). I have almost all this stuff done by now, yet I reckon a feedback loop is likely necessary here.
Thoughts?

**Comment by rosibaj** [comment]
@caravinci up to you.  if you can do it quickly, sure!

**Comment by caravinci** [comment]
Prepping deployment... NPM takes forever whenever we publish a new version of Arranger.
This should address all the items, but of course I may have to release a new version if there's any additional feedback. For instance, the style for pie charts' tooltips is a temporary solution, and I'm working on formatting the age ranges in a more human-readable fashion.

**Comment by kcullion** [comment]
Thanks @caravinci ..I have some more feedback. @rosibaj please review 

- [ ] Facet panel: 
![image](https://user-images.githubusercontent.com/18424138/114412491-250fb080-9b7b-11eb-8a1d-654a6d9f2fbd.png)

- [ ] Charts question. Rosi, will they all be eventually plotting viral genomes instead of files? My understanding is that there could be multiple files per one viral genome. But I notice the bar chart says viral genome and the pies seem to be plotting files.

- [ ] Tooltips suggestions:
![image](https://user-images.githubusercontent.com/18424138/114410201-2dff8280-9b79-11eb-937b-5da7fb285bb1.png)
![image](https://user-images.githubusercontent.com/18424138/114410542-7323b480-9b79-11eb-90fc-51b32264d091.png)

- [ ] footer 
![image](https://user-images.githubusercontent.com/18424138/114410693-9189b000-9b79-11eb-8693-607271002f49.png)

- [ ] @rosibaj do we want to customize these file names to VirusSeq? like
VirusSeq-file-manifest-20210412.tsv
VirusSeq-table-export-20210412.tsv
![image](https://user-images.githubusercontent.com/18424138/114410972-cac22000-9b79-11eb-8916-3f965d1f485a.png)

- [ ] @rosibaj is there a default table sort that we can illustrate in the table like the following? In the mock they wanted to sort by sample id to display the files for each sample together, but I don't see sample ID by default in this table.
![image](https://user-images.githubusercontent.com/18424138/114411377-1f659b00-9b7a-11eb-9d77-06f4996fe78f.png)

- [ ] filtered query bar..this may be a usual Arranger thing - but this query box becomes a bit taller causing a jump on the page when the user filters the table. It is probably the addition of the button. If possible, please make the height of this box fixed
![image](https://user-images.githubusercontent.com/18424138/114412960-951e3680-9b7b-11eb-86a0-abd40d1e84ff.png)

**Comment by caravinci** [comment]
Thanks for the feedback, @kcullion 
Seems the tooltip for the column chart was meant to be the one for a variants chart that is currently hidden. However, I did apply some of the changes you suggest:
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/2e61fdbe-27aa-484c-b472-b473643c856f)

As mentioned in my latest comment, I'm working on making the age one be a bit more readable. For instance, in the example you give, I intend for it to read "29 to 38 years:".
While "to" or "-" is an easy change, I'm working on logic to recognise whether the range limit is included or not. e.g. `()` vs `[]`. That logic will be included in the next release.

**Comment by kcullion** [comment]
Thanks @caravinci ..let's wait for @rosibaj when she's back as she may have plans for these charts.

**Comment by caravinci** [comment]
Yep. I'm only acting thus far on the ones I know can be fixed (checked in your list).

**Comment by rosibaj** [comment]
Re:
> Charts question. Rosi, will they all be eventually plotting viral genomes instead of files? My understanding is that there could be multiple files per one viral genome. But I notice the bar chart says viral genome and the pies seem to be plotting files.
I already think i told Justin just to say FILES for this chart instead of viral genomes. right now genomes:files is 1:1 but i dont know if that ratio will be maintained. 

>  filtered query bar..this may be a usual Arranger thing - but this query box becomes a bit taller causing a jump on the page when the user filters the table. It is probably the addition of the button. If possible, please make the height of this box fixed
- [ ] the box is working as expected, we don't want to hide any portion of the query the user has selected or make them resize this portion.. Change the default height BEFORE selection to the height when a query is selected to prevent teh jump:
- 
![image](https://user-images.githubusercontent.com/15824252/114567253-0d026480-9c41-11eb-926f-bf442a1825dd.png)

> do we want to customize these file names to VirusSeq? like 
@caravinci IF you have time you can do this, if not, then this is not the most important.

For this last one:
> is there a default table sort that we can illustrate in the table like the following? In the mock they wanted to sort by sample id to display the files for each sample together, but I don't see sample ID by default in this table.

we might be adding a sample id, im not sure yet.  we can revisit default sort when we confirm the exact columns that will be displayed.

**Comment by caravinci** [comment]
Seems I had misread the request to literally "fix the height for the query bar" as "give it a fixed height".
Now I understand you want a consistent minimum height. lol
Apologies.

I've applied all the aforementioned changes, and will be deploying them soon.

**Comment by caravinci** [comment]
Nah Kim... My head is just way toooo literal sometimes. Either way, "I fixed it now" 😉

**Comment by caravinci** [comment]
Changes deployed. Please let me know if I missed anything, @kcullion @rosibaj

**Comment by rosibaj** [comment]
lgtm for now!
