### ISSUE TITLE
metadata update- AB

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#301]
Hi there,

Could you please remove the `GISAID Accession` for these 2 AB samples- 

`AB_82697`
`AB_82620`

Thank you,
Chanchal

**Comment by edsu7** [comment]
`GISAID Accession` have been removed for `AB_82697` and `AB_82620`

As an example to verify,
Before:
```
"submitterSampleId": "AB_82620",
  "database_identifiers": {
    "gisaid_accession": "EPI_ISL_2479726"
  }
```
After:
```
"submitterSampleId": "AB_82620",
  "database_identifiers": {
    "gisaid_accession": null
  }
```

**Comment by ChanchalYa** [comment]
thanks very much @sifavahora  @edsu7 !
