### ISSUE TITLE
Update Sample Information - ON

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#307]
Hi @sifavahora,

Could you please update the attached samples for their reason for sequencing and reason for sequencing details? 

[NML_PHO_reasons_for_sequencing_illumina_2022-07-26_DPupdate1.csv](https://github.com/cancogen-virus-seq/portal/files/9254301/NML_PHO_reasons_for_sequencing_illumina_2022-07-26_DPupdate1.csv)
[NML_PHO_reasons_for_sequencing_illumina_2022-07-26_DPupdate2.csv](https://github.com/cancogen-virus-seq/portal/files/9254303/NML_PHO_reasons_for_sequencing_illumina_2022-07-26_DPupdate2.csv)

I will be submitting more very similar updates, so if you want to hold off on this update until I have time to drop those, feel free :) Let me know if you want the additional updates posted in this issue or added as an additional one!

**Comment by sifavahora** [comment]
Hi @GH-Emily, 

Please add the additional updates on the this ticket itself. We will do all of them together. Thanks.

**Comment by GH-Emily** [comment]
@sifavahora,

okay, after further review, it looks like the remainder of samples that I'm dealing with haven't been submitted to data portal yet! So the only samples to update are in the two attached files above :) 

Emily

**Comment by edsu7** [comment]
1248 samples have been updated. The following is an example:
``` 
"submitterSampleId": "ON_476355",
"experiment": {
    "purpose_of_sequencing": "Missing",
    "purpose_of_sequencing_details": "Missing"
  },
```
updated to
```
"submitterSampleId": "ON_476355",
  "experiment": {
    "purpose_of_sequencing": "Baseline surveillance (random sampling)",
    "purpose_of_sequencing_details": "Surveillance of international border crossing by air travel or ground transport"
  },
```

**Comment by sifavahora** [comment]
@GH-Emily can you please close this if applicable? Thanks.
