### ISSUE TITLE
ON - redaction

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#317]
Hi @sifavahora

Could you please remove the following samples? 

ON_469947
ON_469972
ON_469973
ON_469974
ON_469975
ON_469976
ON_469977
ON_469959
ON_469960
ON_469961
ON_469962
ON_469963
ON_469964
ON_469965
ON_469966
ON_469967
ON_469968
ON_469969
ON_469970
ON_469971
ON_472230
ON_472229
ON_472225
ON_472228
ON_472227
ON_471799
ON_471800
ON_471801
ON_471802
ON_471803
ON_471804
ON_471805
ON_471806
ON_471807
ON_471808
ON_471809
ON_471810
ON_471811
ON_471812
ON_471813
ON_471814
ON_471815
ON_471816
ON_471817
ON_471818
ON_472191
ON_472192
ON_472193
ON_472055
ON_472056
ON_471707
ON_471706
ON_471705
ON_471704
ON_471703
ON_471702
ON_471701
ON_471700
ON_471699
ON_471698
ON_471697
ON_471696
ON_471863
ON_471864
ON_471868
ON_471869
ON_471870
ON_471871
ON_471872
ON_471873
ON_472258
ON_472259
ON_472260
ON_472261
ON_472262
ON_472263
ON_472358
ON_472359
ON_472360
ON_472364
ON_472368
ON_472365
ON_472367
ON_471681
ON_471682
ON_471683
ON_471684
ON_471685
ON_471686
ON_471687
ON_470025
ON_470024
ON_470023
ON_470022
ON_470021
ON_470020
ON_470019
ON_470018
ON_470017
ON_470016
ON_470015
ON_470014
ON_470013
ON_470012
ON_470011
ON_470010
ON_470009
ON_470026
ON_470027
ON_472058
ON_472060
ON_472061
ON_472062
ON_472063
ON_472064
ON_472059
ON_472065
ON_471824
ON_471823
ON_471822
ON_471821
ON_471820
ON_471819
ON_471714
ON_471715
ON_471716
ON_471717
ON_471718

**Comment by sifavahora** [comment]
HI @GH-Emily. Sure we will do that. We are starting to maintain logs for data changes in the portal. Could you please also mention the reason for this request and future requests? Thanks.

**Comment by GH-Emily** [comment]
You bet! 

This was requested by Ontario due to data quality concerns.

**Comment by edsu7** [comment]
The 128 analyses list above have been suppressed. As an example:
```
  "samples": [
      "submitterSampleId": "ON_471714",
],
  "analysisStateHistory": [
    {
      "initialState": "UNPUBLISHED",
      "updatedState": "PUBLISHED",
      "updatedAt": "2022-08-02T23:55:12.809053"
    },
    {
      "initialState": "PUBLISHED",
      "updatedState": "UNPUBLISHED",
      "updatedAt": "2022-08-16T13:59:33.528586"
    },
    {
      "initialState": "UNPUBLISHED",
      "updatedState": "SUPPRESSED",
      "updatedAt": "2022-08-16T14:00:31.022917"
    }
  ]
```
