### ISSUE TITLE
update gisaid accession -QC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#318]
Hi there @sifavahora,

Could you please update the gisaid accession for the sample- `QC_300592` to `EPI_ISL_2293776` ?

Thanks,
Chanchal

**Comment by edsu7** [comment]
`QC_300592`'s `gisaid_accession` has been updated from:
```
"submitterSampleId": "QC_300592",
 "database_identifiers": {
    "gisaid_accession": "EPI_ISL_7713672"
  },
```
to
```
"submitterSampleId": "QC_300592",
 "database_identifiers": {
    "gisaid_accession": "EPI_ISL_2293776"
  },
```

**Comment by ChanchalYa** [comment]
Thanks very much @edsu7 @sifavahora !
