### ISSUE TITLE
Add Download All and disable logic for download options

### ISSUE THREAD

**Issue by akachru-github** [cancogen-virus-seq/portal#32]
- DOWNLOAD ALL will be in the header, a pill,  this will appear along the navigation bar on the landing page. 
- Grey out other download options if no rows selected. Disable the dropdown, OR disable the options are both acceptable approaches.

**Comment by caravinci** [comment]
Modified Arranger to allow disabling individual exporters on a piecemeal basis, if they require rows being selected.
Added the "Download All" at the end of the menu, as per Christina's input; still pending the final URL to be used upon release.

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/627a5300-0361-4eac-bcb5-d4e2e2ec07bc)

Deployed to dev for initial testing of edge cases, and will be updated once the URL is provided.

**Comment by rosibaj** [comment]
@caravinci UI looks good for this for now - you are blocked by https://github.com/cancogen-virus-seq/roadmap/issues/10 
- moving this to in-progress and `blocked` until we can get that link.
