### ISSUE TITLE
update collection dates- border samples

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#320]
Hi there @sifavahora,

Could you please update the `sample collection date` for the list of samples attached here?

Thanks,
Chanchal

[Collection_Date_Updates_VirusSeq_20220818.csv](https://github.com/cancogen-virus-seq/portal/files/9377226/Collection_Date_Updates_VirusSeq_20220818.csv)

**Comment by edsu7** [comment]
Collection date for the listed 28 samples have been updated.

See below for an example -
From:
```
"submitterSpecimenId": "UN-319462",
 "sample_collection_date": "2022-01-14",
```
Updated to :
```
"submitterSpecimenId": "UN-319462",
"sample_collection_date": "2022-01-08",
```

**Comment by ChanchalYa** [comment]
Thanks very much @edsu7 @sifavahora !
