### ISSUE TITLE
ON - Reason for sequencing updates

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#322]
Hi @sifavahora,

Could you please update the attached samples? Additional information was provided by PHO. 

[NML_PHO_reasons_for_sequencing_retrospective_2022-05-02_final_dpUpdate.csv](https://github.com/cancogen-virus-seq/portal/files/9385457/NML_PHO_reasons_for_sequencing_retrospective_2022-05-02_final_dpUpdate.csv)

**Comment by edsu7** [comment]
Hi @GH-Emily,

The field `purpose_of_sequencing` in our schema is now a list.

Below is an example of the requested changed:
|studyId|analysisId|submitterDonorId|old purpose_of_sequencing|new purpose_of_sequencing|
|--|--|--|--|--|
|PHO-ON|ec72df13-984f-4ad5-b2df-13984ffad587|ON_80757|International travel surveillance'|Targeted surveillance (non-random sampling)'|

I would like to clarify that you want to replace the older value and not append the new value to the the "list".

Cheers,
Edmund

**Comment by GH-Emily** [comment]
Hi @edsu7 

I have attached a **new** update file. It now lists information in the purpose_of_Sequencing field as a list rather than splitting the two values into purpose_of_Sequencing and purpose_of_sequencing_details. Everything in the new file should **overwrite** the current values, rather than being concatenated with the existing value. 

If there is an existing value in the field purpose_of_sequencing_details and my file has a null value, please over write the existing value with the null. 

[NML_PHO_reasons_for_sequencing_retrospective_2022-05-02_final_dpUpdate.csv](https://github.com/cancogen-virus-seq/portal/files/9620682/NML_PHO_reasons_for_sequencing_retrospective_2022-05-02_final_dpUpdate.csv)

Emily

**Comment by edsu7** [comment]
57569/57570 samples have had their `purpose_of_sequencing` and `purpose_of_sequencing_details` updated. 

The odd sample `ON_388855` was previously suppressed https://github.com/cancogen-virus-seq/portal/issues/321

![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/11bd0c90-9cb2-4a33-b257-4e2b75e39338)

**Comment by sifavahora** [comment]
@GH-Emily please close this if applicable.

**Comment by GH-Emily** [comment]
thank you
