### ISSUE TITLE
BC - Reason for Sequencing Updates

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#325]
Hi @sifavahora,

Could you please update the reason for sequencing for the attached samples? BC has provided corrected information. 

Thank you, 
Emily

[2022-09-01_BC_DP_Updates.csv](https://github.com/cancogen-virus-seq/portal/files/9472837/2022-09-01_BC_DP_Updates.csv)

**Comment by edsu7** [comment]
Updates have been applied to the above 241 samples' `purpose_of_sequencing`.

The following is an example of update:
```
"submitterDonorId": "BC_328819",
"purpose_of_sequencing": "Baseline surveillance (random sampling)"
```
Updated to
```
"submitterDonorId": "BC_328819",
"purpose_of_sequencing": "Surveillance of international border crossing by air travel"
```

**Comment by sifavahora** [comment]
Hi @GH-Emily can you please close this ticket if applicable. Thanks

**Comment by GH-Emily** [comment]
thanks!

**Comment by GH-Emily** [comment]
@sifavahora 

I've made a mistake in this request. I'm wondering if you could please update 

"submitterDonorId": "BC_328819",

to 

"purpose_of_sequencing": "Targeted surveillance (non-random sampling)"

**Comment by GH-Emily** [comment]
@sifavahora 

I've made an error in this request (sorry!). 

I'm wondering if you could please update the samples according to the updated file I've attached to this comment? 

[2022-09-01_BC_DP_Updates.csv](https://github.com/cancogen-virus-seq/portal/files/9872271/2022-09-01_BC_DP_Updates.csv)

thank you!

**Comment by edsu7** [comment]
Updated 241 samples
before:
![Screen Shot 2022-10-27 at 2.29.33 PM.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/1a435f85-7424-4a26-ba20-9da5c18b6245)
after:
![Screen Shot 2022-10-27 at 2.41.16 PM.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/64e74c02-9372-4f83-bb37-b05320d46a31)

**Comment by GH-Emily** [comment]
thank you so much!
