### ISSUE TITLE
Switch endpoints to request totalcounts

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#327]
Currently this is fetched from singularity. 
We are creating an endpoint to fetch this from the API. 

For reference - https://github.com/cancogen-virus-seq/api/issues/9

**Comment by scottcain** [comment]
@leoraba  & @caravinci 

I have a feeling this is done; can this be closed?

**Comment by caravinci** [comment]
Good question! I completed this along with the release changelogs.
Pretty sure it's safe to close this ticket now
