### ISSUE TITLE
Update metadata for Lineage fields and observe system reaction

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#328]
The Current schema [https://github.com/cancogen-virus-seq/metadata-schemas/blob/main/schemas/consensus_sequence.json#L1283] contains some of the Lineage Analysis fields. The goal of this ticket is to update the values in the field and observe how the system reacts to them. 

Following are some of points test cases to focus: 

- [x] Does Song successfully update the data? 
- [x] Does ES Index get updated automatically when lineage fields have value? 
- [x] Does it require manual trigger for Maestro to update the ES index.

**Comment by sifavahora** [comment]
Updated metadata added metadata for samples with `analysis_version < 13`  
Steps: 
Unpublish, Update, Publish analysis. 
Observation: the ES get re-indexed itself. no error due to schema or added lineage values
reference analysis_id: `02e1979c-30cf-48c4-a197-9c30cf48c46e`
additional note : this update only works for data uploaded on the `dev` portal , this update doesnt work for the mass dump from `prod` done in July . Gives `object not found error`

**Comment by scottcain** [comment]
@leoraba this can be closed too, right?

**Comment by leoraba** [comment]
Maestro version 4.3.0 implements an "upsert" ES script to get re-indexed on any update.
