### ISSUE TITLE
Update Policies, Home Page & Team Page with the latest text

### ISSUE THREAD

**Issue by christinayung** [cancogen-virus-seq/portal#33]
Policy Page Update: https://docs.google.com/document/d/1xHX7UGcPTv91cN9aNe4Y6-s7m7oE9TBuP-jpEGXWekE/edit?usp=sharing

**Comment by rosibaj** [comment]
Via slack: 

Policies:
 `Data Submitters guidelines` --> `Data Submitters Guidelines`
 `Sensitive and or Identifiable Data` --> `Sensitive or Identifiable Data`

**Comment by rosibaj** [comment]
looks great thank you @caravinci !
