### ISSUE TITLE
Suppress samples- QC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#331]
Hi there @sifavahora,

Could you please suppress these samples (attached) in VirusSeq? These were submitted twice, resulting in duplicate copies.

Thanks,
Chanchal
[QC_samples_to_suppress_VirusSeq_20220920.csv](https://github.com/cancogen-virus-seq/portal/files/9608557/QC_samples_to_suppress_VirusSeq_20220920.csv)

**Comment by edsu7** [comment]
Hi @ChanchalYa ,

Were these duplicates submitted under the same `specimen_collect_sample_id` or different?

**Comment by ChanchalYa** [comment]
Hi @edsu7 ,

These were submitted under different `specimen_collector_sample_id`

**Comment by edsu7** [comment]
56 samples have suppressed.

Example below: 
```
  "analysisStateHistory": [
    {
      "initialState": "UNPUBLISHED",
      "updatedState": "PUBLISHED",
      "updatedAt": "2022-08-30T16:58:09.367691"
    },
    {
      "initialState": "PUBLISHED",
      "updatedState": "SUPPRESSED",
      "updatedAt": "2022-09-20T19:06:14.983656"
    }
],
      "submitterSampleId": "QC_497203",
```

The following `specimen_collector_sample_id` did not have analyses
```
QC_497201
QC_497204
QC_497249
QC_497335
```

**Comment by ChanchalYa** [comment]
thanks @edsu7

**Comment by edsu7** [comment]
```
QC_497201
QC_497204
QC_497249
QC_497335
```

have been located and suppressed.

```
{
  "analysisId": "1a272f71-08b6-4fd6-a72f-7108b6dfd6b0",
  "studyId": "LSPQ-QC",
  "analysisState": "SUPPRESSED",
      "donor": {
        "studyId": "LSPQ-QC",
        "submitterDonorId": "QC_497249"
  ```

**Comment by ChanchalYa** [comment]
Thanks very much @edsu7
