### ISSUE TITLE
Samples not Indexed in the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#334]
Hi @sifavahora, for the BC upload 10 samples were not indexed on the portal. I have included the specimen collector ID and analysis ID. Please have a look and let me know if I have to re-upload these samples. Thanks!
[New Microsoft Excel Worksheet.xlsx](https://github.com/cancogen-virus-seq/portal/files/9669276/New.Microsoft.Excel.Worksheet.xlsx)

**Comment by sifavahora** [comment]
@edsu7  as a first step can you please check if these samples exist in Song. I am guessing it is the analysis_state issue

**Comment by edsu7** [comment]
Hi @nithujohn,

I've republished them and that's successfully indexed them onto the portal:

- Before of `BC_482670`:
<img width="1341" alt="Screen Shot 2022-09-29 at 7 45 18 AM" src="https://user-images.githubusercontent.com/22638361/193026527-c6fbf382-c89f-437e-a31d-1db652f4eb35.png">
- After:
<img width="1220" alt="Screen Shot 2022-09-29 at 7 46 23 AM" src="https://user-images.githubusercontent.com/22638361/193026628-82810ce3-0836-480b-822a-a8acd75a7084.png">

**Comment by nithujohn** [comment]
Thank you so much @edsu7 @sifavahora :)
