### ISSUE TITLE
Sample Removal - ON

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#336]
Hi @sifavahora! 

Could you please remove the following samples from VirusSeq? They have incorrect GISAID information.

ON_67726
ON_67317
ON_67549
ON_67727
ON_67547
ON_66993

Thank you, 
Emily

**Comment by edsu7** [comment]
The following samples have been suppressed.
```
ON_67726
ON_67317
ON_67549
ON_67727
ON_67547
ON_66993
```

See below for an example:
```
{
  "studyId": "PHO-ON",
  "analysisState": "SUPPRESSED",
  "samples": [
    {"submitterSampleId": "ON_66993"}
]
}
```

**Comment by GH-Emily** [comment]
thank you!
