### ISSUE TITLE
BC - Sample Metadata Update

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#337]
Hi @sifavahora!

Could you please update the attached samples to have purpose of sequencing: 

Targeted surveillance (non-random sampling)

[2022-10-14_Issue322_DPupdate.txt](https://github.com/cancogen-virus-seq/portal/files/9789840/2022-10-14_Issue322_DPupdate.txt)

Thank you! 
Emily

**Comment by edsu7** [comment]
The following sample IDs were not found:
```
BC_482282
BC_481840
BC_481862
```

Everything else has been updated to `Targeted surveillance (non-random sampling)` .Please see below

![Screen Shot 2022-10-17 at 1.19.46 PM.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/51539433-2212-44c6-ac3c-f27cc3098646)

**Comment by GH-Emily** [comment]
thank you!
