### ISSUE TITLE
NS & QC - Data Clean up

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#340]
Hi @sifavahora!

Could you please update sample NS_460278 to have age and age bin "Unknown" the previous data submitted was incorrect. 

Could you also please update sample QC_443886 to have age 30 and age bin 30 - 39 

AND 

QC_478265 to have age 52 and age bin 50 - 59? 

Thank you! 
Emily

**Comment by edsu7** [comment]
Hi @GH-Emily 
Regarding `NS_460278` currently the age is `null`. For `host_age_bin` `unknown` is not a valid option. Instead we have the following options :
```
"Not Applicable",
"Missing",
"Not Collected",
"Not Provided",
"Restricted Access"
```

**Comment by edsu7** [comment]
`QC_443886` and `QC_478265` have been updated
![image](https://user-images.githubusercontent.com/22638361/197580934-2dcfdfd8-fb23-44c6-bfe0-80933b1069bd.png)
![image](https://user-images.githubusercontent.com/22638361/197581141-269920ef-4f71-4155-83b9-3a62568555cd.png)

**Comment by GH-Emily** [comment]
> Hi @GH-Emily Regarding `NS_460278` currently the age is `null`. For `host_age_bin` `unknown` is not a valid option. Instead we have the following options :
> 
> ```
> "Not Applicable",
> "Missing",
> "Not Collected",
> "Not Provided",
> "Restricted Access"
> ```

Could you please update to "Not Provided"?

**Comment by edsu7** [comment]
Last one - `NS_460278`'s age is now `null` and `age_bin` `Not Applicable`

![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/c0050035-cba7-45ce-ad13-49333d2fee95)

**Comment by GH-Emily** [comment]
thank you!
