### ISSUE TITLE
[Design] Add a timeline graph of cases on the Explorer Page 

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#344]
GOAL : Help users we visualize how data has grown in the portal over the time. The timeline unit could be month, quarter etc. dynamic based on the span of time selected.  

Current Explorer Page : https://virusseq-dataportal.ca/
Timeline could be by Submission Date or Sample Collection Date 

Expected Outcomes: 
How and where to place this graph(widget) on the explorer page and the Data Release page.

**Comment by patrickdsantos** [comment]
Hey Sifa! 

I've uploaded to the prototype to InVision. Check it out: https://invis.io/JX133CO3658M#/470870479_VirusSeq-Visualize-Dashboard-3Graphs

I'll book some time for us this week to go through it and get feedback :)
