### ISSUE TITLE
Suppress samples- border

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#345]
Hi @sifavahora,

Could you please suppress the attached list of samples in the portal? 

Thanks,
Chanchal
[Samples_to_suppress_VirusSeq_20221114.xlsx](https://github.com/cancogen-virus-seq/portal/files/10006294/Samples_to_suppress_VirusSeq_20221114.xlsx)

**Comment by edsu7** [comment]
Samples have been suppressed. 

Example:
```
{
  "studyId": "COVID-CAN",
  "analysisState": "SUPPRESSED",
  "samples": [
    {
      "submitterSampleId": "UN-446623",
}
]
```

Cheers,
Edmund

**Comment by ChanchalYa** [comment]
Thanks very much @edsu7 !


Chanchal
