### ISSUE TITLE
Data Clean up - ON Samples

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#346]
Hi @sifavahora, 

Ontario has provided purpose of sequencing for some samples. I'm wondering if you could please update these? 

[2022-11-17_Issue375_missing_DPUpdate.csv](https://github.com/cancogen-virus-seq/portal/files/10032814/2022-11-17_Issue375_missing_DPUpdate.csv)

Thanks! 
Emily

**Comment by edsu7** [comment]
1658 samples have had their `purpose_of_sequencing` updated.

Below is an example.

Previous:
![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/5620b8a8-95ed-4ce7-99a6-66267bd2a793)

Updated:
![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/bb1fa225-e83b-492b-9e06-1cb2998c234b)

Cheers,
Edmund
