### ISSUE TITLE
Metadata update- Border samples

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#347]
Hi @sifavahora,

Could you please update the collection dates for `UN-469585`  and  `UN-469586`  to `2022-07-13`  in the portal?

Thanks,
Chanchal

**Comment by edsu7** [comment]
`UN-469585` and `UN-469586` collection dates have been updated.

Before:
![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/307906c4-8eef-46ae-b252-c6d7ec141922)
After:
![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/30f91db0-35c9-4683-a993-7f7b75ba37ed)

**Comment by ChanchalYa** [comment]
Thanks @edsu7 !

Chanchal
