### ISSUE TITLE
Suppress samples- ON

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#348]
Hi @sifavahora,

Could you please suppress the ON samples (attached) in the portal?

Thanks,
Chanchal
[ON_samples_to_suppress_VirusSeq_20221125.xlsx](https://github.com/cancogen-virus-seq/portal/files/10093632/ON_samples_to_suppress_VirusSeq_20221125.xlsx)

**Comment by edsu7** [comment]
63 samples have been suppressed.

Below is an example:
```
{
  "analysisId": "0318294d-b40e-4276-9829-4db40e6276e2",
  "studyId": "PHO-ON",
  "analysisState": "SUPPRESSED",
  "samples": [
    {
      "submitterSampleId": "ON_97612",
}]}
```

**Comment by ChanchalYa** [comment]
Thanks @edsu7 !


Chanchal
