### ISSUE TITLE
Update Submission instructions

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#35]
On the submission UI Dashboard, these instructions are wrong:

![image](https://user-images.githubusercontent.com/15824252/116137082-1bb93480-a6a1-11eb-8e9c-63657af67bfd.png)

### Change the instructions to this blurb: 

Virus metadata is submitted as a .tsv file.  Viral genome data must be submitted as a `.fasta` file. Up to 5000 samples can be submitted in a single submission, but note that the larger the file the longer the submission will take.  Fasta files are accepted individually, or as a single concatenated fasta containing all samples in one file. 

To format your viral sequence metadata: 
- Sequence metadata must be provided in TSV format according to the accepted values for each field.  A reference of the accepted values can be found [in this resource](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/blob/master/template/canada_covid19/SOP.pdf). 
- [DataHarmonizer](https://github.com/Public-Health-Bioinformatics/DataHarmonizer) is a tool that can be used to help validate your metadata TSV locally before submitting.  Download the tool and follow the instructions on the Github repository to pre-validate your metadata before submission. 
- If you are using Excel or Google sheets, make sure all characters are UTF-8 encoded. 

To format your viral sequence files: 
- Make sure they have the file extension `.fasta`.
- Each sequence **must** be preceded be a description line, beginning with a `>`.  The description line should include >hCoV-19/`country`/`identifier`/`year sequenced`.  This identifier **must match exactly** the "Isolate" column in the TSV file.

### Links: 
no1: https://github.com/Public-Health-Bioinformatics/DataHarmonizer/blob/master/template/canada_covid19/SOP.pdf 
no2: https://github.com/Public-Health-Bioinformatics/DataHarmonizer

**Comment by rosibaj** [comment]
verified on prod: 

![image](https://user-images.githubusercontent.com/15824252/116158359-87f56180-a6bc-11eb-8850-7f92357a6610.png)

**Comment by caravinci** [comment]
Ooops. CopyPasta!
