### ISSUE TITLE
Sample Removal - Border 

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#354]
Hi @edsu7

Could you please remove sample UN-62272 from the data portal? There are issues with the metadata. 

Thank you, 
Emily

**Comment by edsu7** [comment]
`UN-62272` has been suppressed.

Before:
![Screen Shot 2023-01-03 at 10 18 27 AM](https://user-images.githubusercontent.com/22638361/210387026-9816ccfc-6460-42a4-b4bb-15609a495891.png)

After:
![Screen Shot 2023-01-03 at 10 20 29 AM](https://user-images.githubusercontent.com/22638361/210387084-6eea7fce-cb03-48e3-8b59-a7a215b703b2.png)

Cheers,
Edmund
