### ISSUE TITLE
AB duplicates

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#357]
Hi @scottcain I have accidentally uploaded the same datasets which resulted in duplicates. Can you please suppress them from the portal. Apologies for the error! Thanks Nithu
[AB.txt](https://github.com/cancogen-virus-seq/portal/files/10375687/AB.txt)

**Comment by edsu7** [comment]
the `459` samples list have had their latest analyses suppressed.

Original:
![Screen Shot 2023-01-09 at 2 03 01 PM](https://user-images.githubusercontent.com/22638361/211394270-43170df8-8994-4ed6-84ad-74441a13a404.png)
Updated (showing 459 difference):
![Screen Shot 2023-01-09 at 2 40 09 PM](https://user-images.githubusercontent.com/22638361/211394330-08e0e5aa-1cf8-4190-aba0-55a40371afd8.png)

Original of a random sample:
 ![Screen Shot 2023-01-09 at 2 05 07 PM](https://user-images.githubusercontent.com/22638361/211394408-f20cf1c7-c58d-4200-9e3d-f80cc8399d1b.png)
 
 Updated:
![Screen Shot 2023-01-09 at 2 42 13 PM](https://user-images.githubusercontent.com/22638361/211394453-b5ade7d8-72d5-48f3-8692-c8a45adc65e3.png)

Cheers,
Edmund

**Comment by nithujohn** [comment]
Thank you so much ! @edsu7
