### ISSUE TITLE
Samples not indexing on the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#359]
Hi @scottcain I have done uploads with the below mentioned data providers but looks like half of the samples indexed.

AB- 365 out of 619 indexed (Data Submission: 32badd5e-c8ce-43de-93ae-2548e6209a36)
QC- 746 out of 1290 indexed (Data Submission: 1adccd34-d415-48b3-baf2-e2919858cba5)
PHO- 1461 out of 2475 indexed (Data Submission: 50ca2bab-c996-44b1-b99d-3e960d657214)
NS- 46 out of 71 (Data Submission: c984b329-4f5c-43b7-ad5b-bde88c63f5ac)
NL- 32 out of 48 (Data Submission: 315a08d2-81af-4255-9278-a446b0773c3d)
NB- 102 out of 169 (Data Submission: 32c570f7-ce4a-42a9-8c07-6ad94b41146c)

Please have a look and let me know any info needed. Thanks!

**Comment by scottcain** [comment]
Hi @nithujohn Would it be possible to get a list of failed analysis IDs?

**Comment by nithujohn** [comment]
All the samples has completed the analysis it's only the indexing part I would say left. From the submission UI I won't be able to find which samples are indexed as all the samples has processed. But let me see I can filter them from indexed samples on the portal but it might take some time as well

**Comment by nithujohn** [comment]
[NB.txt](https://github.com/cancogen-virus-seq/portal/files/10483924/NB.txt)
[NS.txt](https://github.com/cancogen-virus-seq/portal/files/10483925/NS.txt)
[NL.txt](https://github.com/cancogen-virus-seq/portal/files/10483928/NL.txt)

Here is the maritime provinces not indexed samples analysis IDs

**Comment by nithujohn** [comment]
[QC.txt](https://github.com/cancogen-virus-seq/portal/files/10484200/QC.txt)
[AB.txt](https://github.com/cancogen-virus-seq/portal/files/10484201/AB.txt)
AB and QC failed samples analysis ID

**Comment by edsu7** [comment]
Hi @nithujohn,

I checked the IDs you listed in https://github.com/cancogen-virus-seq/portal/issues/359#issuecomment-1401049772 and https://github.com/cancogen-virus-seq/portal/issues/359#issuecomment-1401107786, all were present on the portal.

Additionally from https://github.com/cancogen-virus-seq/portal/issues/359#issue-1553780481, you uploaded `4672` analyses which is matching the portal count when queried for `PHO-ON`,`ABPL-AB`,`EH-NL`,`VHN-NB`,`NSHA-NS`,`LSPQ-QC` on `2023/01/22`-`2023/01/24`
![image](https://user-images.githubusercontent.com/22638361/214330414-1c85cb59-4c84-4412-8713-3edbdcd9a467.png)

Could you please re-confirm?

**Comment by nithujohn** [comment]
Hi @edsu7 , I just checked and the samples are indexed on the portal. Yesterday till 5 pm PST it was not indexed on the portal looks like indexed late in the evening. Thank you so much for checking the IDs.
