### ISSUE TITLE
QC duplicate sample

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#360]
Hi @edsu7 , there is a duplicate sample in the portal. Can you please delete one of them from the portal?
Thanks!

hCoV-19/Canada/QC-L00571075001/2022

**Comment by edsu7** [comment]
Hi @nithujohn , just wanted to confirm that the `Specimen Collect Sample ID` for the duplicate is `QC_576471`?

**Comment by nithujohn** [comment]
Yea, the sample collector ID is QC_576471

**Comment by edsu7** [comment]
A duplicate of `QC_576471` has been suppressed.

Previously:
![image](https://user-images.githubusercontent.com/22638361/214372686-3b257656-9593-43a0-8e93-cd58008ca180.png)
Current:
![image](https://user-images.githubusercontent.com/22638361/214375039-2481edcb-3b61-4946-a592-24caf52d6dd7.png)

Cheers.
Edmund

**Comment by nithujohn** [comment]
Thank you so much!
