### ISSUE TITLE
Data update on the portal

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#361]
Hi @edsu7 in a random check I just saw three errors for consensus sequence software version listed below. Can you please update the below IDs. Thanks!
NB_324452       130.00% to 1.3
NB_322234        130%     to 1.3
NB_323126        130.00%  to 1.3

Let me know if you have questions.

**Comment by edsu7** [comment]
Samples `NB_324452`,`NB_322234`,`NB_323126` have been updated.

Before:
![image](https://user-images.githubusercontent.com/22638361/214605498-297bd0f2-0ca1-43b0-841c-55afa28adb24.png)
After:
![image](https://user-images.githubusercontent.com/22638361/214607661-fa33619c-c165-49f3-9e1e-3a74471b4d16.png)
![image](https://user-images.githubusercontent.com/22638361/214610165-6cb585ea-7282-41d9-b085-9152226e09b5.png)
![image](https://user-images.githubusercontent.com/22638361/214610589-30ac3f09-6000-4f62-92ea-575b1eaa0860.png)

**Comment by nithujohn** [comment]
Thank you so much!
