### ISSUE TITLE
Make looking for columns easier in explorer

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#363]
In ‘Columns’ selector, sort columns names by alphabetical order to make them easier to find as number of columns as gone up, or auto-complete

**Comment by scottcain** [comment]
Rather than changing the current sorting (not that I know they are sorted in any rational way), perhaps just adding an autocomplete filter at the top of the box would be sufficient. I'd rather not capriciously change the ordering since users who use this are presumably used to the current order.

**Comment by leoraba** [comment]
Added a search filter in the 'Columns' component. It facilitates the search and highlights the text inserted
![image](https://github.com/cancogen-virus-seq/portal/assets/9260184/41833830-84c5-41e3-a64d-25cb1d72ce94)
