### ISSUE TITLE
Metadata updates- border samples

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#364]
Hi @edsu7,

Could you please update the `sample collection date`  in the portal for the list of samples attached?

Thanks,
Chanchal
[Collection_date_updates_VirusSeq_20230131.xlsx](https://github.com/cancogen-virus-seq/portal/files/10557725/Collection_date_updates_VirusSeq_20230131.xlsx)

**Comment by edsu7** [comment]
Hi @ChanchalYa ,

81 values have had their `sample collection date` updated. Example below.

Before:
![image](https://user-images.githubusercontent.com/22638361/216333655-693ff4a5-a989-4a87-8655-06800e50839c.png)

After:
![image](https://user-images.githubusercontent.com/22638361/216337272-df494e33-0edf-496b-aa4a-5220da3a4461.png)

Cheers,
Edmund

**Comment by ChanchalYa** [comment]
Thanks very much @edsu7 !
