### ISSUE TITLE
Metadata update- BC

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#367]
Hi @edsu7, Can you please update the sample collection date and virus name change for the below sample from BC? Thanks :)

BC_422751     hCoV-19/Canada/BC-BCCDC-422751/2020       2020-04-14 currently in the portal change to
 
hCoV-19/Canada/BC-BCCDC-422751/2022         2022-04-14

**Comment by edsu7** [comment]
Sample `BC_422751`'s `sample collection date` and `fasta header` has been updated. I also took the liberty of updating `isolate` as well.

Before:
![image](https://user-images.githubusercontent.com/22638361/218867977-6532a77a-3886-4fa2-b2d5-bd6e3683cba5.png)
After:
![image](https://user-images.githubusercontent.com/22638361/218869033-ad864ffa-a882-4517-8536-a08815512adf.png)

Cheers,
Edmund

**Comment by nithujohn** [comment]
Thank you so much @scottcain @edsu7 !
