### ISSUE TITLE
Possible data sync issue

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#369]
In the Feb 16 release, there is a metadata entry for a sequence called `hCoV-19/Canada/BC-BCCDC-422751/2022` but this ID isn't present in the fasta file for the release. Instead, there is a sequence with the ID `hCoV-19/Canada/BC-BCCDC-422751/2020` (notice "2" versus "0" in the last character of the IDs). 

This issue is almost certainly related to https://github.com/cancogen-virus-seq/portal/issues/367 where this sequence was updated. Was the update only "partial"?

**Comment by edsu7** [comment]
Sorry about that, when I updated the `fasta header` neglected to also update in the actual file.
Old analysis `cc73d9f7-190b-4148-b3d9-f7190b2148ef` has been suppressed.
New analysis `a9dd07ac-8253-4e98-9d07-ac82539e9815` was reuploaded with the correct fasta header and lineage info added back in.

**Comment by scottcain** [comment]
And it should be available on viral AI later today.
