### ISSUE TITLE
Homepage and team page wording change.

### ISSUE THREAD

**Issue by kcullion** [cancogen-virus-seq/portal#37]
For transparency let's change the wording to this

`Genome Canada has also partnered with DNAstack to integrate VirusSeq data with their COVID Cloud Platform. COVID Cloud is a cloud-based platform that helps researchers find, visualize, and analyze genomics and other datasets related to COVID-19.`

in these two spots

- [x] homepage
![image](https://user-images.githubusercontent.com/18424138/116291256-5e8f1100-a762-11eb-9ea3-8a6b9764a05e.png)

- [x] Meet the team page
![image](https://user-images.githubusercontent.com/18424138/116291632-ce9d9700-a762-11eb-91f6-d66cbe510242.png)

**Comment by rosibaj** [comment]
@kcullion i cant quite see the difference here - is this done?

**Comment by kcullion** [comment]
@rosibaj no it's not. But maybe it's not accurate anymore?
Instead of saying `Genome Canada has partnered with DNAstack to integrate COVID Cloud with the Canadian VirusSeq Data Portal` which seems to me like it's saying the two portals are linked in some way...I thought we could say
`Genome Canada has also partnered with DNAstack to integrate VirusSeq data with their COVID Cloud Platform`

**Comment by rosibaj** [comment]
confirmed on prod
