### ISSUE TITLE
BC - Virus Name and Collection Date Update

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#370]
@edsu7

Possibly linked to #369  

We'd like to request that virus name hCoV-19/Canada/BC-BCCDC-422751/2020 be re-named to hCoV-19/Canada/BC-BCCDC-422751/2022 and that collection date be updated to 2022-04-14. Specimen collector sample ID should be BC_422751

Thanks!

**Comment by GH-Emily** [comment]
my request can be ignored as it was resolved in: 

https://github.com/cancogen-virus-seq/portal/issues/367

However, it appears that this update is not visible in ViralAI yet

**Comment by scottcain** [comment]
I believe they do updates on Tuesday and Friday, so it should be available today some time.
