### ISSUE TITLE
Metadata update- AB

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#371]
Hi @edsu7 ,

Could you please update the `fasta header` and `isolate` for AB_586456 to **hCoV-19/Canada/AB-ABPHL-91632/2022** ?

Thanks,
Chanchal

**Comment by edsu7** [comment]
Double checking. The current header is `hCoV-19/CANADA/AB-ABPHL-91632/2022` and the change you want to apply is from `CANADA` to `Canada`?

**Comment by ChanchalYa** [comment]
yes, just the case change from `CANADA` to `Canada`.

Thanks

**Comment by edsu7** [comment]
Analysis was resubmitted with the correct `isolate`,`fasta header` and fasta file under `12db3bcf-b20f-4ac1-9b3b-cfb20f7ac11d`. Old analysis `1082226f-4053-4142-8222-6f4053a14289` was suppressed.
Before:
![image](https://user-images.githubusercontent.com/22638361/220710880-a3706f9e-e7b3-4704-b4b2-e0b27466c68c.png)
After:
![image](https://user-images.githubusercontent.com/22638361/220710849-c56c8b03-28fc-49e2-8242-59a95490014a.png)

Cheers,
Edmund

**Comment by ChanchalYa** [comment]
thanks @edsu7 !


Chanchal

**Comment by ChanchalYa** [comment]
Hi again @edsu7 ,
It seems that both the earlier and fixed `isolate` copies are present in viral ai for this sample-

![image](https://user-images.githubusercontent.com/99286178/222468793-1cd58ccb-246f-465f-9b1d-6cd48628bad5.png)

**Comment by edsu7** [comment]
Hi @ChanchalYa,

Since I had to edit the file contents, it was easier to resubmit as a new sample entirely and suppress the old. In the case of Viral AI, someone on their end will have to remove the redundant sample.

The sample found in https://github.com/cancogen-virus-seq/portal/issues/370 should also have the same issue.

Cheers,
Edmund

**Comment by ChanchalYa** [comment]
Thanks @edsu7!
