### ISSUE TITLE
Meta Data Update - Testing Protocol 

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#373]
[2023_03_03_Testing_protocol_update.csv](https://github.com/cancogen-virus-seq/portal/files/10885529/2023_03_03_Testing_protocol_update.csv)
Hi @edsu7 the following samples in the above csv file need to have the changes made in the "Testing protocol" field in the data portal. 

Please feel free to reach out if you have any questions or concerns. 

Thanks!

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier,
Is there another identifier you can provide for  `R3400366747` and `R3470345661`, like a `specimen collector sample ID`?

e.g.:
```
QC_224343       hCoV-19/Canada/QC-L00376257001/2021
ON_260876       hCoV-19/Canada/ON-PHL-21-40785/2021
```

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Hi @edsu7,

Sorry about that-I completely forgot to include that information. 

Please find it below:
BC_255516 
BC_77047

Kirsten

**Comment by edsu7** [comment]
@KirstenPalmier could you confirm the following is correct?

|SAMPLE.TEXT_ID|specimen collector sample ID|
|-|-|
|R3400366747|BC_255516|
|L00376257001|QC_224343 |
|R3470345661|BC_77047|
|ON-PHL-21-40785|ON_260876 |

Cheers,
Edmund

**Comment by GH-Emily** [comment]
> @KirstenPalmier could you confirm the following is correct?
> SAMPLE.TEXT_ID 	specimen collector sample ID
> R3400366747 	BC_255516
> L00376257001 	QC_224343
> R3470345661 	BC_77047
> ON-PHL-21-40785 	ON_260876
> 
> Cheers, Edmund

Hi there, 

Changes requested listed below! 


Specimen collector   sample ID | Testing Protocol
-- | --
BC_77047 | Viral sequencing was performed following a tiling amplicon strategy using   the 1.2 kb primer scheme by Freed et al., 2020 and an Illumina MiSeq   sequencing instrument. Libraries were prepared using Illumina DNA Prep kits.
QC_224343 | Viral sequencing was performed following a tiling amplicon strategy using   the 400 bp ARTIC v3 primer scheme. Sequencing was performed using an Oxford   Nanopore sequencing instrument.
BC_255516 | Viral sequencing was performed following a tiling amplicon strategy using   the 1.2 kb primer scheme by Freed et al. 2020
ON_260876 | Viral sequencing was performed following a tiling amplicon strategy using   the 400 bp ARTIC v3 primer scheme. Sequencing was performed using an Illumina   NextSeq 550 sequencing instrument.

**Comment by edsu7** [comment]
Hi @GH-Emily and @KirstenPalmier,

The four samples listed in the [ticket](https://github.com/cancogen-virus-seq/portal/issues/373#issuecomment-1461033374) had their `sequencing_protocol` updated.

Please note that `BC_77047` I didn't see a difference between the new `sequencing_protocol` and the old. I pushed the update through anyways.

I forgot to take screenshots of the before changes sorry!

Cheers,
Edmund

**Comment by GH-Emily** [comment]
> Hi @GH-Emily and @KirstenPalmier,
> 
> The four samples listed in the [ticket](https://github.com/cancogen-virus-seq/portal/issues/373#issuecomment-1461033374) had their `sequencing_protocol` updated.
> 
> Please note that `BC_77047` I didn't see a difference between the new `sequencing_protocol` and the old. I pushed the update through anyways.
> 
> I forgot to take screenshots of the before changes sorry!
> 
> Cheers, Edmund

thank you!!

**Comment by KirstenPalmier** [comment]
Hi @edsu7 and @GH-Emily 


Thank you!
