### ISSUE TITLE
Update Reason For Sequencing Details to "Not Provided" 

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#374]
Good morning @edsu7,

Can you please update the following samples in Data Portal?

Thank you. Please feel free to reach out if you have any comments or questions.

Kirsten 
[RFSD_update_DP_NS.csv](https://github.com/cancogen-virus-seq/portal/files/10981153/RFSD_update_DP_NS.csv)

**Comment by edsu7** [comment]
12 samples have had their `purpose_of_sequencing_details` updated

Before:
![image](https://user-images.githubusercontent.com/22638361/225416431-257d9680-658d-43ef-b173-8f4fb80f214a.png)

After:
![image](https://user-images.githubusercontent.com/22638361/225418398-95741684-a6f3-4dbe-b447-f51e7400222d.png)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you!
