### ISSUE TITLE
Update Dehosting Method for ON Samples

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#375]
Hi @edsu7,

Can you please update the Dehosting method for the following samples? 

Thank you. 
[Updated_dehosting_method_DP.csv](https://github.com/cancogen-virus-seq/portal/files/10982304/Updated_dehosting_method_DP.csv)

Please let me know if you require anything further. 

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier,
The samples listed in https://github.com/cancogen-virus-seq/portal/files/10982304/Updated_dehosting_method_DP.csv

Seem to already have the value `BWA v0.7.17`.

Below is an example:
![image](https://user-images.githubusercontent.com/22638361/225415526-aaf7eabc-b860-4914-8467-4b18dc1af93e.png)

Could you please reconfirm the updated value?

**Comment by KirstenPalmier** [comment]
Hi @edsu7 - Sorry about that. It must have only been an issue on our end. Thank you for confirming!

They can be left as is.

Thanks again!
