### ISSUE TITLE
Metadata update - AB

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#377]
Hi @edsu7,

Could you please update the `sequencing_protocol` for the samples attached?

Thanks,
Chanchal
[AB_sequencing_protocol_update_VirusSeq_20230328.csv](https://github.com/cancogen-virus-seq/portal/files/11093387/AB_sequencing_protocol_update_VirusSeq_20230328.csv)

**Comment by edsu7** [comment]
Done!

![image](https://user-images.githubusercontent.com/22638361/229573740-7b240194-c70b-43ea-a233-e6fdb980c6b4.png)

Cheers,
Edmund

**Comment by ChanchalYa** [comment]
Thank you very much @edsu7 !

Chanchal
