### ISSUE TITLE
Update metadata description on policies page

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#379]
On https://virusseq-dataportal.ca/policies, the `Contextual Metadata:` list should be updated with this:

Study id- a unique identifier for each data provider 
Specimen collector sample ID- a unique identifier for each sequenced specimen
GISAID accession- the GISAID accession number assigned to the sequence
Sample collected by- the name of the agency that collected the original sample
Sequence submitted by- the name of the agency that generated the sequence
Sample collection date- the date on which the sample was collected
Geo_loc_name (country)- the country where the sample was collected
Geo_loc_name (state/province/territory)- the province/territory where the sample was collected
Organism- Taxonomic name of the organism
Isolate- Identifier of the specific isolate
Fasta header name- fasta file identifier of the isolate 
Purpose of sampling- the reason that the sample was collected
Purpose of sampling details- the description of why the sample was collected, providing specific details
Anatomical material- A substance obtained from an anatomical part of an organism e.g. tissue, blood
Anatomical part- An anatomical part of an organism e.g. oropharynx
Body product- A substance excreted/secreted from an organism e.g. feces, urine, sweat
Environmental material- A substance obtained from the natural or man-made environment e.g. soil, water, sewage
Environmental site- An environmental location may describe a site in the natural or built environment e.g. metal can, hospital
Collection device- The instrument or container used to collect the sample e.g. swab
Collection method- The process used to collect the sample e.g. phlebotamy, necropsy
Host (scientific name)- The taxonomic, or scientific name of the host
Host disease- The name of the disease experienced by the host
Host age- Age of host at the time of sampling
Host age unit- The unit used to measure the host age, in either months or years
Host age bin- Age of host at the time of sampling, expressed as an age group
Host gender- The gender of the host at the time of sample collection
Purpose of sequencing- The reason that the sample was sequenced
Purpose of sequencing details- The description of why the sample was sequenced providing specific details
Sequencing instrument- The model of the sequencing instrument used
Sequencing protocol- The protocol used to generate the sequence
Raw sequence data processing method- The names of the software and version number used for raw data processing e.g. removing barcodes, filtering etc
Dehosting method- The method used to remove host reads from the pathogen sequence
Consensus sequence software name- The name of software used to generate the consensus sequence
Consensus sequence software version- The version of the software used to generate the consensus sequence
Breadth of coverage value- The percentage of the reference genome covered by the sequenced data, to a prescribed depth
Depth of coverage value- The average number of reads representing a given nucleotide in the reconstructed sequence
Reference genome accession- A persistent, unique identifier of a genome database entry
Bioinformatics protocol- A description of the overall bioinformatics strategy used
Gene name- The name of the gene used in the diagnostic RT-PCR test
Diagnostic_pcr_ct_value- The Ct value result from a diagnostic SARS-CoV-2 RT-PCR test
Lineage name- The name of the lineage assigned to a squenced sample
Lineage analysis software name- The name of the software used to determine the lineage
Lineage analysis software version- The version of the software used to determine the lineage
Lineage analysis software data version- A version number that represents both pangolin-data version number
Scorpio call- A software that performs snp-based calling of VOCs, mainly serious constellations of reoccurring phylogenetically-independent origin
Scorpio version- The version of scorpio software to determine the lineage

**Comment by justincorrigible** [comment]
Changes made and reviewable in dev at https://portal.dev.cancogen.cancercollaboratory.org/policies
Will promote to prod once reviewed/approved

**Comment by scottcain** [comment]
@justincorrigible Unfortunately, I can't see the dev site; want to post a screenshot?

**Comment by justincorrigible** [comment]
Here we go!
![policies](https://user-images.githubusercontent.com/2107110/232563725-47299c34-7682-4c26-9d51-2eeaaa5610e9.png)

**Comment by scottcain** [comment]
@justincorrigible Thanks! It can go into the next release in which it's convenient to put it.

**Comment by justincorrigible** [comment]
Changes deployed to prod. Please feel free to close the ticket upon validation 👍

**Comment by scottcain** [comment]
Thanks @justincorrigible
