### ISSUE TITLE
Metadata update- BC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#381]
Hi @edsu7!

Could you please update `GISAID Accession` in the portal for the list of BC samples attached here?

Thanks,
Chanchal
[BC_gisaid_accession_update_VirusSeq_20230420.csv](https://github.com/cancogen-virus-seq/portal/files/11289250/BC_gisaid_accession_update_VirusSeq_20230420.csv)

**Comment by edsu7** [comment]
Hey @ChanchalYa,

Samples have been updated:
![image](https://user-images.githubusercontent.com/22638361/233474238-948a0d5c-dd58-4553-be97-9e648c14c267.png)

Cheers,
Edmund

**Comment by ChanchalYa** [comment]
Thanks very much @edsu7 !

Cheers,
Chanchal
