### ISSUE TITLE
BC Seq Tech Update 

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#382]
Hi @edsu7,

Please find a csv with samples where the sequencing_instrument needs to be updated from Illumina NextSeq 2000 to Illumina MiSeq.

Please let me know if you have any questions,

Kirsten 
[BC_Seq_tech_update_ViralAI.csv](https://github.com/cancogen-virus-seq/portal/files/11299022/BC_Seq_tech_update_ViralAI.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier ,

`sequencing_instrument` for 16 samples have been updated to `Illumina MiSeq`

Before:
![Screen Shot 2023-04-28 at 12 01 33 PM](https://user-images.githubusercontent.com/22638361/235198881-fcf6e880-e251-46dd-a0b4-20c15afa349f.png)
After:
![Screen Shot 2023-04-28 at 12 07 49 PM](https://user-images.githubusercontent.com/22638361/235198901-0257ac8b-a3a3-4612-8ea1-7e83844010de.png)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thanks Edmond! 

Have a great weekend. 

Kirsten
