### ISSUE TITLE
Metadata update- AB

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#384]
Hi @edsu7,

Could you please update the `sample_collected_by` and `sequencing_submitted_by` to `Alberta Precision Labs (APL)` for all the Alberta samples to replace any existing `Alberta ProvLab North (APLN)` ? Our partners have requested this update.

Thank you,
Chanchal

**Comment by edsu7** [comment]
Hi @ChanchalYa,

All ABPL-AB samples have had their `sequencing_submitted_by` and `sample_collected_by` changed to `Alberta Precision Labs (APL)`

Before:
![Screen Shot 2023-04-26 at 6 13 28 PM](https://user-images.githubusercontent.com/22638361/234726691-afb00295-846d-453c-a019-465ccd995393.png)
After:
![Screen Shot 2023-04-26 at 7 55 05 PM](https://user-images.githubusercontent.com/22638361/234726692-d00fe4c7-fd1d-4b8d-a37f-cdc300a2ba19.png)

Cheers,
Edmund
