### ISSUE TITLE
Sample removal

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#385]
Hi @edsu7,

Can the following sample please be removed:
AB_51033

Thank you!

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier ,

`AB_51033` has been suppressed.

Before:
![Screen Shot 2023-05-05 at 3 00 51 PM](https://user-images.githubusercontent.com/22638361/236547868-a0cabe90-530b-43ba-b36a-f353259f6e9b.png)
After:
![Screen Shot 2023-05-05 at 3 04 08 PM](https://user-images.githubusercontent.com/22638361/236547893-9426e7bc-340d-4b02-8823-1464906940f9.png)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thanks Edmund!
Kirsten
