### ISSUE TITLE
Redaction request- MB

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#387]
Hi @edsu7,

Could you please redact/suppress the MB samples submitted on `2023-04-28` ? There were issues associated with many sequences in this batch, we will re-submit these samples in a future submission.

Thank you,
Chanchal

**Comment by edsu7** [comment]
Hi @ChanchalYa 

`179` samples have been suppressed. 

Here's a record of samples that were suppressed:
[suppressed.txt](https://github.com/cancogen-virus-seq/portal/files/11456296/suppressed.txt)

Cheers,
Edmund

**Comment by ChanchalYa** [comment]
Thank you so much, @edsu7!

Cheers,
Chanchal
