### ISSUE TITLE
Consensus sequence version update 

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#388]
Hi @edsu7,

Can you please update the following samples. I've included a csv with the 'old' and 'new' information by Specimen Collector Sample ID. 

Please let me know if you require anything else!

Thanks, 

Kirsten
[DP_Update_consensus_seq_version.csv](https://github.com/cancogen-virus-seq/portal/files/11491920/DP_Update_consensus_seq_version.csv)

**Comment by scottcain** [comment]
@edsu7 can you please take a look at this?

**Comment by KirstenPalmier** [comment]
Thank you! 

Kirsten

**Comment by KirstenPalmier** [comment]
Hi @edsu7 ,

I am so sorry, but I made a mistake with these samples. Can they be changed back to the original version? Re-attaching csv with requested versions included.

Kirsten 
[DP_Update_consensus_seq_version_reverted.csv](https://github.com/cancogen-virus-seq/portal/files/12134811/DP_Update_consensus_seq_version_reverted.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier ,

Sorry for missing this. I've updated the 7853 to their original versions.
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/6f220c8d-8652-46f1-ae01-20a50c86cc80)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you!
