### ISSUE TITLE
possible duplicates in arranger downloads

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#392]
From Chanchal:
```
When the metadata is downloaded for all the samples belonging to a Study ID (e.g. EH-NL), the downloaded file 
contains lots of duplicates, resulting in much higher sample# than what’s on the portal. Also, Nithu just noticed 
that when we try to download both the metadata and sequences for a specific Study ID the download includes
all the samples in the portal, not just for the Study ID selected.
```

**Comment by nithujohn** [comment]
Hi @scottcain , adding a comment I downloaded samples another study ID from Nova Scotia and found the same error. Looks like it's not to one study ID but has the issue for all the samples.

**Comment by scottcain** [comment]
@nithujohn and Chanchal, I think it may be fixed in production; there was a problem with the software that powers searching and filtering but we just updated it with something that I think will fix it. Please let me know.

**Comment by justincorrigible** [comment]
Changes deployed to prod. The issue has been resolved as far as we can tell on our end, but we'll rely on your approval before closing this ticket.

**Comment by leoraba** [comment]
Closing ticket due to inactivity.
