### ISSUE TITLE
Instrument update

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#393]
Good afternoon @edsu7,

Can you please update the following sample's Instrument field from "Missing" to "Oxford Nanopore PromethION"?

Specimen Collector Sample ID = QC_457358

Thank you!

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier 

`QC_457358`'s `sequencing_instrument` field has been updated from `Missing` to `Oxford Nanopore PromethION`.

Before:
![Screen Shot 2023-06-16 at 12 26 31 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/66ac17e8-3d32-4ae6-86f0-fa4fb783df24)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/d19e6c88-cae0-4d52-a8cd-026f25bd1ac1)

Cheers,
Edmund
