### ISSUE TITLE
NL Sequencing Protocol Update

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#394]
Good morning @edsu7,

Can you please update the following samples - where the previous sequencing protocol is blank - it can be replaced with the following (within the csv file).

Thank you!

Kirsten 
[NL_DP_Update_Sequencing_Protocol.csv](https://github.com/cancogen-virus-seq/portal/files/11918729/NL_DP_Update_Sequencing_Protocol.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The 16 samples have had their `sequencing protocol ` updated.

Before:
![Screen Shot 2023-06-30 at 2 50 11 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/a3afc5df-0cce-497a-9661-8d4d9ad61c80)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/3cade94b-4a7d-403f-9a48-5c3ce23fda7d)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you! Have a great weekend. :) 

Kirsten
