### ISSUE TITLE
QC Consensus Sequence Software Version Updates

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#396]
Hi @edsu7,

Can the following samples be updated to reflect the new consensus sequence versions in each file?

Thank you. Please let me know if you have any questions regarding this request.

Kirsten 
[QC_dataportal_update_file1.csv](https://github.com/cancogen-virus-seq/portal/files/12134768/QC_dataportal_update_file1.csv)
[QC_dataportal_update_file2.csv](https://github.com/cancogen-virus-seq/portal/files/12134769/QC_dataportal_update_file2.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

`19034`/`21497` samples' `consensus sequence software versions` have been updated. `2463` samples did not exist on the portal.

Before:
![Screen Shot 2023-08-09 at 9 12 41 AM](https://github.com/cancogen-virus-seq/portal/assets/22638361/5680e101-d583-41b7-9787-85e48a22ac7e)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/cea399d6-fb88-4670-808e-8ce2f640d1d4)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you!
