### ISSUE TITLE
Sample Redaction - BC

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#398]
Hi @edsu7 

I'm wondering if you could please remove 

BC_546323
BC_546308

![image](https://github.com/cancogen-virus-seq/portal/assets/52721825/ec2c36dd-076b-4ed5-aeef-7ae2867f910d)

They have been removed from GISAID and the province requests they also be removed from VirusSeq. 

Thank you! 
Emily

**Comment by GH-Emily** [comment]
apologies - please hold off on the redaction momentarily. I have to double check something quickly

**Comment by edsu7** [comment]
Hi @GH-Emily ,

Do you still need these samples removed?

Cheers,
Edmund

**Comment by GH-Emily** [comment]
> Hi @GH-Emily ,
> 
> Do you still need these samples removed?
> 
> Cheers, Edmund

Yes please!!

**Comment by edsu7** [comment]
Hi @GH-Emily,

Samples `BC_546323` and `BC_546308` have been removed.

Before:
<img width="1127" alt="Screen Shot 2023-08-10 at 10 55 36 AM" src="https://github.com/cancogen-virus-seq/portal/assets/22638361/b3b3a06c-d417-48ba-8cca-fa79d2959a99">


After:
<img width="246" alt="image" src="https://github.com/cancogen-virus-seq/portal/assets/22638361/e6b95f71-13e4-4469-90b9-b4dacc14210a">

Cheers,
Edmund

**Comment by GH-Emily** [comment]
thank you!
