### ISSUE TITLE
Request for collection date change

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#399]
Good day @edsu7,

Can you please change the Collection Date for the following sample:
BC_14922 (EPI_ISL_971097)
The old sample collection date = 2020-09-09
New sample collection date = 2020-12-04

Thank you!

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

`BC_14922`'s `sample collection date` please see below.
Original:
![Screen Shot 2023-08-16 at 9 41 50 AM](https://github.com/cancogen-virus-seq/portal/assets/22638361/b87fd96c-59f4-40d5-b5f5-d97dfe8ac93a)
Updated:
![Screen Shot 2023-08-16 at 9 45 12 AM](https://github.com/cancogen-virus-seq/portal/assets/22638361/26ce5ee6-ef27-4799-9c02-a061ddf1d08d)

Cheers,
Edmund

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

Long story short the time zones affect how the date is displayed on the UI - More details here:
https://github.com/cancogen-virus-seq/portal/issues/162

In the data itself, the date is correct:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/a4ec667d-f1ff-47d0-9314-04062391085b)

But as you mentioned the timezone on the UI would be off by a day.

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
AH! Makes sense. 

Thank you Edmund, 

Kirsten
