### ISSUE TITLE
Profile Page + logout Dropdown 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#4]
- [ ] Once a user logs in, profile icon shows in top rioght
- [ ] When clicked profile has link to `Profile` page and Logout option.
- [ ] Slight restyle for virus-seq:
Zeplin for Profile page: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/6064b9b3ad796803a52f8098

**Comment by caravinci** [comment]
Added this functionality, and made changes to the icons as instructed.
May have to implement the "Study Access" section of the user profile in a separate ticket.

**Comment by rosibaj** [comment]
Study access was not in scope of this ticket. i will create a separate ticket for that.
