### ISSUE TITLE
Request for Consensus Sequence Method Version change

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#400]
Hi @edsu7, 

Can you please update the following sample's consensus sequence method software name?
Sample: SK_565509
Old consensus sequence method software: https://github.com/phac-nml/ncov2019-artic-nf;nextflow nanopolish
New consensus sequence method software: https://github.com/phac-nml/ncov2019-artic-nf;nextflow medaka

Thank you!

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier 

`SK_565509`'s `Consensus sequenc software name` has been updated. Please see below
Before:
![Screen Shot 2023-08-17 at 2 35 39 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/d093a77f-6cb5-40fb-ab81-e85e9239b8e5)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/61d0f08e-bf6d-4d3d-932b-83ff0a94d442)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you!
