### ISSUE TITLE
Metadata Update AB - Consensus sequence method name and version

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#402]
Hi @edsu7,

Can you please update the following samples for both the Consensus sequence method name and version?

Same as the previous request--I am also curious to know if these fields have been changed on your end at some point as we have looked through our old submission files to see where the discrepancies came from but cannot seem to track it down.

Thank you!

Kirsten
[AB_consensus_seq_name_version_updateIssue574.csv](https://github.com/cancogen-virus-seq/portal/files/12372725/AB_consensus_seq_name_version_updateIssue574.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

Using `AB_82792`, it was first registered on `2021-09-21`. When looking at the data [release ](https://virusseq-dataportal.ca/releases) version `2021-09-23`, the software name and version were still `Nanopolish` and `0.13.2`.

So from our end these fields have not been updated.

Regarding the update:
- `4659` samples from this ticket and https://github.com/cancogen-virus-seq/portal/issues/401 have been updated.
- Note there were duplicates in the file [AB_consensus_seq_name_version_updateIssue574.csv](https://github.com/cancogen-virus-seq/portal/files/12372725/AB_consensus_seq_name_version_updateIssue574.csv)

Before:
![Screen Shot 2023-08-17 at 6 08 35 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/2f7e9570-d446-4462-a5f1-3b1b46a54f02)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/27e796bd-1c33-462f-9662-09e40b3d31f2)

Cheers,
Edmund
