### ISSUE TITLE
MB - Consensus Sequence Software name change

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#403]
Hi @edsu7 

I've come across some additional samples where the `consensus sequence software name` should be changed from `Freebayes` to `Nanopolish`

|Specimen collector sample ID|
|-|
|MB_194747|
|MB_194754|
|MB_194760|
|MB_194768|
|MB_194786|
|MB_194725|
|MB_194736|

Please let me know if you need anything further!

Thank you,

Kirsten Palmier

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The 7 samples listed in https://github.com/cancogen-virus-seq/portal/issues/403#issue-1855678870, have had their `consensus sequence software name` updated.

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/3ce0e48d-b01e-4140-a0ef-d6cbbbca611b)

After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/77a479ed-80c1-403c-aedd-ea726c948ae4)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thanks again Edmund,

Kirsten
