### ISSUE TITLE
AB Samples to be removed

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#405]
Good morning @edsu7 ,

Can the following 31 samples be removed from the database at the request of the province?

Thank you,

Kirsten 
|specimen collector sample ID|
|-|
|AB_82567|
|AB_82578|
|AB_82525|
|AB_82475|
|AB_82506|
|AB_82302|
|AB_82305|
|AB_82318|
|AB_82366|
|AB_82375|
|AB_82540|
|AB_82554|
|AB_82433|
|AB_82417|
|AB_82705|
|AB_82382|
|AB_82591|
|AB_82391|
|AB_82414|
|AB_82423|
|AB_82344|
|AB_82420|
|AB_82457|
|AB_82573|
|AB_82379|
|AB_82472|
|AB_82532|
|AB_82272|
|AB_82336|
|AB_82442|
|AB_82560|

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The requested 31 samples have been removed. 

Before:
![Screen Shot 2023-08-23 at 1 55 56 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/9fdead6e-bc3e-4bd7-90fc-dc68228043be)
Update:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/5136cc04-8ad5-4959-8736-806222649478)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thanks Edmond!

Kirsten
