### ISSUE TITLE
Metadata Update - Consensus Sequence Method Name (SK)

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#407]
Good day @edsu7 ,

I came across 4 samples with extra characters in the Consensus Sequence Method Name in Data Portal.
Can they please be updated to not include the extra characters? See below:
![image](https://github.com/cancogen-virus-seq/portal/assets/60520877/d35d7a24-7858-417d-9812-0c35c46dde73)

|Specimen Collector Sample ID|
|-|
|SK_348176|
|SK_382660|
|SK_411493|
|SK_367916|

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The four samples have been updated to remove trailing characters

Updated view:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/e4c4428c-bb91-4c13-95b8-2eb0a6329db7)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you @edsu7!

Kirsten
