### ISSUE TITLE
Collection Date Update

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#408]
Hi @edsu7! 

Could you please update the collection dates for the two samples listed below? The province provided updated information. 

QC_300592,2021-02-06
QC_291067,2021-01-09

Thank you!
Emily

**Comment by edsu7** [comment]
Hi @GH-Emily,

The `sample_collect_date` for `QC_300592` and `QC_291067` have been updated.

Before:
![Screen Shot 2023-08-24 at 1 31 27 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/b66a8675-dae2-4be5-a30e-468564b5c5c6)
Updated:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/87a3fbd1-cc0c-4ced-8cee-ea9137b813ff)

Cheers,
Edmund

**Comment by GH-Emily** [comment]
Thank you! :)
