### ISSUE TITLE
Collection Date Update 

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#409]
Hi @edsu7 

I'm wondering if you could please update one more collection date? 

QC_390244,2021-12-04

Thank you! 
Emily

**Comment by edsu7** [comment]
Hi @GH-Emily ,

`Sample Collection Date` for `QC_390244` has been updated. Please see below:

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/71c185c0-497f-444b-ba2d-eebe17065b5e)
Updated:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/e9863d76-f5bc-4a0c-90b5-78f8318d3a57)

Cheers,
Edmund
