### ISSUE TITLE
Add communication banner to the portal UI

### ISSUE THREAD

**Issue by akachru-github** [cancogen-virus-seq/portal#41]
- With upcoming shutdowns from Scinet and Collab maintenance, the Virus-seq portal will become unavailable for short periods of time. 
- We will need to be able to communicate the outage alerts leading up to the scheduled maintenance via a banner along the top of the portal UI. 
- The text will need to be easily updated via github.

**Comment by akachru-github** [comment]
- Make banner change in Virus-seq, and port back generic changes to DMS-UI. 
- ICGC25k
  - toggle to be dismiss-able
  - supports regular text and linked text
  - stored in environment variables

**Comment by jaserud** [comment]
Deployed into dev with the three variants visble: error, warning and info

**Comment by rosibaj** [comment]
Banners verified and deployment to production completed.  thank you @jaserud !
