### ISSUE TITLE
Metadata Update - Consensus Sequence Method Name - QC

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#410]
Good afternoon @edsu7,

Can you please update the following values in the `Consensus Sequence Method Name` from `Nanopolish` to `iVar`? 

Thank you, 

Please let me know if you require anything further.

Kirsten 

|Specimen Collector Sample ID|
|-|
|QC_134796|
|QC_134797|
|QC_134640|
|QC_134641|
|QC_134645|
|QC_134649|
|QC_134651|
|QC_134652|
|QC_134654|
|QC_134655|
|QC_134658|
|QC_134659|
|QC_134664|
|QC_134665|
|QC_134668|
|QC_134669|
|QC_134671|
|QC_134672|
|QC_134673|
|QC_134674|
|QC_134675|
|QC_134677|
|QC_134679|
|QC_134680|
|QC_134681|
|QC_134682|
|QC_134684|
|QC_134685|

</body>

</html>

**Comment by edsu7** [comment]
Hi @KirstenPalmier ,

`consensus sequence software name` for the 28 samples listed above have been updated:

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/de0293c5-de77-425e-a538-22f0cebf9d0c)
Updated:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/01736a8a-44b7-4f64-8466-2c1800ae5928)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you Edmund!

Kirsten
