### ISSUE TITLE
Purpose of Sequencing update for QC

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#413]
Good morning @edsu7 , 

Can you please update the Purpose of Sequencing field for the following samples (csv attached)?

Thank you,

Kirsten 
[QC_purpose_of_sequencing_upate_Issue597.csv](https://github.com/cancogen-virus-seq/portal/files/12674731/QC_purpose_of_sequencing_upate_Issue597.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

178 samples' `Purpose of Sequencing` have been updated. See below for an example.

Previously:
![Screen Shot 2023-09-20 at 12 16 13 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/d53aa08b-303f-481a-862c-58bae2b19356)

Updated:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/41810b2f-7254-4987-9fa8-64f274d6430a)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you! 

Kirsten
