### ISSUE TITLE
QC - Consensus Sequence version update 

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#414]
Good morning @edsu7,

I believe these should be the last of the historic samples needing updates for consensus sequence method versions for Quebec.

Please find the attached csv with Specimen Collector Sample IDs and the old/new values.

Let me know if you require anything further or have any questions! 
[QC_dataportal_consensus_seq_version_update_Issue605.csv](https://github.com/cancogen-virus-seq/portal/files/12751794/QC_dataportal_consensus_seq_version_update_Issue605.csv)

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The consensus sequence method version have been updated for 1016 samples. Please see below.

Before:
![Screen Shot 2023-10-03 at 1 10 22 PM](https://github.com/cancogen-virus-seq/portal/assets/22638361/19c37d53-cc00-4531-8c20-b97303732dfe)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/82c83c5d-95fe-4c97-a2ed-c2fc10a7a8f9)

**Comment by KirstenPalmier** [comment]
Thank you!

Kirsten
