### ISSUE TITLE
QC - collection date update

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#415]
Good morning @edsu7 ,

Can the collection date for the sample QC_291067 be updated **from**  `2021-01-09` **to 2021-02-06**.

Thank you!

Kirsten Palmier

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

the `sample collection date` for `QC_291067` has been updated. See below:

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/3a911b02-fa74-4336-a647-a01527b4e370)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/6ad421a9-1416-4a62-9e00-cc2b280eac6c)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Hi @edsu7 -- sorry the date is 2021-02-**06** not 2021-02-05. Thanks!

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The value in database is `2021-02-06` but due to the browser's timezone shows `2021-02-05`. The same thing occurs in the before photo too.

Edmund

**Comment by KirstenPalmier** [comment]
Ah! Right, I forgot about this quirk. 

Thank you for the confirmation!

Kirsten
