### ISSUE TITLE
Update metadata schema

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#417]
Hi @scottcain, can you please update the metadata schema for the fields "sample_collected_by" and "sequence_submitted_by" with the below tag, Thanks!

"Newfoundland and Labrador - Newfoundland and Labrador Health Services"

**Comment by scottcain** [comment]
Hi @nithujohn one question about this: should we also remove "Newfoundland and Labrador - Eastern Health" so that it can't appear in future submissions?

**Comment by nithujohn** [comment]
Hi @scottcain, NML wants to keep it as well as they can't submit if there is any old sequences

**Comment by scottcain** [comment]
OK, that makes sense--just wanted to double check.

**Comment by lindaxiang** [comment]
@scottcain @nithujohn , the schema has been updated upon the request. Please give a try!

**Comment by nithujohn** [comment]
@lindaxiang I checked the schema and I can see the names in the schema..... Thank you so much!
