### ISSUE TITLE
Update for Acknowledgement Page For New Foundland

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#418]
Hi @scottcain, Can you please update the acknowledgement page with the below names, Thanks!

"Newfoundland and Labrador - Newfoundland and Labrador Health Services" (previously known "Newfoundland and Labrador - Eastern Health")

**Comment by scottcain** [comment]
@leoraba Can I ask you to do this? I have edited that page before, but it always seems to take me longer than it should :-)

**Comment by justincorrigible** [comment]
💪 Leo's busy with Keycloak. 

I'm on it!

**Comment by scottcain** [comment]
@nithujohn We can change the content in the Ack page but there is currently no mention of "Eastern Health" Currently, it looks a like this:

**Newfoundland and Labrador**
_Dr. Leonard A. Miller Centre for Health Services; National Microbiology Laboratory_
...individual names...

So should the "Dr. Leo ... Laboratory" be replaced with the text you provided above?

**Comment by nithujohn** [comment]
@scottcain yea I checked it and needs to replace Dr.Leo ...... Lab

**Comment by nithujohn** [comment]
@justincorrigible can you include the ones I included in the brackets (previously known "Newfoundland and Labrador - Eastern Health") as well. Thanks :)

**Comment by justincorrigible** [comment]
AH! I see what you meant now! apologies. like so?
Also, should I make it "known as"? (missing the "as" right now)

![image](https://github.com/cancogen-virus-seq/portal/assets/2107110/b94dfd03-7bd8-418d-b821-e3619040d483)

**Comment by nithujohn** [comment]
Yea! Thank you so much @justincorrigible

**Comment by justincorrigible** [comment]
Changes deployed and publicly available.
Please advice if any further changes are needed 👍
