### ISSUE TITLE
Accidental duplicate submission 2023-11-02 (20 samples)

### ISSUE THREAD

**Issue by molpratt** [cancogen-virus-seq/portal#419]
Hi @lindaxiang,

Sorry to do this to you again, but I've accidentally uploaded the wrong files to the Data Portal today. I'm wondering if you'd be able to remove the following 20 duplicate samples, where the submission date is today (November 02, 2023). 
```
submission id: 
c2d48704-89ab-4f6a-8e35-ab4e8ca8e959

NL_647781
NL_647782
NL_647783
NL_647784
NL_647785
NL_647786
NL_647787
NL_647788
NL_647789
NL_647790
NL_647791
NL_647792
NL_647793
NL_647794
NL_647795
NL_647796
NL_647797
NL_647798
NL_647800
NL_647801
```
Apologies, I will try my best to avoid this in the future! 

Thank you for your help, 
Molly

**Comment by edsu7** [comment]
Hi @molpratt,

The duplicate samples have been removed. Please see below for an example:

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/ee4a5dc4-b43a-4f91-aa7f-c5d220ef53e8)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/84fc3b7e-0d52-4939-9f72-bd9fa6680caf)

Cheers,
Edmund

**Comment by molpratt** [comment]
Thank you, Edmund!
