### ISSUE TITLE
Support external maintenance page for virus-seq portal

### ISSUE THREAD

**Issue by akachru-github** [cancogen-virus-seq/portal#42]
- With upcoming shutdowns from Scinet and Collab maintenance, the Virus-seq portal will become unavailable for short periods of time.
- During the outage (scheduled or otherwise), we will need have users directed to a maintenance page. This can be manually triggered. 
- Since the virus-seq portal is hosted entirely on Collab, this page will need ot be hosted externally. Netlify was suggested as an option. 
- virus-seq coordinate the dns change. let's make sure the DNS TTL's (Time To Live) are low. 
  -  Dont' want the DNS change to take forever to propogate

## Maintenance page UI

We are just going with a similar design to the login page. Ping Kim for the background image.

Zeplin: https://zpl.io/br3GAg7
- [ ] Regarding footer: keep the footer but hide the `Policies` and `Submitter Login` links

![image](https://user-images.githubusercontent.com/18424138/118305430-f35d7280-b4b5-11eb-8495-fe7bcde9c5b2.png)

**Comment by akachru-github** [comment]
- Devops for DNS change
- We will need a design for this. Reach out to @kcullion for this.

**Comment by akachru-github** [comment]
Reference to IHCC maintenance page:  https://github.com/IHCC-cohorts/ihcc-ui/tree/develop/src/components/MaintenancePageContent

**Comment by rosibaj** [comment]
contact link: info@virusseq-dataportal.ca 
other link: https://www.genomecanada.ca/en/cancogen/cancogen-virusseq

**Comment by rosibaj** [comment]
@lepsalex can you add these links to the images:
- https://www.genomecanada.ca/
- https://www.overture.bio 
- https://github.com/cancogen-virus-seq
