### ISSUE TITLE
QC and ON sample updates for Consensus Sequence Software and Version

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#420]
Good day @edsu7 ,

Can you please update the following samples:
|Specimen Collector Sample ID| Old consensus sequence software name| New consensus sequence software name| old version| new version|
|-|-|-|-|-|
|ON_31631|ncov2019-artic-nv (OICR v1.5)|**iVar**|1.5|**1.3**|
|QC_41771|iVar|**Nanopolish**|0.13.2|**no change**|
|ON_365036|Freebayes|**iVar**|1.3.2|**1.3**|

Please let me know if you have any questions.

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The request samples have had their consensus sequence software name and version altered accordingly.

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/329982fa-47c9-46ef-9764-9cd9e19a5fb7)

After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/16198c97-8a47-4d73-8f53-db169757ddcc)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you!
