### ISSUE TITLE
AB Consensus Sequence Software Version Update

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#421]
Good afternoon @edsu7 ,

Can you please update the following samples attached in terms of the Consensus Sequence Software Version?

If you have any questions, please do not hesitate to reachout.

Kirsten 
[AB_consensus_software_version_update_Issue661.csv](https://github.com/cancogen-virus-seq/portal/files/13453243/AB_consensus_software_version_update_Issue661.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

Updates on  `Consensus Sequence Software Version` have been applied to the 149 samples.

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/e3911ba6-15fd-4feb-ac9a-3a7932a421e4)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/c6ff00c5-579d-4111-b73b-63732974ad22)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you Edmund,

Have a great day!
