### ISSUE TITLE
MB Consensus Sequence Software Version Update

### ISSUE THREAD

**Issue by JeffTuff** [cancogen-virus-seq/portal#422]
Hi @edsu7,

Please update the `Consensus Sequence Software Version` for samples in the attached file as indicated.

[VirusSeq_mb_medaka_161_181_n_14_update.csv](https://github.com/cancogen-virus-seq/portal/files/13491317/VirusSeq_mb_medaka_161_181_n_14_update.csv)

Thank you!

Jeff

**Comment by edsu7** [comment]
Hi @JeffTuff ,

The following samples have had their consensus sequence software version updated from `1.8.1` to `1.6.1`:
```
MB_638062
MB_638064
MB_638065
MB_638067
MB_638069
MB_638070
MB_638071
MB_638072
MB_638073
MB_638074
MB_638075
MB_638076
MB_638077
MB_638078
```

See below for before and after screenshots:
Before -
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/421e12ea-a168-4c28-ad4a-49eda02f2262)
After -
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/63522592-9ea1-4730-802c-9ca41f30e7f7)

Cheers,
Edmund
