### ISSUE TITLE
Samples to redact

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#423]
Good afternoon @edsu7 ,

Can the following samples please be redacted from the VirusSeq:

|Specimen Collector Sample ID|
|-|
|ON_471855|
|ON_471849|
|ON_471991|
|ON_472005|
|ON_472006|
|ON_471798|
|ON_471603|
|ON_472200|
|ON_472196|
|ON_472007|
|ON_472030|
|ON_471861|
|ON_472348|
|ON_472349|
|ON_472357|
|ON_471794|
|ON_472040|
|ON_471848|
|ON_472207|
|ON_471792|
|ON_472209|
|ON_472205|
|ON_472204|
|ON_472194|
|ON_472004|
|ON_471992|
|ON_471793|
|ON_471854|
|ON_471853|
|ON_471851|
|ON_472210|
|ON_472199|
|ON_472352|
|ON_472202|
|ON_472201|
|ON_472195|
|ON_472351|
|ON_472211|
|ON_472034|
|ON_472033|
|ON_472345|
|ON_471862|
|ON_471852|
|ON_472208|
|ON_472206|
|ON_472354|
|ON_472213|
|ON_472035|
|ON_471847|
|ON_472032|
|ON_472198|
|ON_472045|
|ON_472350|
|ON_471850|
|ON_472346|
|ON_472197|
|ON_471859|
|ON_472212|
|ON_471997|
|ON_472036|
|ON_471796|
|ON_472347|
|ON_472203|
|ON_471797|
|ON_472031|
|ON_472344|
|ON_472038|
|ON_472037|
|ON_472003|
|ON_472044|
|ON_472039|
|ON_472353|
|ON_471860|
|ON_472002|
|ON_471791|
|ON_472046|
|ON_471795|
|ON_472043|
|ON_471846|
|ON_472355|

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The samples you listed have been suppressed and no longer appear on the portal

Before :
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/00100023-4a2d-4cc1-a6e1-712751000f74)

After :
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/0c7237dd-4fee-43fb-9355-9cfd340bd529)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you @edsu7 !

Kirsten
