### ISSUE TITLE
Update metadata schema

### ISSUE THREAD

**Issue by molpratt** [cancogen-virus-seq/portal#425]
Hi @scottcain, 

We've had a request from our partner labs to add a value to the metadata schema for the "anatomical part" field. The new requested value is "Throat". 
 
Thank you,

Molly

**Comment by edsu7** [comment]
Hi @GH-Emily and @molpratt,

Update has been applied and is live on the portal

![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/818d751a-566d-4470-a520-1afecb0c4818)

Cheers,
Edmund
