### ISSUE TITLE
BC - Collection Date updates and single sample redaction

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#426]
Good afternoon @edsu7 ,

May the following samples be modified according to the table below? 

|Specimen Submitter ID|Old Collection Date|New Collection Date|
|-|-|-|
|BC_13540|2020-11-17|2020-10-17|
|BC_14245|2020-11-28|2020-11-27|

Lastly, this single sample can be removed:  BC_15251

Thank you!

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The collection dates for `BC_13540` and `BC_14245` have been applied and `BC_15251` has been removed.

Please see below (reminder that dates on the UI are shifted b/c of time zones)

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/2cea1807-2708-4a82-b0e3-31d0b8335eb2)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/0e3ac701-7adf-4769-b040-56d419143b0c)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you! 

Have a great day. 

Kirsten
