### ISSUE TITLE
Sample Redaction

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#427]
Hi @edsu7 

Ontario has requested the redaction of the following three samples: 

ON_593811
ON_593813
ON_593812

I'm wondering if you could please remove them from the portal? 

Thank you!

**Comment by edsu7** [comment]
Hi @GH-Emily,

The samples `ON_593811`,`ON_593812`,`ON_593813` have been removed.

Please see below.

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/58ba3758-b431-4a62-994b-ca1deb509c73)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/0a05aa99-31fe-450d-a684-13634a0a03cc)

Cheers,
Edmund
