### ISSUE TITLE
Updates to Acknowledgements Lists

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#428]
Hi there, 

We would like to request some updates to the [acknowledgements](https://virusseq-dataportal.ca/acknowledgements). 

------------------------------------
**Alberta:** 

_Genomes with prefix ABPHL_
Bu J, Croxen M, Deo A, Dieu P, Dong X, Ferrato C, Gavriliuc S, George R, Getachew F, Gill, K, Ie N, Khadka R, Khan F, Koleva P, Lee L, Li V, Lindsay A, Lloyd C, Lynch T, Ma R, McCullough, E, Mohon A, Murphy S, Obasuyi O, Pabbaraju K, Presbitero A, Rotich S, Shokoples S, Thayer J, Tipples G, Trevor H, Whitehouse M, Wong A, Yu C, Zelyas N 
 
_Genomes in collaboration with UC (prefix AB-NNNNNN)_
Gordon P, Lam LG, Pabbaraju K, Wong A, Ma R, Li V, Melin A, Tipples G, Berenger B, Zelyas N, Kellner J, Bernier F, Chui L, Croxen M

------------------------------------
**British Columbia:**

_BCCDC Public Health Laboratory_
Prystajecky Natalie, Linda Hoang, John R. Tyson, Dan Fornika, Shannon Russell, Kim MacDonald, Kimia Kamelian, Ana Pacagnella, Corrinne Ng, Loretta Janz, Richard Harrigan, Robert Azana, Tara Newman, Jessica Caleta, Sherrie Wang, Janet Fung, Mel Krajden

------------------------------------
**Manitoba:**

_Cadham Provincial Laboratory collected specimens sequenced at the National Microbiology Lab (NML)_
Paul Van Caeseele, Jared Bullard, David Alexander, Kerry Dust.

_NML_

_Cadham Provincial Laboratory sequenced specimens_
David Alexander, Lori Johnson, Janna Holowick, Joanne Sanders, Adam Hedley, Kerry Dust, Ayo Bolaji, Brooke Cistarelli, Emma Rempel, Paul van Caeseele, Jared Bullard. 

_Dynacare sequenced specimens_
Hilary Racher, Melissa Desaulnier, Tintu Abraham, Hongbin Li (Impact Genetics, Brampton Ontario)

------------------------------------

**New Brunswick:**

_Centre Hospitalier Universitaire Georges L. Dumont_
Beauregard AP., Lyons P., Chacko S., Shaw W., Lacroix J., Allain E., Crapoulet N., Garceau R., Desnoyers G.

_NML_

------------------------------------

**Newfoundland and Labrador:**

_Newfoundland and Labrador Health Services (previously known as "Newfoundland and Labrador - Eastern Health")_
Robert Needle, Yang Yu, Laura Gilbert, George Zahariadis, Geoffrey Woodland, Chris Corkum, , Kerri Smith, Phillip Andrews, Matthew Gilmour

_NML_

------------------------------------
**Nova Scotia:**

_QEII Health Sciences Centre*_ 
Todd Hatchette, Jason LeBlanc, Janice Pettipas, Dan Gaston, Greg McCracken. (*data tagged post September 14th, 2022 should include Allana Loder)

_NML_

------------------------------------

**Ontario:**

_Public Health Ontario Laboratory_
Jacob Afelskie,Vanessa G Allen, Rebecca Azzaro, Doonia Bajovic, Philip Banh, Ilse Belgrave , Tom Braukmann, Ashley Carandang, Yao Chen, Claudia Chu, Shawn Clark, Kirby Cronin, Richard de Borja, Rachelle DiTullio, Carla Duncan, Hadi El Roz, Alireza Eshaghi, Nahuel Fittipaldi, Christine Frantz, Dhiraj Gaglani, Nicole Graham, Jonathan B Gubbay, Jennifer L Guthrie, Lawrence Heisler, Daniel Heydari, Mark Horsman, Hadia Hussain, Jason Iraheta, Grace Jeong, Esha Joshi, Sushma Kavikondala, Lisa Kim, Surendra Kumar, Michael Laszloffy, Aimin Li, Michael C.Y. Li, Alex Marchand-Austin, Maria Mariscal, Dean Maxwell, Lisa McTaggart, Fatima Merza, Anupam Mittal, Naadia Mohammed, Esther Nagai, Sandeep Nagra, Shiva Nassori, Paul Nelson, Rima Palencia, John Palmer, Samir N Patel, Stephen Perusini, Nataliya Potapova, Anna Puzinovici, Zarah Rajaei, Christina Rampertab, Himeshi Samarsinghe, Candice Schreiber, Christine Seah, Fatemeh Shaeri, Kapil Shaeri, Kapil Shah, Narisha Shakuralli, Natasha Singh, Karthikeyan Sivaraman, Brenda Stanghini, Ashleigh Sullivan, Vincent Su Bin Cha, Yogi Sundaravadanam, Sarah Teatero, Semra Tibebu, Nobish Varghese, Andre Villegas, Jesse Wang, Matthew Watson, Sichong Xu, Xiao Xu, Kent Young, Sophie Yu, Farhan Yusuf, Sandra Zittermann

_Ontario Institute for Cancer Research_
- no changes requested at this time

_McMaster University_
- no changes requested at this time

------------------------------------

**Québec:**

_Laboratoire de Santé Publique du Québec, McGill Génome Sciences Centre; CoVSeq Consortium_
Sandrine Moreira, Jiannis Ragoussis, Guillaume Bourque, Éric Fournier, Aurélie Guilbault, Benjamin Delisle, Dihya Baloul, Inès Levade, Sarah Reiling, Hector Galvez, Paul Stretenowich, Alexandre Montpetit, Michel Roger, Judith Fafard

------------------------------------

**Saskatchewan:**

_Roy Romanow Provincial Laboratory_
Ryan McDonald, Keith MacKenzie, Kara Loos, Stefani Kary, Meredith Faires, Guruprasad Janga, Rachel DePaulo, Laura Klassen, Alanna Senecal, Amanda Lang, Jessica Minion, Roy Romanow Provincial Laboratory - Molecular Diagnostics.

_NML_

------------------------------------

Requesting a **new section** for NML, to be listed as it's own bolded section last in the list::

------------------------------------
**Canada's National Microbiology Laboratory (NML):** 

Anna Majer, Shari Tyson, Grace Seo, Philip Mabon, Elsie Grudeski, Rhiannon Huzarewich, Russell Mandes, Anneliese Landgraff, Jennifer Tanner, Natalie Knox, Morag Graham, Gary Van Domselaar, Nathalie Bastien, Ruimin Gao, Cody Buchanan, Jasmine Frost, Ameet Bharaj, Cole Slater, Nikki Toledo, Laura Hart, Yan Li, Timothy Booth, Catherine Yoshida, Genevieve Labbe, Adina Bujold, Kara Loos, Jennifer Beirnes, Michael Przybytkowski, Patrick Bastedo, Debra Sorensen, Andrea Tyler, Ana Duggan, Darian Hole, Madison Chapel, Kristen Biggar, Emily Haidl, Chanchal Yadav, Jeff Tuff, Connor Chato, Katherine Eaton, Kirsten Palmier, Molly Pratt, Amber Papineau and Adrian Zetner.

**Comment by GH-Emily** [comment]
I've completed the Canada's National Microbiology Laboratory (NML) section, now just awaiting response from BC

**Comment by GH-Emily** [comment]
I've completed the BC update request in the message above! @scottcain

**Comment by scottcain** [comment]
@GH-Emily because of the migration from OICR to McGill, this update may take a little longer than we would otherwise have hoped (we need to get a build environment set up at McGill); is a delay acceptable?

**Comment by GH-Emily** [comment]
> @GH-Emily because of the migration from OICR to McGill, this update may take a little longer than we would otherwise have hoped (we need to get a build environment set up at McGill); is a delay acceptable?

I believe a delay to the actual page is okay! I might have another update to add in anyways. 

However, I believe these updates were requested by the VirusSeq team for the purposes of an upcoming publication. @nithujohn can confirm.

**Comment by scottcain** [comment]
I had a feeling that might be the case, so we should make publication as a hard deadline.

**Comment by nithujohn** [comment]
@scottcain yea for the data portal and duotang manuscript requested this update. I have also updated on the manuscript draft notifying Erin that there is a ticket with the names updated for acknowledgements

**Comment by eringill** [comment]
@scottcain, the updated acknowledgements list has been added to the manuscript. 

I received an email from PEI via the CPHLN secretariat that they should also be added to the acknowledgements section as follows:

---
**Prince Edward Island**

_Queen Elizabeth Hospital_
Xiaofeng Ding, Vanessa Arseneau, Kari-Lyn Young

_NML_

**Comment by scottcain** [comment]
@GH-Emily One more detail: when I read this initial issue, I read it as a "replace" operation, which is to say, take whatever is on the acknowledgments page and replace it with what's in this issue. A dev I was chatting with today pointed out that it could also me a "merge" operation, merging in what's in this issue with what's on the page. Before we commit changes, I just wanted to double check which it is :-)

**Comment by GH-Emily** [comment]
@scottcain updates were provided to me as "replace"! Thank you so much :)

**Comment by scottcain** [comment]
@GH-Emily @eringill 
The acknowledgements page has been updated: https://virusseq-dataportal.ca/acknowledgements Please let me know if you see any issues. Feel free to close the issue if all is well.

**Comment by eringill** [comment]
@scottcain @GH-Emily could you please add Cindy Bell and Catalina Lopez-Correa to the acknowledgements section under _CanCOGeN VirusSeq Implementation Committee_  

Thank you!

**Comment by scottcain** [comment]
@justincorrigible Can you please add this to your considerable "to do" list? @eringill as heads up: I expect this will take longer than one would otherwise expect because the portal build tools are not in place at SD4H yet, so rebuilding the portal right now is a bit of a Rube Goldberg process.

**Comment by eringill** [comment]
Could you please change the last paragraph of this section so that it reads:

Funding for the VirusSeq Data Portal has been provided by The Canadian COVID Genomics Network (CanCOGeN), supported by Genome Canada and Innovation, Science and Economic Development Canada (ISED), plus the Canadian Institutes of Health Research (CIHR) - Coronavirus Variants Rapid Response Network (CoVaRR-Net).

Thank you!

**Comment by justincorrigible** [comment]
Hey @eringill @scottcain. I've made the changes requested, and they should be publicly visible now at https://virusseq-dataportal.ca/acknowledgements.
Closing ticket as "done"
