### ISSUE TITLE
NS Purpose of Sequencing Update

### ISSUE THREAD

**Issue by molpratt** [cancogen-virus-seq/portal#429]
Hi @edsu7 

Could you please update the Purpose of Sequencing to Targeted Surveillance for the following sample from NS?

| specimen collector sample ID | old PoS | new PoS |
|---|---|---|
| NS_695256 |Baseline surveillance (random sampling) | Targeted surveillance (non-random sampling) | 

Thank you!

Molly

**Comment by edsu7** [comment]
Hi @molpratt,

`NS_695256`'s `Purpose of Sequencing` has been updated.

Please see below -

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/3b328a05-5dab-4b4c-b0c1-410b8fc4763f)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/a5fb58d9-472c-44c7-a712-ef4927bfff20)

Cheers,
Edmund

**Comment by molpratt** [comment]
Thank you!
