### ISSUE TITLE
Data Redaction - Saskatchewan Samples

### ISSUE THREAD

**Issue by GH-Emily** [cancogen-virus-seq/portal#430]
Hi @edsu7 

I'm wondering if you could please remove: 

SK_428125
SK_428126

from the portal? 

Thank you! 
Emily

**Comment by edsu7** [comment]
Hi @GH-Emily ,

`SK_428125` and `SK_428126` have been suppressed. Please see below:

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/b8c1b77f-3083-4e12-9f53-bcd9e7d931e6)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/63715074-464d-4406-996e-b5e0908b7fef)

Cheers,
Edmund

**Comment by GH-Emily** [comment]
thank you!

**Comment by Computational-and-Operational-Genomics** [comment]
Hi @edsu7  

I've realized SK_428125 was redacted in error. I'm wondering if you're able to make that record visible again please? 

Emily

**Comment by GH-Emily** [comment]
@edsu7 

I've realized that I requested the redaction of SK_428125 in error. I'm wondering if you could please make this record visible again? 

Emily

**Comment by edsu7** [comment]
Hi @GH-Emily,

`SK_428125` has been reuploaded.

![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/b18eec01-f8a8-4098-9d81-3226bec92af0)

Cheers,
Edmund

**Comment by GH-Emily** [comment]
@edsu7 thank you!!
