### ISSUE TITLE
Data Redaction - ON sample

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#431]
Good morning @edsu7 ,

Can the following sample please be redacted from the VirusSeq Database at the request of the PT? 

ON_584525

Thank you!

Kirsten

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

`ON_584525` has been redacted. Please see below.

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/da00edfd-322a-4d9b-8c08-b02f9db1795c)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/28750c4d-3fc4-4411-ae8e-a62336c032e3)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you! 

Kirsten
