### ISSUE TITLE
Update metadata schema - Purpose of Sequencing

### ISSUE THREAD

**Issue by molpratt** [cancogen-virus-seq/portal#433]
Hi @edsu7 

We would like to add a new "purpose of sequencing"  value to the metadata schema. 

The new value is:

"Chronic (prolonged) infection surveillance"

Thank you, 

Molly

**Comment by edsu7** [comment]
Hi @molpratt,

`purpose of sequencing` has been updated to now include `Chronic (prolonged) infection surveillance`.

![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/7063d756-a341-418f-9318-34e7be6cb789)

Cheers,
Edmund

**Comment by molpratt** [comment]
Thank you kindly, Edmund!

Would it be possible to now update the `purpose of sequencing` value for the following SK sample to the new Chronic surveillance value?


specimen collector sample ID | old PoS | new PoS
-- | -- | --
SK_700220 | Targeted surveillance (non-random sampling) | Chronic (prolonged) infection surveillance

Thanks again for your help, 

Molly

**Comment by edsu7** [comment]
Hi @molpratt 
Sample `SK_700220`'s `purpose of sequencing` has been updated.

![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/1aa45883-f706-4aba-b6b9-f1dcff71b778)

Cheers,
Edmund

**Comment by molpratt** [comment]
Lovely, thanks!!
