### ISSUE TITLE
Data Redaction Request - ON

### ISSUE THREAD

**Issue by molpratt** [cancogen-virus-seq/portal#435]
Hi @edsu7 

We have mistakenly added some duplicate files to the Portal. Could you please remove the following 68 records from ON where the submission date == 2024-04-12 ? 
![image](https://github.com/cancogen-virus-seq/portal/assets/141779800/547c8306-71ed-4c4c-a2a6-cd192f02b662)

### IDs:
ON_707600
ON_707602
ON_707126
ON_707189
ON_707607
ON_707606
ON_707177
ON_707188
ON_707174
ON_707601
ON_707170
ON_707208
ON_707574
ON_707201
ON_707241
ON_707244
ON_707248
ON_707129
ON_707247
ON_707127
ON_707245
ON_707258
ON_707120
ON_707194
ON_707237
ON_707256
ON_707261
ON_707096
ON_707547
ON_707093
ON_707548
ON_707092
ON_707099
ON_707083
ON_707080
ON_707540
ON_707593
ON_707236
ON_707232
ON_707599
ON_707154
ON_707274
ON_707214
ON_707271
ON_707580
ON_707105
ON_707259
ON_707192
ON_707077
ON_707185
ON_707064
ON_707086
ON_707191
ON_707195
ON_707183
ON_707087
ON_707220
ON_707221
ON_707579
ON_707583
ON_707225
ON_707587
ON_707146
ON_707145
ON_707148
ON_707130
ON_707251
ON_707278

Thank you very much!

Molly

**Comment by edsu7** [comment]
68 duplicate records with submission date `2024-04-12` have been removed

Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/7d630be1-43ea-45ad-b5db-2f10185992e0)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/b07d386e-f768-4071-b00f-e377dbf2d27b)

Cheers,
Edmund

**Comment by molpratt** [comment]
Thank you so much!

Molly
