### ISSUE TITLE
Re-enable Downloads + Visible columns

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#45]
- [x] Add the download functionality BACK on the search page (e.x https://github.com/cancogen-virus-seq/portal/issues/32)
- [x] Now that the questionable data has been suppressed, we can add some columns back as visible to the platform: 
  - Add the `Isolate` column as an option to select for columns 
  - Add `host age` as a facet, and option for selection in the column.  This should be a default visible column.

**Comment by caravinci** [comment]
Changes applied. Awaiting confirmation, in order to replicate to prod.

**Comment by rosibaj** [comment]
Deployed and verified on production environment May 20, 3:37
