### ISSUE TITLE
Update Policies text

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#47]
page: https://virusseq-dataportal.ca/policies
text updates:  https://docs.google.com/document/d/1xg-U-kFGYEhJmpkwqC1tcR3nFDz4H_tFsIelIi30z3E/edit#

**Comment by jaserud** [comment]
updates to policy page: https://github.com/cancogen-virus-seq/portal/pull/49/commits/405e3a244cfe9b98d3ba0ac227a85ff15b00fba5

**Comment by rosibaj** [comment]
@jaserud can i get one update just to the date:

...This privacy policy was last revised on `May 31 2021`. ...

**Comment by rosibaj** [comment]
lgtm thank you @jaserud

**Comment by rosibaj** [comment]
confirmed on production
