### ISSUE TITLE
Add Links to Site Banners + Permanent Banner 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#48]
- [ ] Add the ability to add links to banners.
- [ ] Add this Banner 
**Banner Type:** Info and Dismissible 
**Banner Title:** IMPORTANT: Data Acknowledgement 
**Banner Content:** You may use the data from the Canadian VirusSeq Data Portal to author results obtained from data analyses, provided that your published results [acknowledge](https://virusseq-dataportal.ca/acknowledgements ) the Canadian Public Health Laboratory Network (CPHLN), CanCOGeN VirusSeq, and all laboratories having contributed data. The full acknowledgement and data use policy can be found [here](https://virusseq-dataportal.ca/policies).  Please note that the data that is being shared is the work of many individuals and should be treated as unpublished data. If you wish to publish research using the data, contact us at info@virusseq-dataportal.ca first to ensure that those who have generated the data can be involved in its analysis. You are responsible to make the best efforts to collaborate with representatives of the data providers responsible for obtaining the specimen(s) and involve them in such analyses and further research using such data.  

------

links 
- https://virusseq-dataportal.ca/policies 
- https://virusseq-dataportal.ca/acknowledgements

**Comment by b-f-chan** [comment]
Related to #158 - @sifavahora please determine if there is duplication with #158 and whether we just need one ticket vs two

**Comment by sifavahora** [comment]
I see the acknowledgements link/button in the banner already but that contradicts with https://github.com/cancogen-virus-seq/portal/issues/246. need to confirm what needs to be done.

**Comment by sifavahora** [comment]
closing for now.
