### ISSUE TITLE
Add authorized login to portal

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#5]
- [x] Add login button to portal. 
- [x] When user logs in and gets navigated to the `Submission Dashboard` page.  Right now, this page can just be blank (or put some template text or something) with the expected header/footer.
- [x] `Dashboard` link appears in header and is selected for the user.

**Comment by caravinci** [comment]
These changes have been deployed. Notes:
- The login button is available in the footer as discussed, although its position (3rd element) can easily be changed if necessary; and it disappears once a user logs in.
- "Dashboard"'s contents are a 1:1 copy of the "submitter login" page, but it is a different route, as visible in the URL and the highlighted tab.

**Comment by rosibaj** [comment]
Feedback for the logout path - once i logout i should be logged out of Keycloak as well. 

![image](https://user-images.githubusercontent.com/15824252/114226501-a24fe100-9941-11eb-853f-07f74553863e.png)

- there is a url the browser can navigate to in keycloak to log you out of keycloak as well
- https://keycloak.virusseq-dataportal.ca/auth/realms/virusseq/protocol/openid-connect/logout?redirect_uri=<our_logout_redirect_url>\
- the redirect url can be the about landing page

**Comment by caravinci** [comment]
Logout redirection should work now as specified.

**Comment by rosibaj** [comment]
tested April 12 2021. lgtm now!
