### ISSUE TITLE
Support External Read Only Site for Maintenance - Needed June 9-11

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#51]
- UI Pages only
- remove submitter login in footer
- disable the explore tab, and the explore button from homepage
- No new data can be posted. 
- hosted on Netlify 
- Add a `warning` banner to this site with the text: 
```
Data exploration, download and upload are currently unavailable due to site maintenance.  Service should return shortly after the maintenance window completes on June 9. 
```

**Comment by jaserud** [comment]
Preview page here: https://deploy-preview-1--nostalgic-kare-282903.netlify.app/
