### ISSUE TITLE
Incorrect sample collection date

### ISSUE THREAD

**Issue by ArtPoon** [cancogen-virus-seq/portal#54]
Apologies if this isn't the correct issue tracker to report this.  I just noticed that sample `L00248453` has a collection date of `2011-01-01`, which is very unlikely and not consistent with the year field in the sample name (isolate).

**Comment by ArtPoon** [comment]
Data retrieved from portal on June 9.

**Comment by rosibaj** [comment]
@lindaxiang Can you please take a look at this submission error?

**Comment by rosibaj** [comment]
This has been corrected. thank you @ArtPoon for the big submission!
