### ISSUE TITLE
Data Submission UI: My Dashboard

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#6]
- [x] No submissions state:
Zeplin Link:  https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/60709965780d473c6a005059
![image](https://user-images.githubusercontent.com/15824252/114222688-df65a480-993c-11eb-887a-76b4a14b5e9a.png)
- [x] User has submissions state:
- Zeplin Link: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/60661ca311c5a192df146d9f
![image](https://user-images.githubusercontent.com/15824252/114222771-f99f8280-993c-11eb-9f7a-ee906729d55e.png)
- [x]  Endpoint to power the UI: https://muse.virusseq-dataportal.ca/swagger-ui/#/Muse/Get%20Submissions

- Submissions are linked to a users **egoid**.  Users should **only** see submissions that they have started.

**Comment by caravinci** [comment]
Deployed new version. Still pending: sorting and pagination.

**Comment by rosibaj** [comment]
new version looks good; will move back to in progress to review sorting and pagination when it is ready!

**Comment by caravinci** [comment]
Sorting is complete. Reprioritising pagination for a different ticket as per Christina's instruction.

**Comment by rosibaj** [comment]
thanks @caravinci I will close this ticket now.
