### ISSUE TITLE
Suppress Duplicated Data 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#68]
- there are 10 duplicated samples from the Jul 13 AB Data Upload
```
AB_47576
AB_47577
AB_47578
AB_47579
AB_47580
AB_47581
AB_47582
AB_47583
AB_47584
AB_47585
```

- [ ] Suppress the duplications in analysis

**Comment by lindaxiang** [comment]
The following analysis have been suppressed in SONG:

**analysisId**|**sampleId**|**studyId**
:-----:|:-----:|:-----:
e9db3eb1-1003-49a9-9b3e-b11003f9a90f|AB\_47576|ABPL-AB
f7e73cdd-4def-4ebb-a73c-dd4def9ebb8e|AB\_47577|ABPL-AB
b6a36142-7e10-4788-a361-427e10c788be|AB\_47578|ABPL-AB
ad967dbc-1890-4c14-967d-bc1890ec143e|AB\_47579|ABPL-AB
c63ca5ca-823d-4d55-bca5-ca823ddd55ab|AB\_47580|ABPL-AB
e276fb9f-09c7-461b-b6fb-9f09c7d61ba7|AB\_47581|ABPL-AB
77e77150-3d39-426f-a771-503d39126f99|AB\_47582|ABPL-AB
a2565ddc-c8fb-4d27-965d-dcc8fbed27d9|AB\_47583|ABPL-AB
fc4ac475-4f9b-4b73-8ac4-754f9b9b73c1|AB\_47584|ABPL-AB
eb7cfbe7-b254-476a-bcfb-e7b254376a1f|AB\_47585|ABPL-AB
