### ISSUE TITLE
Data Submission: Start a New Submission

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#7]
- [x] Upload Files: started submission with file error: https://zpl.io/aNNGENv
The submit button should be enabled iif there is one TSV file and at least one FASTA file. 
- [x] valid submission ready: https://zpl.io/amPzLrm
- [x] Submission loader: https://zpl.io/2p8QRLN
- [x] Validation error: https://zpl.io/V0vnrdm

**Comment by rosibaj** [comment]
April 16 2021 Feedback (morning round):

- [ ] fix color of metadata file icon
![image](https://user-images.githubusercontent.com/15824252/115051717-20186d00-9eab-11eb-9d4c-84f5cd894f51.png)
- [ ] When i have only one metadata file, i cannot use the delte. i have to use clear all. i should be able to delete this.  This does not happen for FASTA files.
![image](https://user-images.githubusercontent.com/15824252/115051963-6077eb00-9eab-11eb-9581-05acb95d64b0.png)
- [ ] Buttons should be the same size (34 px tall defined in zeplin)
![image](https://user-images.githubusercontent.com/15824252/115052169-9fa63c00-9eab-11eb-9d33-5a510916cc86.png)
- [ ]  Error should be full width:
![image](https://user-images.githubusercontent.com/15824252/115052505-0297d300-9eac-11eb-8f25-34e5a7a0990b.png)

I cant use the UI to complete a submission (I get an Internal Server Error) with data that i believe should work.  Will attempt some postman uploads to verify.

**Comment by caravinci** [comment]
> fix color of metadata file icon

Not quite sure why the .tsv are not showing blue for you 🤔
They're fairly different colours on my screen. 
<img width="580" alt="Screenshot 2021-04-16 at 12 47 41" src="https://user-images.githubusercontent.com/2107110/115057485-20683680-9eb2-11eb-9031-fd97387b9e46.png">

---

> When i have only one metadata file, i cannot use the delete. i have to use clear all.

Cannot reproduce in any of my browsers. May have to jump on a call to troubleshoot this one.

---

The other changes, plus a fix for the auth issue should be available to test now. 👍

**Comment by rosibaj** [comment]
- still experiencing delete issue and tsv file issue (Windows 10/Chrome) 
- still experiencing a not full width error as well
![image](https://user-images.githubusercontent.com/15824252/115067498-04b75d00-9ebf-11eb-866f-13264fd4c486.png)

**Comment by caravinci** [comment]
Deployed a new version. Hopefully these issues will go away now.

**Comment by rosibaj** [comment]
Moving back to in progress as the issues mentioned above still exist 
- can replicate in Windows/Chrome and Windows/Firefox

**Comment by rosibaj** [comment]
Tested April 20, 2021
- icons are correct color 
- i can now delete tsv files as desired, no issues. 

- can start a valid and invalid submission, with the expected flows.
