### ISSUE TITLE
Aug 2020: Update schema/add fields for Virus-Seq

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#71]
There will be additional fields added to the virus-seq dataset: 
- 4 new, optional fields.  https://github.com/cancogen-virus-seq/metadata-schemas/issues/8
## Steps to Update
- [ ] Data harmonizer template update
- [ ] Song - https://github.com/cancogen-virus-seq/metadata-schemas/issues/8
- [ ] ES mapping - https://github.com/cancogen-virus-seq/roadmap/issues/29
- [ ] Muse update needed 
       https://github.com/cancogen-virus-seq/muse/issues/80
- [ ] Singularity update needed - https://github.com/cancogen-virus-seq/singularity/issues/15
- At this point all deploys are done, and need to do a reindex. Portal in maintenance with  down time. 
- [ ] UI deployment with updated new fields - https://github.com/cancogen-virus-seq/portal/issues/70
- [ ] Payloads Update - https://github.com/cancogen-virus-seq/roadmap/issues/30

**Comment by lindaxiang** [comment]
- [ ] Payloads update - https://github.com/cancogen-virus-seq/roadmap/issues/30
