### ISSUE TITLE
Update Portal UI to use Arranger to generate sets for user selection

### ISSUE THREAD

**Issue by akachru-github** [cancogen-virus-seq/portal#72]
- Have arranger build a set and pass that set ID to singularity. 

Zeplins: 
- [x] https://zpl.io/a7pD9Jj
When you click download this modal launches and stays open.  the loader spins in the corner while the operation is caclulating.  Once the file is ready, it autodownloads.  If it is a download all file that is already ready, force the loader for 2 seconds just for consistency. 

- [x] https://zpl.io/bzxpEWl When the download is complete, trasition the loader to a complete message.  the user can close the modal whenever they want.

**Comment by andricDu** [comment]
Waiting on design.

**Comment by rosibaj** [comment]
deployed September 02, 2021
