### ISSUE TITLE
Suppress AB Data

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#74]
The data was uploaded without the fasta header format as expected ` >hCoV-19/country/identifier/year sequenced.`

Nithu will update the data, but we need the current AB dataset suppressed. 

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/190a58be-8100-4e3d-9dba-036989678834)****

**Comment by lindaxiang** [comment]
All 9955 analysis have been suppressed from the portal.

**Comment by rosibaj** [comment]
@Linda Xiang i have heard back regarding the upload that was supposed to replace this suppression.  It has been confirmed that the incorrect replacement data was uploaded.  Can you please suppress the AB data again?
