### ISSUE TITLE
Investigate wrong or duplicated PHO-ON data 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#75]
## Steps to fid data  
- select all samples with (2) values on the facet on the left hand side of the portal 
- sort the table on sample submitter id. You will see tht there are 2 rows.  

## Data description
- The data compared between rows is wildly different, for the same sample id.  For example, in one the gender switches (`ON_125804`) and in another the age bin is 20 years different (`ON_125805`). 

![image](https://user-images.githubusercontent.com/15824252/129949406-0cdd4b9e-098f-4d1a-9846-e3985ab6ce46.png)

## Expected outcome

Have a list of items to suppress based on what is the correct data.

**Comment by nithujohn** [comment]
Can you suppress all the samples with duplicates as there was a database error. I have receieved the corrected files and could you let me know once it is suppressed. Thanks!

**Comment by rosibaj** [comment]
@lindaxiang Can you please suppress all samples with a count of (2) in the PHO-ON study?

**Comment by lindaxiang** [comment]
@rosibaj 84 analysis which have duplicated samples are suppressed on the portal.

**Comment by rosibaj** [comment]
thank you @lindaxiang  - confirmed on portal UI.
