### ISSUE TITLE
Theming/Styling Keycloak pages 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#9]
- [x] Update the theme to design: https://zpl.io/brqjAy5
- [x]  Add common password restrictions [at least 8 characters, one number one symbol] 
- [x] Add terms and conditions page into the flow with permission. 
- [x] Update the email copy (@rosibaj please provide copy for this) on account verification. 
- [x] Figure out how to add the Keycloak theme to the production deployment 
- [x] Change "VirusSeq Porta" to "VirusSeq Data Portal"

**Comment by andricDu** [comment]
@yalturmes This is the current devops related problem we need to solve:

We have this git repo here: https://github.com/cancogen-virus-seq/cancogen-keycloak-theme

We need to mount cancogen folder in that git repo as `/opt/jboss/keycloak/themes/keycloak` inside the container/pod running keycloak.

We use the bitnami helm chart for keycloak: https://github.com/bitnami/charts/tree/master/bitnami/keycloak
It has the following config that could be useful:
```
extraVolumeMounts	Optionally specify extra list of additional volumeMounts for Keycloak container(s)	[]
extraVolumes	Optionally specify extra list of additional volumes for Keycloak pods	[]
```

We need to figure out how to get that folder into a volume that is mounted by keycloak.

**Comment by rosibaj** [comment]
confirmed last bullet & can see changes and themes in prod.  lgtm thank you @lepsalex @andricDu!!
